### ISSUE TITLE
Does new latest versison has armbi so file?

### ISSUE THREAD

**Issue by stevenwsg** [objectbox/objectbox-java#1008]
I readed this problem: https://github.com/objectbox/objectbox-java/issues/605. It writted on 2019, three years later, does this question hava new solution?

I provided sdk to some other manufacture. I want to,  other manufacturer can easy insert our sdk.

Now , i used version is 2.3.4

If no other way ,can you tell me which repo can let me build a armbi so file?

**Comment by stevenwsg** [comment]
Some manufacture build app only save armbi so file, v7a can not save in app, relinker can not solve this problem

**Comment by greenrobot-team** [comment]
ObjectBox only supports `arm64-v8a`, `armabi-v7a` and `x86_64` as well as `x86` on Android. https://docs.objectbox.io/faq#on-which-platforms-does-objectbox-run

When using App Bundle it should no longer be required to use the workarounds mentioned in https://docs.objectbox.io/android/app-bundle-and-split-apk. If you still observe issues, please report with more details (e.g. what devices are affected).
