### ISSUE TITLE
ObjectBox prevents the loading of my other .so libraries

### ISSUE THREAD

**Issue by TechNov** [objectbox/objectbox-java#1012]
**Describe the bug**
I have been using OBjectobx for years and everything is working fine.
These last days I have been developing an Android Java App still using Objecbox. But in addition to that, my App, which is specially made for a Payment Terminal (PAX A920), must interact with peripherals (magnetic card reader, NFC card, ...). For that, the PAX builder provided me with .so files ("libDeviceConfig.so", ...) to integrate into my project in order to handle these peripherals.
My issue is the following:
1. When I integrate Objecbox and NDK .so (in a jniLibs / armeabi directory), the project crach at runtime I get this error: .... couldn't find "libDeviceConfig.so" when I want access the card reader for example. but the Objectbox is working.
2. When I create a project integrating the .so files alone, Without integrating Objectbox, the project works well and I manage to interact with the peripherals of the PAX A920 terminal.
Apparently ObjectBox uses a "libobjectbox-jni.so" file so its loading process prevents the loading of other .so files that I have integrated myself.
How to make my project work with these two tools (Objecbox and the .so files) please. help
PAX Library and Demo App: https://docs.hips.com/docs/pax-a920

APK Aanalysis;
.so libraries Only in my Project [https://ibb.co/7CqKXZS](https://ibb.co/7CqKXZS)
.so And ObjectBox both integrated in my oroject  [https://ibb.co/qmccPyk](https://ibb.co/qmccPyk)

**Basic info (please complete the following information):**
 - ObjectBox version:2.9.1
 - Reproducibility: integrate Objectbox and an others .so library in you app 
 - Device: All device who i test my App ( Pax A920, emulator, Huawei Y9 Prime, Sunmi V2Pro)
 - OS: Android 7.1.xxx and android 10

**To Reproduce**
1. install PAX Library and Demo App: https://docs.hips.com/docs/pax-a920
2. Run App got to "PICC" Menu ==>detectAorBBandCommand
3. App will not crash . if it chrash, the cause will not be `**couldn't find "libDeviceConfig.so"** `
2. Add Objectbox 2.9.1 in this demmo project,
3. Run projetc, got to "PICC" Menu ==>detectAorBBandCommand
4. App will crash because it cant find libDeviceConfig.so in the _/src/main/jniLibs/armeabi_ folder

**Comment by greenrobot-team** [comment]
> is -it possible to recompile .so file from the old armeabi to new architecture?

Not that I know of.

It seems the SDK/API provided at https://docs.hips.com/docs/pax-a920 does not include armeabi-v7a support. The [used Cortex A7](https://static.hips.com/pdf/sheets/A920_EN_20200515.pdf) chipset could [support it though](https://developer.arm.com/ip-products/processors/cortex-a/cortex-a7). Maybe you can ask for an armeabi-v7a version of the libraries.

Anyhow, you can try to extract the `armeabi-v7a` version of `libobjectbox-jni.so` and move it to the `armeabi` folder (and use the `abiFilters "armeabi"` ABI filter)? Maybe that works.

Side note: you do not need to manually copy the ObjectBox `.so` files into the `libs` folder. Including the `objectbox-android` dependency is enough.

**Comment by TechNov** [comment]
The device PAX A920 support armeabi-v7a well.

but the SDK is thery old i thank.
I remember that those armeabi .so files require Android min SDK 16 to be loaded by the system.

the device infos [https://imgur.com/JoAY8cI](https://imgur.com/JoAY8cI).

**Comment by TechNov** [comment]
i have do it like you recommanded.
in the App gradle
```
...
android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.pax.demo1"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 38
        versionName "V3.24.00_20210519"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
         ndk {
           abiFilters 'armeabi'//, 'armeabi-v7a' //'x86', 'x86_64', 'arm64-v8a',
       }
    }
...
```
in the  grandle.proprieties 

`android.useDeprecatedNdk=true`

in the jniLibs/armeabi
                 ==>libDeviceConfig.so
                 ==>libobjectbox-jni.so

when i run, the App crash always...

**Comment by greenrobot-team** [comment]
If the system supports `armeabi-v7a` it should not be necessary to manually copy the `.so` files. It should be enough to just apply the ObjectBox plugin, or [manually add all dependencies](https://docs.objectbox.io/advanced/advanced-setup#manually-add-libraries). Also do not specify any `abiFilters` then.

Android should then first look in the `armeabi-v7a` folder, then in the `armeabi` folder when loading native libraries.

**Comment by taq** [comment]
> i have do it like you recommanded. in the App gradle
> 
> ```
> ...
> android {
>     compileSdkVersion 28
>     defaultConfig {
>         applicationId "com.pax.demo1"
>         minSdkVersion 16
>         targetSdkVersion 28
>         versionCode 38
>         versionName "V3.24.00_20210519"
>         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
>          ndk {
>            abiFilters 'armeabi'//, 'armeabi-v7a' //'x86', 'x86_64', 'arm64-v8a',
>        }
>     }
> ...
> ```
> 
> in the grandle.proprieties
> 
> `android.useDeprecatedNdk=true`
> 
> in the jniLibs/armeabi ==>libDeviceConfig.so ==>libobjectbox-jni.so
> 
> when i run, the App crash always...

Hey, just got the same situation here, did you find a solution?

**Comment by TechNov** [comment]
Hi, 

> > i have do it like you recommanded. in the App gradle
> > ```
> > ...
> > android {
> >     compileSdkVersion 28
> >     defaultConfig {
> >         applicationId "com.pax.demo1"
> >         minSdkVersion 16
> >         targetSdkVersion 28
> >         versionCode 38
> >         versionName "V3.24.00_20210519"
> >         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
> >          ndk {
> >            abiFilters 'armeabi'//, 'armeabi-v7a' //'x86', 'x86_64', 'arm64-v8a',
> >        }
> >     }
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the grandle.proprieties
> > `android.useDeprecatedNdk=true`
> > in the jniLibs/armeabi ==>libDeviceConfig.so ==>libobjectbox-jni.so
> > when i run, the App crash always...
> 
> Hey, just got the same situation here, did you find a solution?

Hi, not a solution as such, I had to give up ObjecBox for Realm DB

**Comment by taq** [comment]
What worked for me: just created `armeabi` and `armeabi-v7a` under `app/src/main/jniLibs/`, put `libDeviceConfig.so` inside both directories and it worked! At first Mapbox was complaining with only `armeabi` dir, but when I created both, solved the problem.

**Comment by xuanthuan-UFO** [comment]
I got this error 2 days ago when work with Pax920. Analyze the apk and i see the file libs/libDeviceConfig.so but this err still happen.

Just add android:extractNativeLibs="true" in AndroidManifest and the problem solved.
