### ISSUE TITLE
No implementation found for nativeGreater & nativeLess methods

### ISSUE THREAD

**Issue by davidhowe** [objectbox/objectbox-java#1014]
Lib version io.objectbox:objectbox-android:3.0.1

Using 
1. .greater(_property_, _value_) on the box QueryBuilder _OR_ 
2. .less(_property_, _value_) on the box QueryBuilder 

returning errors: 
1. Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long io.objectbox.query.QueryBuilder.nativeGreater(long, int, long, boolean) (tried Java_io_objectbox_query_QueryBuilder_nativeGreater and Java_io_objectbox_query_QueryBuilder_nativeGreater__JIJZ)

2. Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long io.objectbox.query.QueryBuilder.nativeLess(long, int, long, boolean) (tried Java_io_objectbox_query_QueryBuilder_nativeLess and Java_io_objectbox_query_QueryBuilder_nativeLess__JIJZ)

Reverting to using _between_ for now to keep project working

**Comment by greenrobot-team** [comment]
Thanks for reporting, but can not reproduce. This sounds like your project has a dependency on an old version of `objectbox-android` (something older than 2.9.0). Check that all the ObjectBox dependencies are at the same version (are you maybe using `objectbox-android-objectbrowser` and forgot to update its version for debug builds?). Running the `dependencies` Gradle task can be helpful.
