### ISSUE TITLE
default.json line break type

### ISSUE THREAD

**Issue by zhangguangxuan** [objectbox/objectbox-java#1017]
Is there a function to specify the line break type when creating the default.json? e.g. LF, CR or CRLF.

**Comment by greenrobot-team** [comment]
No there is not. I doubt one will be added.

Is there are reason you need this option?

**Comment by zhangguangxuan** [comment]
The default.json is CRLF in our git server.

**Comment by greenrobot-team** [comment]
Thanks! Closing this as a duplicate of #181 Please thumbs up that issue instead!
