### ISSUE TITLE
Generate Meta Models for abstract base classes

### ISSUE THREAD

**Issue by Ditscheridou** [objectbox/objectbox-java#1018]
The framework allow entity inheritance and enables you to define some base properties on entity classes. But it will not generate a Meta model class for this abstraction. I would expect the framework to do so, so you can make fetches based on this abstraction. It feels very in-consequent here, the developer now has to implement workarounds to be able to make fetches based on a abstract property.

**Comment by greenrobot-team** [comment]
I don't see exactly how this would work, can you give a concrete example? E.g. the returned objects could then be of various types which would break a lot of assumptions the ObjectBox API makes, no?
