### ISSUE TITLE
Hint: use closeThreadResources() to avoid finalizing recycled transactions

### ISSUE THREAD

**Issue by gitHubDujianfeng** [objectbox/objectbox-java#1025]
Skipping low-level close for read-only cursor (non-creator thread '')
2021-11-22 17:24:47.119 22486-22495/com.fuiou.pay.saas I/System.out: Hint: use closeThreadResources() to avoid finalizing recycled transactions (initial commit count: 3).

The version number of objectbox used is 2.8.1. This error is always reported when inserting data and querying data. How to solve it? I've seen your official solution before. Using closethreadresources can't solve this problem

**Comment by greenrobot-team** [comment]
Does your code insert/query data in a short-lived thread? If yes, before that thread ends make sure to call `BoxStore.closeThreadResources()`.

For additional help please create a minimal example or share at least some code.
