### ISSUE TITLE
io.objectbox.exception.FileCorruptException

### ISSUE THREAD

**Issue by unengchen** [objectbox/objectbox-java#1032]
android 8.1
objectbox 2.9.1

io.objectbox.exception.PagesCorruptException:Could not open database environment ; please check options and file system ( page not found ) ( error code: -30797)

**Comment by greenrobot-team** [comment]
Maybe the solution at https://github.com/objectbox/objectbox-java/issues/646#issuecomment-585217604 can help. TL;DR: Where is the database stored? Maybe change to a more reliable storage location.

If you can reliably reproduce this, please provide us with a small code example and more details.
