### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by LdwHly** [objectbox/objectbox-java#1042]
我app里使用了ormlite的框架，现在想转为objectBox，我应该怎么处理数据迁移？有例子参考一下吗

**Comment by greenrobot-team** [comment]
For the future please post in English so everyone can easily understand.

There is no migration guide for OrmLite to ObjectBox. Note that ObjectBox is **not** a SQL-based database.

But basically: create the database model in ObjectBox, then run some migration code e.g. on app launch.
