### ISSUE TITLE
DbException: Order: Unsupported type for property where type is kotlin.Long

### ISSUE THREAD

**Issue by marek-embiq** [objectbox/objectbox-java#1045]
The main issue is that the `order()` method does not work for kotlin.Long argument/property.

Basic info:
 - ObjectBox version 3.1.0
 - Reproducibility: always
 - Device: custom
 - OS: Android 7

The code where the issue occurs 

`val nextAvailableId = animals.query()`
`                    .orderDesc(Animal_.deliveryId) //sort desc -> first = highest `
                    `.build()`
                    `.findFirst()?.deliveryId // get highest`
                   ` ?.plus(1) // increment to get first available`
                    `?: 1 // set 1 if there is no record`

I think the code above doesn't need any additional description.

The exception is:
io.objectbox.exception.DbException: Order: Unsupported type for property deliveryId

and value deliveryId is a kotlin.Long

I can't test it on a regular smartphone because it is a project for a quite specific device. All project dependencies are up to date so maybe the old android is the real problem in my case.

**Comment by greenrobot-team** [comment]
With a data class like:
```kotlin
data class ExampleEntity(
        @Id var id: Long = 0,
        var example: String? = null
)
```
and a query like `box.query().orderDesc(ExampleEntity_.id).build().find()` results are returned as expected.

Can you share the code of the entity class? And are you saying this only occurs on that specific device? Does it occur on Android emulator (if it's possible to run your app there) as well?

**Comment by silver-butte** [comment]
I can't share the whole class code. 

I also use data class. 
Here is part of the code responsible for deliveryId:
```
@Entity
data class Animal(
    @Id(assignable = true)
    var id: Long = 0,
    @SerializedName("delivery_id")
    var deliveryId: Long = 0,
...
) {
...
    @Exclude
    var delivery = ToOne<Delivery>(this, Animal_.delivery)
...
}

@Entity
data class Delivery(
    @Id(assignable = true)
    var id: Long = 0,
...
) {
...
}
```

As you can see I'm using the relation feature in my code but I think it doesn't matter in my case.

After commenting out code using custom features of "custom device" used in my project I was also able to run it on Android emulator and also on Pixel 5. In both cases, the exception is the same as on the custom device.

**Comment by marek-embiq** [comment]
I can't share the whole class code. 

I also use data class. 
Here is part of the code responsible for deliveryId:
```
@Entity
data class Animal(
    @Id(assignable = true)
    var id: Long = 0,
    @SerializedName("delivery_id")
    var deliveryId: Long = 0,
...
) {
...
    @Exclude
    var delivery = ToOne<Delivery>(this, Animal_.delivery)
...
}

@Entity
data class Delivery(
    @Id(assignable = true)
    var id: Long = 0,
...
) {
...
}
```

As you can see I'm using the relation feature in my code but I think it doesn't matter in my case.

After commenting out code using custom features of "custom device" used in my project I was also able to run it on Android emulator and also on Pixel 5. In both cases, the exception is the same as on the custom device.

**Comment by greenrobot-team** [comment]
Actually the relation is the issue. `devliveryId` is [a special relation target ID](https://docs.objectbox.io/relations#expose-the-toone-target-id-property) property used for the `ToOne` relation. It is not possible to order by it.

This would require ordering results by the ID of a related entity (here `Delivery`), this feature request is tracked in #141.

As a workaround it would be possible to not used the reserved name, but instead e.g. `deliveryIdForOrder` and set this manually to the `Delivery` id in addition to setting the target on the `ToOne`.

**Comment by marek-embiq** [comment]
Yep, that was it, thanks for the explanation. I've solved the problem by using sort(), but still waiting for feature request #141 that will make my code cleaner :)
