### ISSUE TITLE
merge objects on conflict

### ISSUE THREAD

**Issue by andrew-ld** [objectbox/objectbox-java#1046]
if I try to add a new object in a store but there is a univocity rule currently can either give an exception or replace the object with a new one.

it would be useful to have a new conflict rule that allows you to merge the 2 objects into a single one and update the existing object with the data merged from the two objects.

**Describe the solution you'd like**
- add "MERGE" on the enum "ConflictStrategy"
- add to the "Entity" annotation the "objectsMerger" attribute (required to use the merge strategy)
- "objectsMerger" is the implementation of ObjectsMerger<T>.

```

public interface ObjectsMerger<T> {
   /** this method updates the attributes of "stored" */
   merge(T stored, T new);
}
```

**example of an entity allowing merge.**
```

class ExampleMerger: ObjectsMerger<MergiableEntity> {
    override fun merge(T stored, T new) {
         stored.resourceName = new.resourceName
         stored.resourcePath = new.resourcePath
    }
}

@Entity(objectsMerger = ExampleMerger::class)
data class MergiableEntity(
    @Id
    var id: Long,

    @Index
    @Unique(onConflict = ConflictStrategy.MERGE)
    var resourceUuid: String

    var resourceName: String

    var resourcePath: String
)
```

**Comment by greenrobot-team** [comment]
Thanks! This should be discussed as part of #1023.
