### ISSUE TITLE
ObjectboxLiveData.getValue returns null

### ISSUE THREAD

**Issue by Schmalztopf** [objectbox/objectbox-java#1047]
Hello,

is there a reason why ObjectboxLiveData does not return any result when calling getValue()?

Bet regards
Thomas Gramer

**Comment by greenrobot-team** [comment]
If the query has not run yet and posted the result, the value will be `null`. For the query to run and post the result there must be at least one active observer.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to comment with more information or create a new issue.
