### ISSUE TITLE
Small typo in website

### ISSUE THREAD

**Issue by drmathewsgit** [objectbox/objectbox-java#1056]
Sync typo in main webpage
![CleanShot 2022-03-03 at 20 09 38](https://user-images.githubusercontent.com/22167887/156586993-0a9e7215-735c-4c27-93d7-f9370d186f84.png)
)

**Comment by greenrobot-team** [comment]
Thanks!

**Comment by ivahnenkoAnna** [comment]
That's fixed now, thanks for letting us know!
