### ISSUE TITLE
change the database name

### ISSUE THREAD

**Issue by swanfly** [objectbox/objectbox-java#1058]
Our Android App requires multi-user login，Before logging in, the database name is entity. After logging in, i want to change the database name to entity-uid, and how to reinitialize the boxstore, thanks.

**Comment by swanfly** [comment]
Thank you very much for your answer. I will try your plan after my another project is over.

**Comment by greenrobot-team** [comment]
@swanfly Thanks for the response! I will close this issue then as resolved. Feel free to comment again if this isn't working as expected.
