### ISSUE TITLE
Data Observers with limit

### ISSUE THREAD

**Issue by GXSZone** [objectbox/objectbox-java#1064]
is there any progress

**Comment by GXSZone** [comment]
in addition, only the modified data is returned

**Comment by greenrobot-team** [comment]
I don't follow. Is this a feature request? Or does this refer to an existing issue? Please share some additional details.

**Comment by GXSZone** [comment]
#602 and #303

**Comment by greenrobot-team** [comment]
You could write your own observer based on a general `DataObserver`, this is also what the Query observer does internally: https://docs.objectbox.io/data-observers-and-rx#observing-general-changes

Then you can run whatever query you like, including with offset and limit in the `onData` callback. E.g:
```kotlin
class LimitOffsetNoteObserver(
    private val store: BoxStore,
    private val observer: DataObserver<List<Note>>,
    private val offset: Long,
    private val limit: Long
) : DataObserver<Class<Note>> {
    override fun onData(data: Class<Note>) {
        val results = store.boxFor(Note::class)
            .query(Note_.text.contains("TODO"))
            .build()
            .find(offset, limit)
        observer.onData(results)
    }
}

// Keep the subscription while used 
// to avoid garbage collection of the observer.
subscription = store.subscribe(Note::class.java)
    .observer(LimitOffsetNoteObserver(store, observer, offset, limit))
```

To only return data that was modified additional code would be required.
