### ISSUE TITLE
io.objectbox.exception.DbMaxReadersExceededException

### ISSUE THREAD

**Issue by NBXXF** [objectbox/objectbox-java#1066]
user rxjava  Schedulers.newThread() Will not appear DbMaxReadersExceededException but user Schedulers.io()  It's easy to appear
```kotlin
 for (i in 0..100) {
    val box = getBox(this)
    Observable.just(1)
        .subscribeOn(Schedulers.newThread()) //           .subscribeOn(Schedulers.io())
        .map {
            Thread.sleep(Random.nextLong(10000))
            val all = box.boxFor(Teacher::class.java).query().build().find()

            System.out.println("===========>测试一个线程:" + all + "  " + Thread.currentThread().name)
            val find = box.boxFor(Teacher::class.java).query().build().find(0, 1)
            System.out.println("===========>测试一个线程2:" + find + "  " + Thread.currentThread().name)
            true
        }.doOnError {
            System.out.println("===========>测试一个线程:异常了:" + it + "  " + Thread.currentThread().name)
        }
        .subscribe()
}
```

**Comment by greenrobot-team** [comment]
See #1000, specifically https://github.com/objectbox/objectbox-java/issues/1000#issuecomment-890385226 for a discussion on this. I guess that explains this, assuming `Schedulers.newThread()` basically is an unbounded thread pool?

**Comment by NBXXF** [comment]
> See #1000, specifically [#1000 (comment)](https://github.com/objectbox/objectbox-java/issues/1000#issuecomment-890385226) for a discussion on this. I guess that explains this, assuming `Schedulers.newThread()` basically is an unbounded thread pool?

noReaderThreadLocals  did solve my problem,thank you very much

**Comment by greenrobot-team** [comment]
Thanks for reporting back. Closing this then!
