### ISSUE TITLE
Loading native library failed

### ISSUE THREAD

**Issue by zimspy007** [objectbox/objectbox-java#1073]
**Describe the bug**
Loading native library failed.

**Basic info (please complete the following information):**
 - ObjectBox version 2.9.1
 - Reproducibility: Occasionally a single device
 - Device: Galaxy A2 Core 
 - OS: Android 8.1.0

**Logs, stack traces**
Stack trace
```java
Fatal Exception: java.lang.LinkageError
[ObjectBox] Loading native library failed, please report this to us: vendor=The Android Project,os=linux,os.arch=armv8l,model=null,android=true,linux=true,machine=armv8l
io.objectbox.internal.NativeLibraryLoader.<clinit> (NativeLibraryLoader.java:112)
io.objectbox.internal.NativeLibraryLoader.ensureLoaded
io.objectbox.BoxStore.<init> (BoxStore.java:257)
io.objectbox.BoxStoreBuilder.build (BoxStoreBuilder.java:498)
com.yootok.database.objectbox.ObjectBox.init (ObjectBox.java:20)
com.yootok.activities.CustomApplication.onCreate (CustomApplication.java:88)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1119)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
Caused by java.lang.UnsatisfiedLinkError
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yootok-kAcVIfMYsY77HT-X6d9NjA==/base.apk"],nativeLibraryDirectories=[/data/app/com.yootok-kAcVIfMYsY77HT-X6d9NjA==/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libobjectbox-jni.so"
java.lang.Runtime.loadLibrary0 (Runtime.java:1011)
java.lang.System.loadLibrary (System.java:1657)
io.objectbox.internal.NativeLibraryLoader.<clinit> (NativeLibraryLoader.java:86)
io.objectbox.internal.NativeLibraryLoader.ensureLoaded
io.objectbox.BoxStore.<init> (BoxStore.java:257)
io.objectbox.BoxStoreBuilder.build (BoxStoreBuilder.java:498)
com.yootok.database.objectbox.ObjectBox.init (ObjectBox.java:20)
com.yootok.activities.CustomApplication.onCreate (CustomApplication.java:88)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1119)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:810)
```

**Additional context**
 - Is there anything special about your app? - No there is nothing special or worth mentioning about the app.
 - Workarounds to prevent the issue -  We have not found workarounds as yet.
 - This problem seems to occur only on the specified device. We have more than 50 test devices and this one is the only one that faces this issue. Other Samsung devices with Android 8 do not get this error.

**Comment by greenrobot-team** [comment]
`dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yootok-kAcVIfMYsY77HT-X6d9NjA==/base.apk"],nativeLibraryDirectories=[/data/app/com.yootok-kAcVIfMYsY77HT-X6d9NjA==/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libobjectbox-jni.so"`

It appears the APK installed is missing the `lib/armeabi-v7a` folder that would contain the `libobjectbox-jni.so` shared library for the `armv8l` architecture (this is ARMv8 running in 32-bit mode) of that device.

Make sure your build process produces the correct APK resp. App Bundle. E.g. maybe there is an abiFilter configured in your build script?

**Comment by zimspy007** [comment]
There are no abi filters in our app. The file is definitely there in the apk. I have attached a screenshot of the lib folder for armeabi-v7a
![Screenshot 2022-04-26 140607](https://user-images.githubusercontent.com/45720533/165296535-d1863c99-5f72-40e6-b9b8-ed4eb6c5310a.jpg)

**Comment by greenrobot-team** [comment]
As this is on your test device: can you please update to the latest ObjectBox version and collect the stack trace from there? We added additional info to the exception message (it prints the ABIs supported by the device, e.g. which folders Android is looking in).

Assuming the output above includes armeabi-v7a it might be possible using ReLinker helps: https://docs.objectbox.io/android/app-bundle-and-split-apk#buggy-devices-api-22-or-lower

After reading a [StackOverflow post about diagnosing such issues](https://stackoverflow.com/a/27523384/9187282): is it possible that the APK contains a `armeabi` or `arm` folder as well? Then the libraries in `armeabi-v7a` will not be installed.
