### ISSUE TITLE
Android and Flutter reference objectbox at the same time. Can the same table be universal

### ISSUE THREAD

**Issue by wangzhanxian** [objectbox/objectbox-java#1076]
In the app, I use Android and Flutter at the same time and create the same user table name. Are they universal

**Comment by greenrobot-team** [comment]
Assuming [the JSON model file](https://docs.objectbox.io/getting-started#keep-the-model-file) is the same the database uses the same structure internally. However, one would have to be careful not to open the same database file (Store) multiple times.

However, it should be possible to open additional stores in [read-only mode](https://objectbox.io/docfiles/java/current/io/objectbox/BoxStoreBuilder.html#readOnly()).
