### ISSUE TITLE
Relations broken after upgrading to AGP 7.2.0 when using Hilt plugin

### ISSUE THREAD

**Issue by chakflying** [objectbox/objectbox-java#1077]
**Describe the bug**
After upgrading to AGP 7.2.0 using Android Studio's Upgrade Assistant (which also does the remove `package=""` from manifest thing), seems like relations are not initialized properly. Using them returns 
```
kotlin.UninitializedPropertyAccessException: lateinit property ... has not been initialized
```
Reverting the upgrade and run Gradle sync again and the issue disappears.
Since my setup is quite complicated (using mapstruct generated code to construct objectbox objects), I just wanted to ask if anyone else is experiencing this issue.

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): 3.1.2
 - Reproducibility: always
 - Device: Pixel 4a
 - OS: Android 12

**To Reproduce**
1. Have a working project with relations
2. upgrading to AGP 7.2.0 & Gradle 7.3.3
3. See error

**Expected behavior**
App works the same after upgrade

**Code**
```kotlin
@Entity
data class A(
    @Id var _id: Long = 0,

    ...
) {
    lateinit var my_things: ToMany<B>
    lateinit var ...: ToMany<B>
}

a.my_things.add(thing) // error

```

**Additional context**
The relevant function is called in a coroutine if that matters.

**Comment by SecretKeeper** [comment]
same here after upgrading to AGP 7.2.0

**Comment by greenrobot-team** [comment]
Thanks for reporting! I updated our examples to Android Plugin 7.2.0, and specifically [the Kotlin example app](https://github.com/objectbox/objectbox-examples/tree/main/android-app-kotlin) continues to work fine.

Maybe make sure to rebuild your projects (clean and build). When building there should be a transform task for ObjectBox with a log output like:
```
> Task :app:transformClassesWithObjectBoxAndroidTransformForDebug
[ObjectBox] Transformed 4 entities and copied 37 classes in 107 ms
```

Or you can spot an obvious difference when looking at our Kotlin example?

**Comment by fcat97** [comment]
**How to reproduce:**

> build.gradle(project)
```gradle
buildscript {
    ext {
        agp_version = '7.2.0'
}
```

> Entities
```kotlin
@Entity
class Task {
    /**
     * ObjectBox ID
     */
    @Id var id: Long = 0

    /**
     * permanent ID
     */
    val taskID: String = IdGenerator.getNewId()

    /**
     * ObjectBox Reference to [TaskTag]
     */
    @Backlink(to = "task")
    lateinit var tags: ToMany<TaskTag>
}


@Entity
class TaskTag(
    @Id var id: Long = 0,
    @Unique var name: String = "",
) {

    lateinit var task: ToMany<Task>
}
```

> TaskViewModel
```kotlin
val task = repository.getTask(taskID = taskID) ?: Task()

// here comes the error
val tags = task.tags.joinToString(separator = ", ") { it.name }
```


> Error trace
```kotlin
2022-05-18 11:50:26.911 6604-6647/media.example.error E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: media.uqab.planit, PID: 6604
    kotlin.UninitializedPropertyAccessException: lateinit property tags has not been initialized
        at media.example.error.task.domain.model.Task.getTags(Task.kt:64)
        at media.example.error.task.presentation.viewmodel.TaskEditViewModel$getTask$1.invokeSuspend(TaskEditViewModel.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

---

### How to solve

Downgrade Gradle Plugin `agp_version = '7.1.3'`

**Comment by greenrobot-team** [comment]
@fcat97 Thanks. I tried to reproduce with your example, but it works fine. Is it possible that `repository.getTask(taskID = taskID)` somehow sets `tags` to null?

**Comment by sebokopter** [comment]
Might be related to this issue https://issuetracker.google.com/issues/218289804
@chakflying Can your please try to reproduce it with Android Gradle Plugin 7.3.0-alpha03 or newer (latest is 7.3.0-alpha09)?

**Comment by chakflying** [comment]
Thanks for the investigation. Also can confirm upgrading to Android Studio `Electric Eel | 2022.1.1 Canary 2` and AGP `7.4.0-alpha02` issue still exists.

**Comment by TomislavMladenov** [comment]
Can we have more feasible solution for this, as Android Plugin won't receive such fix anytime soon and removing Hilt is not really a solution.

**Comment by greenrobot-team** [comment]
It appears this was actually a regression in the Android Gradle plugin which should be fixed with release `7.2.2`. See https://issuetracker.google.com/issues/232438924 for details.

**Comment by Joeywp** [comment]
I was having the same issue and downgraded to AGP 7.1.3 because of that. I just upgraded to AGP 7.2.2 which indeed fixes this issue for me.

**Comment by chakflying** [comment]
Can confirm project builds fine on `7.2.2`, I guess we can close this as resolved. Thanks!

**Comment by greenrobot-team** [comment]
Thanks for reporting back! Note that we are still working on supporting the new Transform APIs, however, this is tracked with #1078.
