### ISSUE TITLE
Task :app:objectboxTransformDebugUnitTest fail on Kotlin 1.7

### ISSUE THREAD

**Issue by chakflying** [objectbox/objectbox-java#1085]
**Describe the bug**
Looks like Kotlin 1.7 has some gradle changes which broke the task. The app builds fine otherwise.
Link to relevant (?) Kotlin compatibility guide entry [here](https://kotlinlang.org/docs/compatibility-guide-17.html#changes-in-compile-tasks).

Error shown on build: 
```powershell
java.lang.NoSuchMethodError: 'java.io.File org.jetbrains.kotlin.gradle.tasks.KotlinCompile.getDestinationDir()'
	at io.objectbox.gradle.transform.ObjectBoxAndroidTransform$Registration$addDestinationDirOfKotlinCompile$1.transform(ObjectBoxAndroidTransform.kt:164)

```

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): `3.2.0`
 - Reproducibility: always

**To Reproduce**
1. Upgrade app to Kotlin 1.7
2. Run Unit Test
3. See error

**Dependencies**
```gradle
    debugImplementation "io.objectbox:objectbox-android-objectbrowser:$objectboxVersion"
    releaseImplementation "io.objectbox:objectbox-android:$objectboxVersion"
    kapt("io.objectbox:objectbox-processor:$objectboxVersion")
    implementation("io.objectbox:objectbox-kotlin:$objectboxVersion")
```

**Comment by greenrobot-team** [comment]
Thanks! We already have an internal issue for that.

Until we release an updated Gradle plugin the workaround is to stick with Kotlin 1.6.

**Comment by greenrobot-team** [comment]
Release `3.2.1` which fixes this issue is now available.

**Comment by alonzim** [comment]
3.2.1 fixes the issue for me
