### ISSUE TITLE
Bug in storing and retrieving with nested and equal value relations

### ISSUE THREAD

**Issue by aaaamirabbas** [objectbox/objectbox-java#1111]
Hi, I found a **problem** with storage that I think is not supported in `ObjectBox`.
It seems that there is an issue in creating nested relationships.
Please read my codes and further explanations.

```
@Entity
class Link(
  @Id id: Long = 0
  @Unique(onConflict = ConflictStrategy.REPLACE) var uniq: Long,
) {
    lateinit var userA: ToOne<User>
    lateinit var userB: ToOne<User>
}

@Entity
class Message(
  @Id id: Long = 0
  @Unique(onConflict = ConflictStrategy.REPLACE) var uniq: Long,
) {
    lateinit var link: ToOne<Link>
}

@Entity
class Dialog(
    @Id id: Long = 0
    @Unique(onConflict = ConflictStrategy.REPLACE) var uniq: Long,
) {
    lateinit var link: ToOne<Link>
    lateinit var message: ToOne<Message>
}

```

**If we save these entities in this way:**

```
val newLink = Link(uniq = 10)

val message = Message(uniq = 20).apply {
    link.target = newLink
}

val dialog = Dialog(uniq = 30).apply {
    link.target = newLink
    message.target = message
}

 box.put(dialog)
```

**After saving Dialog and get Dialog from box and print Dialog, the result is this:**

> dialog.link.target == null
> dialog.link.targetId == 1
> dialog.message.target == Link(...)
> dialog.message.targetId == 2

It seems that because the Link ID in both Dialog and Message entities has a value of **0**, ‍‍`then a new entity is identified`. If they are saved with one transaction with **put()**, the value of one of the common entities becomes null.

This is normal because, for example, when a Link is saved in a Dialog, `targetId == 1`.
But when Link is saved in a Message, `targetId = 2`.
So, the final Link with `targetId == 2`.
But in Dialog, Link remains `targetId = 1`.

What is the solution to this issue? 
How can it be that when we have a common and similar entity, as in the example above, the `targetId` of both entities is equal to the correct value?

**Comment by greenrobot-team** [comment]
Thanks for reporting!

There is indeed an issue with `ToOne` put logic: it does put the target again, even if another `ToOne` has already put the target:
https://github.com/objectbox/objectbox-java/blob/0e40cec2f102e62c22fed60d624c5db988dc5e2c/objectbox-java/src/main/java/io/objectbox/relation/ToOne.java#L296-L302

In combination with `ConflictStrategy.REPLACE` this will cause an issue as the ID changes with each put. So only the "last" `ToOne` will have the correct target ID set.

Workarounds until we fix this:
- drop `ConflictStrategy.REPLACE` and add custom logic before put,
- use a separate put for each time a ToOne pointing to the same target is modified.

**Comment by greenrobot-team** [comment]
@aaaamirabbas I failed to reproduce this. Even if an object contained in a `ToOne` was already put, it will not trigger a replace as the ID and the unique property are the same value.

Can you double check your code that it definitely does not modify the `id` or `uniq` property?

**Comment by aaaamirabbas** [comment]
@greenrobot-team 
Hi, given that you have taken the `more Info required` label, do you still need more information?
Can you reproduce the problem?

For further explanations:
If all `ToOne` are pushed with `id = 0`, then put is put by another source, one `ToOne` only has some other than null.

The rest of the `ToOne` of the same type all have `targetId` but they don't have a target and `target == null` (the relationship breaks)

This is caused by **@unique (onConflict = conflictrategy.replace).**

This may seem natural, but with the scenario I explained in the first post, you will find that it is difficult for this scenario.

**Comment by greenrobot-team** [comment]
@aaaamirabbas As I wrote the code snippet you have given does in fact work. The relations are stored properly.

Can you provide a unit test that actually fails?

**Comment by aaaamirabbas** [comment]
Hello @greenrobot-team.
I don't have the requested item right now.
Unfortunately, because of the busy work, it takes some time to do and send you the requested items.
To find the right opportunity to write the right test project, please give me the opportunity.

**Comment by greenrobot-team** [comment]
@aaaamirabbas Sure, take your time.
