### ISSUE TITLE
Issue with Adding New Fields

### ISSUE THREAD

**Issue by ylk2534246654** [objectbox/objectbox-java#1118]
How to set default values for existing databases when adding new fields to entity classes in ObjectBox? For example, for a boolean type, how to set the default value to true, or for a List type, how to set it to not be null but to be new ArrayList<>()?

---

I have an Android class named MyEntity, which initially had only one field, id, annotated with @Id. For an upgrade, I added two more fields, list and enabled, both defined with default values. The former is a List of Strings initialized with an empty ArrayList, while the latter is a boolean set to true. However, when I use list.contains() method, I get a NullPointerException with the message "Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference". Moreover, when I call enabled, its value is false, contrary to the expected true value.

---

I have an Android class with the following fields:

```
public class MyEntity {
    @Id
    private long id;
}
```
For the upgrade, I added the following fields:

```
public class MyEntity {
    @Id
    private long id;
    private List<String> list = new ArrayList<>();
    private boolean enabled = true;
}
```
When I use list.contains(), it throws an error.
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
```
When I call enabled, its value is false.

**Comment by greenrobot-team** [comment]
As for supporting default values for new properties, thumbs up or discuss in #157.
