### ISSUE TITLE
java.lang.UnsatisfiedLinkError:dlopen failed

### ISSUE THREAD

**Issue by glenhsi** [objectbox/objectbox-java#1121]
ROM：XiaoMi/MIUI
CPU：armeabi-v7a
Exception：
java.lang.NoClassDefFoundError:io.objectbox.internal.d
io.objectbox.BoxStore.void <init>(io.objectbox.BoxStoreBuilder)(BoxStore.java:258)
......
java.lang.UnsatisfiedLinkError:dlopen failed: "/data/app/~~PBlGFy0zkHHjiA7aVN5ucg==/com.hpbr.directhires-Wz6G9aEaGY6rwDqsb4xDoA==/lib/arm/libobjectbox-jni.so" .dynamic section header was not found
java.lang.Runtime.loadLibrary0(Runtime.java:1077)
java.lang.Runtime.loadLibrary0(Runtime.java:998)
java.lang.System.loadLibrary(System.java:1656)
io.objectbox.internal.NativeLibraryLoader.void <clinit>()(NativeLibraryLoader.java:92)
io.objectbox.BoxStore.void <init>(io.objectbox.BoxStoreBuilder)(BoxStore.java:258)
io.objectbox.BoxStoreBuilder.io.objectbox.BoxStore build()(BoxStoreBuilder.java:516)
com.hpbr.common.database.objectbox.ObjectBox.void init(android.content.Context,java.lang.String)(ObjectBox.java:33)
com.hpbr.common.application.BaseApplication.com.hpbr.common.database.objectbox.api.IDataBase getDataBase()(BaseApplication.java:350)
com.hpbr.common.application.BaseApplication.com.hpbr.common.database.objectbox.api.IDataBase objectDb()(BaseApplication.java:332)

when the app is started, the exception is occasional occured，I want to know how to fix it?

**Comment by greenrobot-team** [comment]
Thanks for reporting.

Based on a quick Google search: is it possible that your build is using a tool that modifies packaged native libraries? E.g. compresses them? Try to turn this off.

If this won't help we need more info on your build. E.g. how do your Gradle scripts look like?

**Comment by glenhsi** [comment]
yeah, I obfuscate my code, I need keep all objectbox classes? Or how to keep objectbox class,thanks

this is my script:

minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
signingConfig signingConfigs.release
zipAlignEnabled true
shrinkResources true 
buildConfigField "boolean", "APP_DEBUG", "false"
buildConfigField "boolean", "APP_ONLINE", "true"

**Comment by greenrobot-team** [comment]
This is not about Java code, but rather native C code packaged in `/lib/arm/libobjectbox-jni.so` in the App Bundle/APK of your app as the error mentions.

Do you apply any additional obfuscation? Or does the store you distribute through add any?

You can verify the `.so` files are not modified by comparing the version in your APK with the ones included in the AAR file for the ObjectBox version you are using, e.g. https://repo1.maven.org/maven2/io/objectbox/objectbox-android/3.5.1/objectbox-android-3.5.1.aar

**Comment by glenhsi** [comment]
I do not apply additional obfuscation,here is more info:


java.lang.NoClassDefFoundError:io.objectbox.internal.d
io.objectbox.internal.NativeLibraryLoader.void checkUnpackLib(java.lang.String)(NativeLibraryLoader.java:0)
ensureLoaded()(NativeLibraryLoader.java:0)
......
java.lang.UnsatisfiedLinkError:dlopen failed: "/data/app/com.hpbr.directhires-ibf-fTGHmpFcQja5ssTVyg==/lib/arm64/libobjectbox-jni.so" has bad ELF magic
java.lang.Runtime.loadLibrary0(Runtime.java:1016)
java.lang.System.loadLibrary(System.java:1672)
io.objectbox.internal.NativeLibraryLoader.void <clinit>()(NativeLibraryLoader.java:92)
io.objectbox.internal.NativeLibraryLoader.void checkUnpackLib(java.lang.String)(NativeLibraryLoader.java:0)
ensureLoaded()(NativeLibraryLoader.java:0)
io.objectbox.BoxStore.void <init>(io.objectbox.BoxStoreBuilder)(BoxStore.java:258)
io.objectbox.BoxStoreBuilder.io.objectbox.BoxStore build()(BoxStoreBuilder.java:516)
com.hpbr.common.database.objectbox.ObjectBox.void init(android.content.Context,java.lang.String)(ObjectBox.java:33)




the private method checkUnpackLib is called,but device is HuaWei/EMOTION(Android9,arm64-v8a),why? objectbox version is 3.2.0

**Comment by glenhsi** [comment]
I do not apply additional obfuscation,here is more info:


java.lang.NoClassDefFoundError:io.objectbox.internal.d
io.objectbox.internal.NativeLibraryLoader.void checkUnpackLib(java.lang.String)(NativeLibraryLoader.java:0)
ensureLoaded()(NativeLibraryLoader.java:0)
......
java.lang.UnsatisfiedLinkError:dlopen failed: "/data/app/com.hpbr.directhires-ibf-fTGHmpFcQja5ssTVyg==/lib/arm64/libobjectbox-jni.so" has bad ELF magic
java.lang.Runtime.loadLibrary0(Runtime.java:1016)
java.lang.System.loadLibrary(System.java:1672)
io.objectbox.internal.NativeLibraryLoader.void <clinit>()(NativeLibraryLoader.java:92)
io.objectbox.internal.NativeLibraryLoader.void checkUnpackLib(java.lang.String)(NativeLibraryLoader.java:0)
ensureLoaded()(NativeLibraryLoader.java:0)
io.objectbox.BoxStore.void <init>(io.objectbox.BoxStoreBuilder)(BoxStore.java:258)
io.objectbox.BoxStoreBuilder.io.objectbox.BoxStore build()(BoxStoreBuilder.java:516)
com.hpbr.common.database.objectbox.ObjectBox.void init(android.content.Context,java.lang.String)(ObjectBox.java:33)



the private method checkUnpackLib is called,but device is HuaWei/EMOTION(Android9,arm64-v8a),why? objectbox version is 3.2.0

**Comment by greenrobot-team** [comment]
Similar error (`dlopen failed: "[...]/lib/arm64/libobjectbox-jni.so" has bad ELF magic`) which points to the APK having a modified, invalid `.so` file.

Is it possible that this is from users who sideload or modify your APK? E.g. on what percentage of devices does this occur?
