### ISSUE TITLE
[Kotlin] Can't set enum param of an entity

### ISSUE THREAD

**Issue by DmytroTols** [objectbox/objectbox-java#1127]
I'm using ObjectBox 3.5.1 and what I witnessed is that I for some reason I can't set enum value of my entity when I put it in 
lets say I have 
@Entity
data class Entity(
    @Id
    var number: Long = 0,
    var enums: EnumType = EnumType.defaulf
)
so after inserting entity:
val entity = Entity()
entyty.enums = EnumType.something
Database.boxBase.put(entity)

I find this entity from database inside another composable and I get EnumType.defaulf

**Comment by neroux** [comment]
Doesn't seem as if enums were supported in the first place

https://docs.objectbox.io/advanced/custom-types#convert-annotation-and-property-converter

**Comment by DmytroTols** [comment]
They are,there is even information "How to convert Enums correctly"
