### ISSUE TITLE
Admin should show 50/page but only shows 10 but pages by 50

### ISSUE THREAD

**Issue by herriojr** [objectbox/objectbox-java#1135]
**Describe the bug**
When using the objectbox browser, it does 50 per page but only shows 10 of said page. I cannot get it to show all 50 without jumping through hoops.

**Basic info (please complete the following information):**
 - ObjectBox version 3.6.0
 - Reproducibility: always
 - Device: emulator
 - OS: API 33

**To Reproduce**
1. Put > 50 objects into a database
2. Open the objectbox admin
3. See it says it is display a page of 1-50 but only 10 show.

**Expected behavior**
If it's showing 50 per page and there's more than 50 objects, it should show all 50 in a page. Next page just skips to the next 50.

**Code**
None

**Logs, stack traces**
None

**Additional context**
None

**Comment by greenrobot-team** [comment]
Thanks for reporting! I could confirm this using our Kotlin example.

**Comment by greenrobot-team** [comment]
This was fixed internally and will ship with the next release.

**Comment by ajans** [comment]
I am also having this issue, but without additional pages. I should see 37 entries, but only see the firs 10.
I can see the data I am looking for when filtering for IDs, but this is impeding my efforts to check if the data is as it should be.

![grafik](https://github.com/objectbox/objectbox-java/assets/3482744/a592d1d9-5d06-4798-b64f-65e962f6560c)

When will the version with the fix be released?

**Comment by ajans** [comment]
I tested this with objectbox-version 3.5.1, this issue does not present itself with this version, so I will stay with it for now.
So clearly, some change between 3.5.1 and 3.6.0 broke the Admin interface.

**Comment by greenrobot-team** [comment]
Back from holiday, aiming to release this in the next weeks.

**Comment by greenrobot-team** [comment]
We have [released version `3.7.0`](https://github.com/objectbox/objectbox-java/releases/tag/V3.7.0) which fixes this issue.
