### ISSUE TITLE
A document typo

### ISSUE THREAD

**Issue by how8570** [objectbox/objectbox-java#1140]
The kotlin simple code has a typo, selected `{` in image should be `}`

![image](https://github.com/objectbox/objectbox-java/assets/16633155/c16fb59a-2fa6-4827-b646-4c9e22320dca)

ref: https://docs.objectbox.io/queries#add-query-conditions-for-related-entities-links

**Comment by greenrobot-team** [comment]
Thanks for reporting! I also fixed the formatting.
