### ISSUE TITLE
io.objectbox.exception.DbSchemaException

### ISSUE THREAD

**Issue by WangkeqiangS** [objectbox/objectbox-java#1149]
I accidentally deleted the objectbox metamodel file default.json and cannot find it. What should I do about the published version?

**Comment by WangkeqiangS** [comment]
I re-generated the metamodel file default.json, overwriting the installation caused the program to throw an exception, how to solve it?

**Comment by greenrobot-team** [comment]
Can you restore it using your version control system? (You should really track this file e.g. in git).

Can you extract it from your built application package?

You can also obtain the IDs from the `MyObjectBox` class if you can access the application package.

https://docs.objectbox.io/getting-started#keep-the-model-file

**Comment by WangkeqiangS** [comment]
Unfortunately, we can't get it back. Our objectbox is too dependent on metamodel files, which is not conducive to multi-branch development and multi-party collaborative development

**Comment by WangkeqiangS** [comment]
Ask a question, if there is a name field in the value, I delete it and then want to restore, before the name value can be restored?

**Comment by greenrobot-team** [comment]
In the database entities and properties are addressed by their UID. So as long as you restore the UID you should get access to the previously stored data.

Maybe have a look at https://docs.objectbox.io/advanced/meta-model-ids-and-uids for a deeper explanation.

**Comment by WangkeqiangS** [comment]
Thank you very much for your recovery, have a good life, goodbye
