### ISSUE TITLE
Query result reversed order

### ISSUE THREAD

**Issue by enriquebautista** [objectbox/objectbox-java#1158]
### Build info

- ObjectBox version: 3.6.0
- OS: Android 12

### Expected behavior

_Get the list of items sorted in such a way that the first one inserted is the first one in the list._

### CODE

This creates a query that fetches all the entities in the order of insertion. 

```kotlin
val myQuery = entityBox.query()
  .build()
```
So,  if I insert data in the following order:
item 1,
item 2,
item 3

The items are ordered like this in the recyclerview
item 3,
item 2,
item 1

The question is how can I reverse order the results of the query without taking as reference any item of the table, that is to say, without using the .order(property, order).

Like this :
Item 1,
Item 2,
Item 3 

The only way I have been able to do this is by sorting the query results outside the ObjectBox query

```kotlin
val myQuery = entityBox.query()
  .build()

val result = myQuery.find()
val orderedList = result.reversed() // .reversed() is from Kotlin collections
```

**Comment by greenrobot-team** [comment]
If I remember correctly, when not adding an order configuration objects are sorted by ID. So to reverse you might try something like:
```kotlin
box.query().orderDesc(TestEntity_.id).build()
```
Other than that you would have to create your own property to order by (or as you said re-order the results after ObjectBox returns them).

**Comment by enriquebautista** [comment]
> If I remember correctly, when not adding an order configuration objects are sorted by ID. So to reverse you might try something like:
> 
> ```kotlin
> box.query().orderDesc(TestEntity_.id).build()
> ```
> 
> Other than that you would have to create your own property to order by (or as you said re-order the results after ObjectBox returns them).

That works! Thanks
