### ISSUE TITLE
Attempt to invoke virtual method 'boolean io.objectbox.relation.ToMany.add(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by georgegatt** [objectbox/objectbox-java#1161]
I updated my Android Studio version from 4.0.2 (Sep. 9, 2020) to Android Studio Giraffe 2022.3.1 Patch 4 (Nov. 13, 2023),
my Gradle version from 6.1.1 to 8.4, my Android Gradle plugin version from 4.0.2 to 8.1.4, and my Objectbox gradle plugin
and Objectbox java version from 2.9.1 to 3.7.1 .

I am using a Huawei 30 Pro phone with Android OS 10 and my Android application is set to targetSdkVersion 33 and buildToolsVersion 33.0.2.  

I have the following classes:
```java
@Entity
public class A {
 
       @Id public long id;
       
       public ToMany<A> companions;

       public A() {
       } 


      public A(B b) {
         List<B> companions = b.getCompanions();
         if (companions != null) {
             for (int i = 0; i < companions.size(); i++) {
                   addCompanion(new A(companions.get(i)));      // here, companions.get(i).getCompanions() is null 
             }
         }
       }

     
     public void addCompanion(A companion) {
          this.companions.add(companion);
     } 

}


// I have ommitted code in this class that initializes the companions property
public class B {

    private List<B> companions;


   public List<B> getCompanions() {
             return this.companions;
  }

}
```

When I was on version 2.9.1 and using the initial Android studio and Gradle versions I mentioned above, the method:
`addCompanion(A companion)`
called from the 2nd constructor of class A, was running fine. After upgrading to version 3.7.1 and the latest Android studio
and Gradle versions, this method invocation is causing every time the app to crash with:

> Attempt to invoke virtual method 'boolean io.objectbox.relation.ToMany.add(java.lang.Object)' on a null object reference

Why is this happening after the upgrade to the latest Objectbox version, and how can I initialize the ToMany<A> companions
property of class A in order to avoid the crash ?

**Comment by greenrobot-team** [comment]
[The ObjectBox Gradle plugin typically transforms the entity classes](https://docs.objectbox.io/relations#initialization-magic) to add initializers for the ToMany and ToOne properties to the class constructors. Maybe this can be fixed as simple as rebuilding the project in Android Studio.

If not, check that the ObjectBox Gradle plugin is still [correctly applied](https://docs.objectbox.io/getting-started).

If all of that won't work, the fields can be initialized manually. See the first link.

**Comment by greenrobot-team** [comment]
I don't see how this could be related to the model JSON file, assuming it has not changed? It's only responsible for managing IDs. But I can't really say more without seeing the setup of the project. My best guess is this is related to upgrading the Android Plugin. Did you maybe leave on the new R8 full mode? Did you adjust your R8 rules?
