### ISSUE TITLE
io.objectbox.exception.DbException error code 30

### ISSUE THREAD

**Issue by luhuanxml** [objectbox/objectbox-java#1162]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues)

### Build info

java.lang.RuntimeException:Unable to create application com.htc.ali.access.app.TheApp: io.objectbox.exception.DbException: Could not open database environment; please check options and file system (30: Read-only file system) (error code 30)

- ObjectBox version: [ 3.7.1]
- OS: [ Android 7.1.1 ]
- Device/ABI/architecture: [ arm64-v8a ]

### Steps to reproduce

_TODO Tell us exactly how to reproduce the problem._

1. ...
2. ...
3. ...

### Expected behavior

_TODO Tell us what you expect to happen._

### Actual behavior

_TODO Tell us what actually happens._

### Code

_TODO Add a code example to help us reproduce your problem._

<details><summary>Code</summary>

```java
[Paste your code here]
```

</details>

### Logs, stack traces

_TODO Add relevant logs, a stack trace or crash report._

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by luhuanxml** [comment]
this is my code .No custom storage directory.
object ObjectBox {

    lateinit var boxStore: BoxStore
        private set

    fun init(context: Context) {
        boxStore = MyObjectBox.builder().androidContext(context).build()
        LogTool.print(
            "ObjectBox",
            "ObjectBox: version=${BoxStore.getVersion()}  versionNative=${BoxStore.getVersionNative()}"
        )
    }

}

Only one device has this issue.

**Comment by greenrobot-team** [comment]
> Only one device has this issue.

Looks like this is an issue with that device then? Maybe it has some customizations so the app files directory is on a read-only volume?
