### ISSUE TITLE
In a module based project the split package io.objectbox.converter prevents building

### ISSUE THREAD

**Issue by Hackmancoltaire** [objectbox/objectbox-java#1163]
When using the Gradle plugin in a multi-module application the split package that exists between io.objectbox.java and io.objectbox.java-api causes an issue during building.

Steps to reproduce:
1. Create a new java project with a root and app level build.gradle. Use the gradle plugin as described.
2. Create a `module-info.java` file for the app module and add `requires io.objectbox.java;`
3. Add some other dependencies at the app level.

Upon build you should get an error like: 
`error: the unnamed module reads package io.objectbox.converter from both objectbox.java and objectbox.java.api`

I'd recommend combining java and java-api or at least moving the converter subfolder into one or the other package.

**Comment by greenrobot-team** [comment]
Thanks for reporting! See #840 for a discussion on supporting the Java module system. Also added a note about the api and regular JAR overlapping.
