### ISSUE TITLE
Adding an index on an Integer field with many repeating values results in very slow "find()" queries

### ISSUE THREAD

**Issue by sspanak** [objectbox/objectbox-java#1164]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues). There is nothing similar.

### Build info

- ObjectBox version: 3.7.1
- OS: Android 11, Android 6.0
- Device/ABI/architecture: Qin F21 Pro/Android 11; No-model Vodafone/Android 6.0 (this is probably irrelevant)

### Steps to reproduce
See the Code section below.

### Expected behavior

The query completes within a reasonable amount of time and adding an index on `langId` results in similar or better time.

### Actual behavior

If there is no index on `langId`, the query is very fast (average: 1ms-30ms, up to 55ms). But adding an index causes it to become many times slower. It could take 30-50ms, peaking to 300ms, depending on the amount of matches. 

This is counterintuitive. To my understanding an index must not make queries slower. And if it happens with some specific data shape, this must be noted in the documentation.

### Code
The build.gradle file is [here](https://github.com/sspanak/tt9/blob/objectbox/build.gradle). I don't think it has anything to do with the problem, but still check it out, if you need to. If the branch is gone by the time you read this, just find it in `master`.

**Create an Entity:**
```java
@Entity
public class Word {
	@Id public long id;
	@Index public int langId;
	public int length;
	@Index public String sequence; // A numeric string, for example: "4665", "923851"
	@Index public byte sequenceShort; // The first two digits of "sequence". I am using this to speed up searching
	@Unique(onConflict = ConflictStrategy.REPLACE) public String uniqueId;
	// ...
	// My entire entity has more properties, but these are enough to reproduce the problem.

}
```
You can find the entire file [here](https://github.com/sspanak/tt9/blob/objectbox/src/io/github/sspanak/tt9/db/objectbox/Word.java).

**Add data in this format:**
```json
[
  {"langId": 656, "sequence": "4665", "sequenceShort": 46, "uniqueId": "656_unique_string"},
  {"langId": 656, "sequence": "592629", "sequenceShort": 59, "uniqueId": "656_another_string"},
  {"langId": 86688, "sequence": "4665", "sequenceShort": 46, "uniqueId": "86688_unique_string"},
  {"langId": 86688, "sequence": "76158", "sequenceShort": 76, "uniqueId": "86688_third_string"},
  // ...
]
```
  - I have two different `langIds`, but the problem is reproducible even with one. The numbers are not consecutive.
  - `sequence` can appear multiple times per `langId`. It contains only digits: 0-9. 
  - `sequenceShort` is the first two digits of `sequence`.
  - `length` is the length of the `sequence` string.
  - `uniqueId` consists of `langId` concatenated with a unique string per the given `langId`.
  - I have about 131k entries for the first `landId` and about 235k for the second one.

I can provide sample data in .csv or .json format if necessary.

**Now query this way:**
```java
Query<Word> longWordQuery = boxStore.boxFor(Word.class)
.query()
	.equal(Word_.langId, 0)
	.startsWith(Word_.sequence, "", QueryBuilder.StringOrder.CASE_SENSITIVE).parameterAlias("seq_start")
	.lessOrEqual(Word_.sequence, "", QueryBuilder.StringOrder.CASE_SENSITIVE).parameterAlias("seq_end")
	.equal(Word_.sequenceShort, 0)
.order(Word_.length)
.orderDesc(Word_.frequency)
.build();

// ... some input validation follows, then we set the parameters:

longWordQuery.setParameter(Word_.sequenceShort, 46);
longWordQuery.setParameter("seq_start", "466");
longWordQuery.setParameter("seq_end", "466" + "99");
longWordQuery.setParameter(Word_.langId, 656);
longWordQuery.find(0, 20)
```

The file where this code lives is [here](https://github.com/sspanak/tt9/blob/objectbox/src/io/github/sspanak/tt9/db/objectbox/WordStore.java). The method in question is `getMany()`.

Again, if the branch is gone by the time you read this, you will find the code in `master`.

**Comment by greenrobot-team** [comment]
Thanks for reporting and including all relevant details!

However, this behavior is kind of expected from an index. An index is only beneficial if most objects have unique values, so that for a query only a small amount of objects matches. Only then is looking up objects via the index faster than scanning all objects (= no index).

If most objects have the same value, the performance actually decreases compared to having no index on the property, as you discovered.

This is also independent of the property type.
