### ISSUE TITLE
Error after upgrade to Android Gradle Plugin 8.2.0 with org.gradle.configuration-cache=true

### ISSUE THREAD

**Issue by Jimex** [objectbox/objectbox-java#1165]
### Is there an existing issue?

N.A

### Build info

ObjectBox version: 3.7.1
Android Gradle Plugin 8.2.0

### Steps to reproduce

_TODO Tell us exactly how to reproduce the problem._

1. Upgrade Android Gradle Plugin to 8.2.0
2. Clean project
3. Run the app

### Expected behavior

App build and run successfully

### Actual behavior

Failed with following message:

1 problem was found storing the configuration cache.
- Task `:app:objectboxPrepareBuild` of type `io.objectbox.gradle.PrepareTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.

**Comment by greenrobot-team** [comment]
Thanks for reporting. The ObjectBox Gradle plugin currently does not support the configuration cache, see #948 for a discussion.
