### ISSUE TITLE
Support Kotlin inline value classes(UInt, especially)

### ISSUE THREAD

**Issue by Mina-1316** [objectbox/objectbox-java#1170]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues) by keyword: Kotlin Value class, inline, etc
- [x] I have searched [StackOverflow](https://stackoverflow.com/search?q=%5Bobjectbox%5D+Value+class)

### Use case

In kotlin, there are inline Value class which wraps primitive type for runtime optimization.

If I try to use value class inside entity, It produces compile issue: `error: cannot find symbol`, typed with value class.

I don't think this is a bug, but unexpected behavior from unimplemented factor(as i assume) so I reported as feature request.

### Proposed solution

Recognize inline value class's primitive property, to reflect Database type on compile time since value class is disassembled and running as primitive in runtime.

It can be rejected if this feature impacts Java's functionality.

### Additional context

I tried converter for `UInt` -> `Int` and It creates an error because real type of `UInt` is `Int`, which will run as `Int` -> `Int`.
below is occurred error:
1. cannot find symbol method,
2. bad operand types for binary operator '!=' - first type: int, second type: <null> `int __id15 = testVal != null ? __ID_testVal : 0;`
3. cannot find symbol method convertToDatabaseValue(int)

**Comment by greenrobot-team** [comment]
@Mina-1316 Try to use `@JvmName`, e.g.

```kotlin
@Entity
data class UnsignedK(
    @Id var id: Long = 0,
    @get:JvmName("getUnsignedInt")
    var unsignedInt: UInt = 0u,
)
```

[Looked into this some more](https://youtrack.jetbrains.com/issue/KT-46144/Unsigned-numbers-dont-have-a-good-interop-story) and it appears the name mangling is done on purpose. Developers have to explicitly opt-in to expose to Java using `@JvmName`.

**Comment by Mina-1316** [comment]
I'll try when I've back on work tomorrow, thanks for fast response!

**Comment by Mina-1316** [comment]
@greenrobot-team I tested and It works well on Kotlin stdlib/custom value classes!

As I tested, no need to set setter for value class, only getter.

below Is the documentation from Kotlin that I've missed:
https://kotlinlang.org/docs/inline-classes.html#calling-from-java-code

**Comment by greenrobot-team** [comment]
Great, thanks for the link! Will use that in our docs.

**Comment by greenrobot-team** [comment]
Added example at https://docs.objectbox.io/advanced/custom-types.
