### ISSUE TITLE
Adding an entity with a ToMany relationship to another ToMany relationship doesn't properly store the ToMany relationship.

### ISSUE THREAD

**Issue by paytontech** [objectbox/objectbox-java#1171]
### Is there an existing issue?

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues)

### Build info

- ObjectBox version: 3.7.1
- OS: Android 12
- Device/ABI/architecture: Galaxy S10+ | arm64

### Steps to reproduce

1. Define a "top-level" entity with a ToMany relationship to a "second-level" entity. The "second-level" entity has another ToMany relationship with a "third-level" entity.
2. Add a "second-level" entity with >1 "third-level" entities to the top-level entity.
3. Store the data in the DB

### Expected behavior
All "third-level" entities are stored properly
### Actual behavior
Only one "third-level" entity from the list is stored in the DB.

### Code

<details><summary>Code</summary>

```java
@Entity
data class TopLevel(
    @Id
    var id: Long = 0,
    var dateAdded: Date
) {
    lateinit var seconds: ToMany<SecondLevel>
}
@Entity
data class SecondLevel(
    @Id var id: Long = 0,  // Change the type to String
    var date: Date
) {
    lateinit var thirds: ToMany<ThirdLevel>
}
@Entity
data class ThirdLevel(
    @Id var id: Long = 0,
    var type: String = "",
)
var topLevel = TopLevel(dateAdded = Date())
var secondLevel = SecondLevel(date = Date())
var thirdLevel1 = ThirdLevel(type = "Test")
var thirdLevel2 = ThirdLevel(type = "Test2")
secondLevel.thirds.add(thirdLevel1)
secondLevel.thirds.add(thirdLevel2)
topLevel.seconds.add(secondLevel)
box.put(topLevel)

var fromDB = box.get(1)
print(fromDB.seconds.last().thirds.count()) // outputs 1. expected: 2
```

**Comment by greenrobot-team** [comment]
Thanks for reporting. However, the above prints 2 for me, so as expected.

Maybe at some point the `ThirdLevel` objects were equal? E.g.
```kotlin
var thirdLevel1 = ThirdLevel(type = "Test")
var thirdLevel2 = ThirdLevel(type = "Test") // considered equal in terms of a Kotlin data class
```

Note that in this case only one gets added.

**Comment by paytontech** [comment]
> Thanks for reporting. However, the above prints 2 for me, so as expected.
> 
> 
> 
> Maybe at some point the `ThirdLevel` objects were equal? E.g.
> 
> ```kotlin
> 
> var thirdLevel1 = ThirdLevel(type = "Test")
> 
> var thirdLevel2 = ThirdLevel(type = "Test") // considered equal in terms of a Kotlin data class
> 
> ```
> 
> 
> 
> Note that in this case only one gets added.

Interesting. Thanks for the response, i'll take a close look at my code!
