### ISSUE TITLE
cannot read first N elements of a box without a filter with objectbox 4.0.0

### ISSUE THREAD

**Issue by andrew-ld** [objectbox/objectbox-java#1180]
with objectbox <= 3.8.0 i can use box.query().build().find(0, N) to read the first N elements of a box without a filter.

with objectbox 4.0.0 box.query() without a parameter is deprecated, what is the substitute?

**Comment by greenrobot-team** [comment]
The `query()` method was deprecated by mistake. I actually meant to deprecate the condition methods on `QueryBuilder`, sorry about that!

**Comment by greenrobot-team** [comment]
This was fixed internally and will be part of the next release.
