### ISSUE TITLE
A document typo in ObjectBox Queries section

### ISSUE THREAD

**Issue by ganwumeng** [objectbox/objectbox-java#1182]
The dart code lack a `)` before `.order`.

[https://docs.objectbox.io/queries#order-results](https://docs.objectbox.io/queries#order-results)

<img width="832" alt="image" src="https://github.com/objectbox/objectbox-java/assets/38616251/172ad89f-8a1d-4ea2-a65f-04720cc71f7e">

**Comment by greenrobot-team** [comment]
Thanks for reporting! Fixed.
