### ISSUE TITLE
panic: runtime error: slice bounds out of range [1071:136]

### ISSUE THREAD

**Issue by varssni-blueocean** [objectbox/objectbox-java#1187]
### Is there an existing issue?

- [ ] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues)

### Build info

- ObjectBox version: [e.g. 3.7.0]
- OS: [e.g. Android 14 | Ubuntu 22.04 | Windows 11 ]
- Device/ABI/architecture: [e.g. Galaxy S23 | arm64-v8a | x86-64 ]

### Steps to reproduce

_TODO Tell us exactly how to reproduce the problem._

1. ...
2. ...
3. ...

### Expected behavior

_TODO Tell us what you expect to happen._

### Actual behavior

_TODO Tell us what actually happens._

### Code

_TODO Add a code example to help us reproduce your problem._

<details><summary>Code</summary>

```java
[Paste your code here]
```

</details>

### Logs, stack traces

_TODO Add relevant logs, a stack trace or crash report._

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by greenrobot-team** [comment]
Issue template not filled out. Looks like spam.
