### ISSUE TITLE
Dagger2 and objectbox are used simultaneously, indicating that DaggerActivity cannot be found

### ISSUE THREAD

**Issue by mclmdream** [objectbox/objectbox-java#1188]
buildscript {
    dependencies {
        classpath "io.objectbox:objectbox-gradle-plugin:4.0.2"
    }
}

plugins {
//    id 'com.android.application' version '7.1.2' apply false
    id 'com.android.application' version '8.0.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.0' apply false
}

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'io.objectbox'
}

![image](https://github.com/user-attachments/assets/dfbbab92-1105-43c3-9737-c3818ea7e430)

**Comment by greenrobot-team** [comment]
Thanks for reporting. Can you please share a more complete build script that also shows how Dagger is used? Is there any relevant log output when building the app? Otherwise, this is rather hard for me to reproduce.

Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

**Comment by mclmdream** [comment]
'com.google.dagger:dagger:2.51.1',
  'com.google.dagger:dagger-compiler:2.51.1',


@ActivityScope
@Component(dependencies = DnetComponent.class,
        modules = {ActivityModule.class,
                DBaseActivityModule.class,

        })
public interface ActivityComponent {
    Activity getBaseActivity();
}



@Scope
@Retention(RUNTIME)
public @interface ActivityScope {
}


@Module
public class ActivityModule {
    private Activity mActivity;

    public ActivityModule(Activity mActivity) {
        this.mActivity = mActivity;
    }

    @Provides
    @ActivityScope
    public BaseActivity provideActivity() {
        return mActivity;
    }

}

 DaggerActivityComponent.builder()， Unable to find DaggerActivityComponent，thanks
