### ISSUE TITLE
Compiler error with kotlin value class

### ISSUE THREAD

**Issue by Delsart** [objectbox/objectbox-java#1189]
### Is there an existing issue?

there is [related issues](https://github.com/objectbox/objectbox-java/issues/706)

### Build info

- ObjectBox version: 4.0.2
- OS: Android 14

### Steps to reproduce

use value class as property
```
ask :app:compileDebugJavaWithJavac FAILED
E:\Project\app\build\generated\source\kapt\debug\work\delsart\flowte\data\element\draw\DrawLayerCursor.java:61: error: cannot find symbol
        long offset = entity.getOffset();
                            ^
  symbol:   method getOffset()
  location: variable entity of type DrawLayer
E:\Project\app\build\generated\source\kapt\debug\work\delsart\flowte\data\element\draw\DrawLayerCursor.java:62: error: bad operand types for binary operator '!='
        int __id3 = offset != null ? __ID_offset : 0;
                           ^
  first type:  long
  second type: <null>
E:\Project\app\build\generated\source\kapt\debug\work\delsart\flowte\data\element\draw\DrawLayerCursor.java:67: error: cannot find symbol
                __id3, __id3 != 0 ? offsetConverter.convertToDatabaseValue(offset) : 0, __ID_type, entity.getType(),
                                                   ^
  symbol:   method convertToDatabaseValue(long)
  location: variable offsetConverter of type OffsetConverter
3 errors
```

### Expected behavior

support value class, for a lot of compose unit class use value class.

### Actual behavior

do not support value class now.

### Code

<details><summary>Code</summary>
Entity:

``` kotlin
@Entity
@Immutable
class DrawLayer(
...

    // maybe we dont need convert since it is a value class
    @Convert(converter = OffsetConvertor::class, dbType = Long::class)
    val offset: Offset = Offset.Zero

...
) 
```

Offset class:

``` kotlin
@Immutable
@kotlin.jvm.JvmInline
value class Offset(val packedValue: Long) 
```

Converter:

``` kotlin
class OffsetConvertor : PropertyConverter<Offset, Long> {
    override fun convertToEntityProperty(databaseValue: Long?): Offset {
        return databaseValue?.let { Offset(it) } ?: Offset.Zero
    }

    override fun convertToDatabaseValue(entityProperty: Offset?): Long {
        return entityProperty?.packedValue ?: 0L
    }
}
```

**Comment by greenrobot-team** [comment]
Thanks for reporting!

A converter does not make sense, as the `Offset` class uses `@JvmInline`. So to Java `Offset` is just a `long`. Hence the compiler error above.

Anyhow, using just the value class does not work because the compiler still complains that the `getOffset()` method is missing.

This can be fixed as suggested in #1170 by using the `@get:JvmName("getOffset")` annotation.

I should add an additional example for a generic value class to https://docs.objectbox.io/advanced/custom-types.

**Comment by Delsart** [comment]
> Thanks for reporting!
> 
> A converter does not make sense, as the `Offset` class uses `@JvmInline`. So to Java `Offset` is just a `long`. Hence the compiler error above.
> 
> Anyhow, using just the value class does not work because the compiler still complains that the `getOffset()` method is missing.
> 
> [This can be fixed](https://kotlinlang.org/docs/inline-classes.html#calling-from-java-code) as suggested in #1170 by using the `@get:JvmName("getOffset")` annotation.
> 
> I should add an additional example for a generic value class to https://docs.objectbox.io/advanced/custom-types.

Thank you. By the way, Kotlin now supports multiple platforms, not just the JVM. Is there any plan to support Kotlin independently?

**Comment by greenrobot-team** [comment]
@Delsart For Kotlin Multiplatform support See #601!
