### ISSUE TITLE
Fail compilation if @Backlink is missing the "to" parameter

### ISSUE THREAD

**Issue by kwadkore** [objectbox/objectbox-java#1193]
### Is there an existing issue? 

Yes, as of version 4.0.2.

- [x] I have searched [existing issues](https://github.com/objectbox/objectbox-java/issues)

### Use case

According to the documentation, the @Backlink annotation requires the "to" parameter be set in order to work. Right now, it's possible to compile and run without setting the "to" parameter, making it easy to unintentionally overlook the issue and have a latent bug. 

### Proposed solution

Can you fail compilation if the Backlink annotation isn't set properly?

### Alternatives

_TODO Describe any alternative solutions or features you've considered._

**Comment by greenrobot-team** [comment]
Thanks for reporting! I'm not sure why the docs say "required", it should be "recommended (I updated them).

In any case, the ObjectBox annotation processor does already display an error when there are two or more relations that `@Backlink` could apply to. Or put differently: while it is recommended to specify the linked relation using "to", it is not required. If there is only one matching relation, ObjectBox will pick it automatically.
