### ISSUE TITLE
build.gradle.kts could not download the plugin

### ISSUE THREAD

**Issue by wgc0303** [objectbox/objectbox-java#1195]
I use Kotlin DSL(build.gradle.kts) in Android studio 2024.1.1
Creating a project, unable to download plugins using alias

This is what's in my libs.version.toml file:
[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
objectbox = "4.0.3"

[plugins]
android-application = { id = "com.android. application", version. ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin. android", version. ref = "kotlin" }
objectbox = { id = "io. objectbox", version. ref = "objectbox" }

This is what is in my build.gradle.kts file:
plugins {
alias(libs.plugins.android.application) apply false
alias(libs.plugins.jetbrains.kotlin.android) apply false
alias(libs.plugins.objectbox) apply false
}

This is what's in my gradle-wrapper.properties file:
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

However, I could not find the pom file during the download process. I went to the maven warehouse to find the relevant file, but I did not find the relevant path. So how do we fix this?
<img width="1262" alt="2024-11-01_220329" src="https://github.com/user-attachments/assets/ed2b3349-1ace-408e-b97f-cb8145bd51d8">
<img width="946" alt="2024-11-01_220542" src="https://github.com/user-attachments/assets/c031a3d0-ea30-469c-8045-261b059eb188">

**Comment by greenrobot-team** [comment]
It looks like you have already figured it out.

For others: The ObjectBox Gradle plugin does not ship a Gradle plugin marker artifact. To work around this, add a [plugin resolution rule](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_resolution_rules) that maps the dependency to a name of your choosing: see the [related GitHub issue](https://github.com/objectbox/objectbox-java/issues/960#issuecomment-1711252548) for details.
