### ISSUE TITLE
Increase a lot of memory while subscribe flow

### ISSUE THREAD

**Issue by udyr-woo** [objectbox/objectbox-java#1196]
### Build info

- ObjectBox version: 4.0.3
- OS: Anroid 13
- Device/ABI/architecture: odroid-m2 | arm64-v8a

### Steps to reproduce

OOM generated by calling flow logic while using in-memory mode(but OOM(from java heap) occurs relatively slowly even in file-based mode)
And I think it's from a snapshot

### Expected behavior

Doesn't increase memory while subscribe flow

### Actual behavior

Increase memory a lot

### Code

<details><summary>Code</summary>

```kotlin
DAO
@OptIn(ExperimentalCoroutinesApi::class)
    override fun getInstancesByRepeaterStationIdAndCcuId(
        repeaterStationId: Short,
        ccuId: Short
    ): Flow<List<RepeaterEntity>> {
        val query =
            repeaterBox.query(RepeaterEntity_.partialCompositeKey.equal("$repeaterStationId-$ccuId"))
                .build()
         return query.subscribe().toFlow().distinctUntilChanged().onCompletion { query.close() }
    }
    
Entity
data class RepeaterEntity(
    @Id
    var objectBoxId: Long = 0,
    @Unique
    var fullCompositeKey: String = "",
    @Index
    var partialCompositeKey: String = "",
    var repeaterStationId: Short = 0,
    var ccuId: Short = 0,
    var id: Short = 0,
    @Index
    @Convert(converter = DeviceConnectStatusConverter::class, dbType = String::class)
    var connect: DeviceConnectStatus = DeviceConnectStatus.CONNECT,
    @Convert(converter = DeviceConnectStatusConverter::class, dbType = String::class)
    var previousConnect: DeviceConnectStatus = DeviceConnectStatus.CONNECT,
    var version: Int = 0,
    var parentVersion: Long = 0
) 

data class RepeaterInputEntity(
    @Id
    var objectBoxId: Long = 0,
    @Unique
    var fullCompositeKey: String = "",
    var repeaterStationId: Short = 0,
    var ccuId: Short = 0,
    var parentRepeaterId: Short = 0,
    var id: Short = 0,
    @Convert(converter = ClassificationConverter::class, dbType = String::class)
    var classification: Classification = Classification.M1,
    var signal: Boolean = false,
    var previousSignal: Boolean = false,
    var wireBreak: Boolean = false,
    var outputList: MutableList<String> = mutableListOf(),
    var testMode: Boolean = false,
    ) 

data class RepeaterOutputEntity(
    @Id
    var objectBoxId: Long = 0,
    @Unique
    var fullCompositeKey: String = "",
    var repeaterStationId: Short = 0,
    var ccuId: Short = 0,
    var parentRepeaterId: Short = 0,
    var id: Short = 0,
    var signal: Boolean = false,
    var request: Boolean = false,
    var previousRequest: Boolean = false,
    var testMode: Boolean = false,
)

The total number of instances of the three entities combined is 432,000

```

</details>

### Logs, stack traces
<img width="1098" alt="objectbox" src="https://github.com/user-attachments/assets/dccc9ba1-314b-4ce5-9903-f43fe07dcdf4">
<img width="1636" alt="objectbox2" src="https://github.com/user-attachments/assets/5c794cbb-80f2-4fcb-ab74-9b056726090e">

</details>

**Comment by greenrobot-team** [comment]
Thanks for reporting. Though I'm not sure there is something ObjectBox can do about this. The root cause is the size of the database and result set being too large for the available memory:

- When using in-memory mode the database is, as the name implies, stored in memory. So when storing many objects it needs more memory than in the regular file-based mode.
- When using `distinctUntilChanged()` on a Flow, [DistinctFlowImpl holds onto the previous results](https://github.com/Kotlin/kotlinx.coroutines/blob/6c6df2b850382887462eeaf51f21f58bd982491d/kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt#L72) to compare them against the new results. So if there are many objects in a result, this requires more memory.

What you can try is to

- Reduce the number of objects in the databases to make it consume less memory. Or not use in-memory mode.
- Add more query conditions to reduce the result set size.
- [Create a flow on the Box](https://docs.objectbox.io/kotlin-support#flow) itself and then on changes run a [Query with a limit](https://docs.objectbox.io/queries#limit-offset-and-pagination).

**Comment by udyr-woo** [comment]
> Thanks for reporting. Though I'm not sure there is something ObjectBox can do about this. The root cause is the size of the database and result set being too large for the available memory:
> 
> * When using in-memory mode the database is, as the name implies, stored in memory. So when storing many objects it needs more memory than in the regular file-based mode.
> * When using `distinctUntilChanged()` on a Flow, [DistinctFlowImpl holds onto the previous results](https://github.com/Kotlin/kotlinx.coroutines/blob/6c6df2b850382887462eeaf51f21f58bd982491d/kotlinx-coroutines-core/common/src/flow/operators/Distinct.kt#L72) to compare them against the new results. So if there are many objects in a result, this requires more memory.
> 
> What you can try is to
> 
> * Reduce the number of objects in the databases to make it consume less memory. Or not use in-memory mode.
> * Add more query conditions to reduce the result set size.
> * [Create a flow on the Box](https://docs.objectbox.io/kotlin-support#flow) itself and then on changes run a [Query with a limit](https://docs.objectbox.io/queries#limit-offset-and-pagination).
> 
> Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

Ok. I will do not use in-memory mode. But, If I cancel the flow subscription, shouldn't I close the query and reduce the memory? But I saw that the memory in the native memory area did not decrease and remained the same.

**Comment by greenrobot-team** [comment]
> shouldn't I close the query and reduce the memory? But I saw that the memory in the native memory area did not decrease and remained the same.

Yes, cancel the subscription and close the query once done with it. However, native memory is likely managed by the operating system, so it won't be reclaimed when running garbage collection on the Java virtual machine. The operating system should reclaim it once needed.

Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

**Comment by udyr-woo** [comment]
> > shouldn't I close the query and reduce the memory? But I saw that the memory in the native memory area did not decrease and remained the same.
> 
> Yes, the subscription should be canceled and the query closed once done with it. However, native memory is likely managed by the operating system, so it won't be reclaimed when running garbage collection on the Java virtual machine. The operating system should reclaim it once needed.
> 
> Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

Thank you for your kind reply. I have a final question (this is purely a question I'm asking because I don't know this library yet) 

override suspend fun updateInstances(list: List<RepeaterHwResponseDto>) = withContext(ioDispatcher) {
        val modifiedInstances = mutableListOf<RepeaterEntity>()
        val modifiedInputs = mutableListOf<RepeaterInputEntity>()
        val modifiedOutputs = mutableListOf<RepeaterOutputEntity>()
        val startTime = System.currentTimeMillis()

        list.forEach { responseDto ->
            val fullCompositeKey =
                "${responseDto.repeaterStationId}-${responseDto.ccuId}-${responseDto.id}"

                val instance = fullCompositeKeyQuery.setParameter(RepeaterEntity_.fullCompositeKey, fullCompositeKey).findUnique()
                if (instance != null) {
                    var parentModified = false

                    // 부모 데이터 변경
                    if (instance.connect != responseDto.connect) {
                        instance.previousConnect = instance.connect
                        instance.connect = responseDto.connect
                        parentModified = true
                    }

                    // 자식 데이터 변경 감지
                    responseDto.inputs.forEachIndexed { index, inputDto ->
                        val input = instance.inputs.getOrNull(index)
                        if (input != null && (input.signal != inputDto.signal || input.wireBreak != inputDto.wireBreak)) {
                            input.previousSignal = input.signal
                            input.signal = inputDto.signal
                            input.wireBreak = inputDto.wireBreak
                            modifiedInputs.add(input)
                            parentModified = true
                        }
                    }

                    responseDto.outputs.forEachIndexed { index, outputDto ->
                        val output = instance.outputs.getOrNull(index)
                        if (output != null && output.signal != outputDto.signal) {
                            output.signal = outputDto.signal
                            output.repeater.target = instance
                            modifiedOutputs.add(output)
                            parentModified = true
                        }
                    }

                    // 부모의 버전 업데이트
                    if (parentModified) {
                        instance.parentVersion += 1
                        modifiedInstances.add(instance)
                    }
                } else {
                    Log.w("RepeaterDao", "Instance not found for : $fullCompositeKey")
                }
        }
        val endTime = System.currentTimeMillis()
//        Log.d("RepeaterDao", "repeater make Time taken to reach : ${endTime - startTime} ms")

        // 변경된 부모 엔티티 저장 (자식은 자동 저장)
        if (modifiedInstances.isNotEmpty()) {
            impermanenceBoxStore.boxFor<RepeaterEntity>().put(modifiedInstances)
            impermanenceBoxStore.boxFor<RepeaterInputEntity>().put(modifiedInputs)
            repeaterBox.put(modifiedInstances)
//            Log.d("RepeaterDao", "modifiedInstances: ${modifiedInstances.count()}")
        }
    }

Is there any other way than to run the find series function over and over again?(And if there's anything else wrong with my code, I'd like you to point it out.)

**Comment by udyr-woo** [comment]
> > shouldn't I close the query and reduce the memory? But I saw that the memory in the native memory area did not decrease and remained the same.
> 
> Yes, the subscription should be canceled and the query closed once done with it. However, native memory is likely managed by the operating system, so it won't be reclaimed when running garbage collection on the Java virtual machine. The operating system should reclaim it once needed.
> 
> Note: I labeled this issue with "more info required" so it will auto-close in a few days if there are no follow-up comments.

Thank you for kind answer
