### ISSUE TITLE
Obtaining a box for an entity causes compile error in kotlin activity

### ISSUE THREAD

**Issue by SanityResort** [objectbox/objectbox-java#177]
## Basics
- ObjectBox version (are using the latest version?): 1.0.0
- Reproducibility: always

### Description

When I try to obtain a box for an entity in a kotlin activity I get compile errors. Using the same methods in a java activity works.

### Code
https://github.com/SanityResort/reproduceObjectBox177

### Logs & stackstraces
../AndroidStudioProjects/Reproduce2/app/src/main/java/reproduce/ReproduceActivity.kt
Error:(24, 74) Name expected
Error:(24, 75) Expecting ')'

**Comment by DJafari** [comment]
i suggested see kotlin example :

https://github.com/objectbox/objectbox-examples

your problems :
1. in the application class :

```
lateinit var boxStore: BoxStore
```

2. in your activity class :

```
val box: Box<Dummy> = (application as ReproduceApplication).boxStore.boxFor(Dummy::class.java)
```

**Comment by SanityResort** [comment]
Ah, did not see those examples, only tried to figure it out by the java based docs. Using the proper class notation in the activity works. Sorry for the hassle.
