### ISSUE TITLE
ToMany-Relation gets reset if using kotlin classes with additional lists initialized with default value

### ISSUE THREAD

**Issue by SanityResort** [objectbox/objectbox-java#191]
## Issue Basics
- ObjectBox version (are using the latest version?): 1.0.1
- Reproducibility: always

### Description
If an entity has a ToMany relation initialized by the default constructor and also has another list field that is initialized with a default value the ToMany relation is reset after the constructor finishes.

### Code
Clone https://github.com/SanityResort/objectbox-reproduce and run the Application class, it will fail at the last block when checking the student relation in teacher1.

### Logs & stackstraces

n/a

## Entities
see github

## Misc
Workarounds are shown in the github repo

**Comment by greenrobot-team** [comment]
First of all can reproduce with the example project.

I looked at the byte-code (decompiled to Java) and the constructors look fine, when a default value is specified. It calls the all-args constructor where the transformer will add the ToMany init code, and afterwards the `addAll` is called:

```java
public TeacherWithLessons(@NotNull List studentsForInit, @NotNull List lessons) {
   Intrinsics.checkParameterIsNotNull(studentsForInit, "studentsForInit");
   Intrinsics.checkParameterIsNotNull(lessons, "lessons");
   super();
   this.studentsForInit = studentsForInit;
   this.lessons = lessons;
   ToMany var10000 = this.students;
   if (this.students == null) {
      Intrinsics.throwUninitializedPropertyAccessException("students");
   }

   var10000.addAll((Collection)this.studentsForInit);
}

// $FF: synthetic method
public TeacherWithLessons(List var1, List var2, int var3, DefaultConstructorMarker var4) {
   if ((var3 & 2) != 0) {
      var2 = CollectionsKt.emptyList();
   }

   this(var1, var2);
}
```

Yet, when stepping through with a debugger, after the `init` method finishes the `ToMany` is initialized again inside a constructor call (`<init>:8, TeacherWithLessons`).

Investigating...

-ut

**Comment by greenrobot-team** [comment]
Alright, have a fix (internally, branch `ignore-constructors-w-this`) for the transformer: it will no longer add relation field initialization code to constructors that call other constructors (through `this()`).

This is planned to ship with `1.5.0`.
-ut
