### ISSUE TITLE
Main site referencing beta license

### ISSUE THREAD

**Issue by kerusu** [objectbox/objectbox-java#208]
Hey there, 

Objectbox is awesome and I want to start using it in our app. Before that I wanted to clarify licensing used for objectbox (sorry for newbie question):

1. Main page references this license (http://objectbox.io/license/) which is referenced as for beta version of library. 
2. At the same time under Documentation section the following reference to license can be found: http://objectbox.io/0209-ob-binary-license/

Could you please let me know what license I should consider in case of making use of ObjectBox in our app?

**Comment by greenrobot-team** [comment]
Sorry for the confusion. As [mentioned in the FAQ](http://objectbox.io/faq/#License_Open_Source), the Java components of ObjectBox (inside this repository) are currently licensed under Apache 2.0. The core/binary part of ObjectBox is currently closed source under [the binary license you found on the website](http://objectbox.io/0209-ob-binary-license/). -ut

**Comment by kerusu** [comment]
Thanks for detailed answer!

**Comment by mario** [comment]
@greenrobot is this likely to change any time soon? I'd like to use it for Nextcloud Talk (https://nextcloud.com/talk/), but I'm afraid as it stands - I can't :(
