### ISSUE TITLE
Relations: Many to many

### ISSUE THREAD

**Issue by jrcacd** [objectbox/objectbox-java#213]
In the documentation...
[Many-to-Many (N:M)](http://objectbox.io/documentation/relations/)
...does not explain how to get all the students of one specific teacher

**Comment by greenrobot-team** [comment]
The many-to-many relation currently has a direction, so this does not work. As of now, you would have to add another many-to-many relation and duplicate the relationships.

See #22 for details on this.
-ut

**Comment by jrcacd** [comment]
This way?

```
@Entity
public class Pet {
   @Id long id;
   @Relation
    List<Owner> owners;
}

@Entity
public class Owner {
    @Id long id;
    @Relation
    List<Pet> pets;
}
```

And I must insert in both?

**Comment by greenrobot-team** [comment]
`@Relation` is deprecated. Do it [like it is explained in the docs](http://objectbox.io/documentation/relations/). And yes, you have to set the pet's owners and the owner's pets. You only have to insert the entities once though. -ut

**Comment by jrcacd** [comment]
Ok. But I need some help.

```
@Entity
class Owner {
    @Id var id : Long = 0
    lateinit var pets: ToMany<Pet>
}
```

After put one owner in the db, the pets is = null. 
I must initialize it? 
If so, to what?

**Comment by greenrobot-team** [comment]
As I mentioned, please read [the documentation about Relations](http://objectbox.io/documentation/relations/). Everything is explained there, including with examples. -ut
