### ISSUE TITLE
FAQ: Library overhead

### ISSUE THREAD

**Issue by ScottPierce** [objectbox/objectbox-java#25]
It'd be useful to have some data in the FAQ about the databases overhead

* size
* method count
* how much can pro-guard reduce

**Comment by Miha-x64** [comment]
...including size of JNI libs, which is cannot be reduced by ProGuard.
(Presentations says ObjectBox is in C/C++. For instance, many people avoiding Realm because it has large JNI libraries.)

**Comment by FabianTerhorst** [comment]
Arch | ObjectBox-Size | Realm-Size
--- | --- | ---
x86 | 1,3MB | 3,2MB
x86_64 | - | 3,1MB
mips | - | 3,6MB
arm64-v8a | 1,1MB | 2,8MB
armeabi-v7a | 838,5KB | 1,8MB

**Comment by greenrobot-team** [comment]
Some more recent values (using `2.2.0`) sourced using Android Studio APK Analyzer with our basic example.

`io.objectbox` package stats for default Android setup (no shrinking/optimization):

Defined Methods | Referenced Methods | Size
--- | --- | ---
1217 | 1263 | 124 KB

Size of native libraries bundled with `objectbox-android`:

Arch | Size
--- | ---
x86 | 483 KB
x86_64 | 456 KB
arm64-v8a | 419 KB 
armeabi-v7a | 355 KB 

-ut
