### ISSUE TITLE
AndroidObjectBrowser(boxStore).start(application) return false

### ISSUE THREAD

**Issue by weiyf** [objectbox/objectbox-java#260]
AndroidObjectBrowser(boxStore).start(application) return false

**Comment by greenrobot-team** [comment]
Check if your build file has the `objectbox-android-objectbrowser` included and the dependency is defined before applying the `io.objectbox` plugin.

See an [example build file](https://github.com/objectbox/objectbox-examples/blob/master/objectbox-example/build.gradle#L12-L19).
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
