### ISSUE TITLE
Attempting query with List member crashes with "Entity is expected to have a no-arg constructor"

### ISSUE THREAD

**Issue by stevesamknows** [objectbox/objectbox-java#320]
First, apologies, as I'm probably doing it wrong -- OTOH there isn't a lot of information
on using Lists with ObjectBox so other users may encounter similar issues...

Summary:
Goal is to support add-or-update to an entity containing a List<String> member.
The "add" (insert to DB on initial app launch) succeeds, but the "update" (running
query on subsequent app launch) will crash with error:
"Entity is expected to have a no-arg constructor"

Steps to reproduce:
* Open attached project in android studio, build and launch
Expect app to launch OK
* Close and re-launch app
Expect app to crash on every subsequent launch attempt

Note: if the entity contains only primitives (no List/Converter) the query works fine.

[ObjectBoxListDemo.zip](https://github.com/objectbox/objectbox-java/files/1586256/ObjectBoxListDemo.zip)

**Comment by TonyNikolov** [comment]
I just managed to solve the same problem, only my entity was not using lists or converters. When you create the object, make sure you are using the labels(thats what they are called in Swift, no idea in Kotlin) Notes(name = "First task", date = "12-12-2007") and not Notes("First task", "12-12-2007")

**Comment by williamwue** [comment]
I have same issue. I have define code just like this:

**Comment by greenrobot-team** [comment]
As the error message indicates, ObjectBox requires an empty constructor to re-create objects. In this case it works by explicitly adding one:
`constructor() : this(0, "", listOf())`

Not sure if that is by design (read: required if non-primitives are used) or oversight. @greenrobot 

-ut

**Comment by stevesamknows** [comment]
Any thoughts on how would you change the code in the attached project to make this work
(either the Converter object, or the objectBox query code)?

(This is the simplest possible boilerplate sample Converter I could find, so don't care about
altering the design, just want to find out how to address the error so that lists become a
viable option.)

**Comment by greenrobot-team** [comment]
Sorry, maybe was not clear enough: for example add the following no argument constructor to the `@Entity` data class:

```kotlin
data class ... {

    constructor() : this(0, "", listOf())

}
```

-ut

**Comment by stevesamknows** [comment]
Or even better, simply add default args to the objectbox Entity...attaching updated
project which fixes the problem (demonstrates both approaches)

[ObjectBoxListDemoFixed.zip](https://github.com/objectbox/objectbox-java/files/1611380/ObjectBoxListDemoFixed.zip)

**Comment by stevesamknows** [comment]
One final note: the original problem is apparent on Android 7 devices; when I ran the original  (without the fix) project attached above on an Android 8 device, it didn't crash on subsequent launches.
Not sure what the difference is (and not suggesting it merits investigation), just noting here
for completeness...

**Comment by greenrobot-team** [comment]
Ah, your solution is more elegant. I just saw that [the docs kind of hint at this](http://objectbox.io/documentation/kotlin/#Entity_Constructors), but do not explicitly mention the solution to provide default args or a default constructor.

I tried your original project on an Android 8 emulator and it did crash as well, maybe this was a versioning issue on your end.
-ut
