### ISSUE TITLE
(Minor) Update for modern gradle

### ISSUE THREAD

**Issue by stevesamknows** [objectbox/objectbox-java#322]
(This is very minor, merely to address warning suppression)

Please update "compile" to "implementation" to suppress build warnings in user projects e.g.
`Configuration 'androidTestCompile' in project ':myobjboxmodule' is deprecated. Use 'androidTestImplementation' instead.`

**Comment by greenrobot-team** [comment]
Thanks for reporting. This will be fixed with the next update. See #375 for details. -ut
