### ISSUE TITLE
Kotlin with relations

### ISSUE THREAD

**Issue by JohannesDev** [objectbox/objectbox-java#333]
I want to use relations with Kotlin in my project. After the objects have been created, I want to read them in a different fragment. I have 2 Entities which are connected through a One-To-Many (1 : N) relation.

**Playlist Entity:**
```
@Entity
class Playlist (
    @Id var id : Long,
    var name : String
){
    @Backlink lateinit var songs: ToMany<Song>
}
```

**Song Entity:**
```
@Entity
data class Song (
        @Id var id: Long,
        var name : String
){
    lateinit var playlist: ToOne<Playlist>
}
```

**Saving Entities:**
```
 val playlist1 = Playlist(0,"Playlist1")
        Playlist1.songs.add(Song(0,"Song1"))
        Playlist1.songs.add(Song(0,"Song2"))
        playlistBox.put(playlist1)
```

**Reading Entities:**
```
val latestPlaylist : ArrayList<Kartpoint> = ArrayList()
val entries = kartrideBox.all[kartrideBox.count().toInt()-1].id

val getLatestPlaylist = (activity as MainActivity).boxStore.boxFor(Playlist::class.java).get(entries)
for (song in getLatestPlaylist.song) {
            latestPlaylist.add(song)
}
Snackbar.make(fragment, "Songs in Playlist: " + latestPlaylist.size, Snackbar.LENGTH_LONG).show()
```

**The exception I get:**

> FATAL EXCEPTION: main
> Process: xxx.yyy.zzz, PID: 28347
> io.objectbox.exception.DbException: Entity is expected to have a no-arg constructor: Song
> …

I would really appreciate any help.

**Comment by TKolbusz** [comment]
Add second constructor with no args so ObjectBox can create an object

**Comment by JohannesDev** [comment]
How would I do this in Kotlin? Do I have to use [compiler plugins](https://kotlinlang.org/docs/reference/compiler-plugins.html)? 
Or is it possible to create a second constructor without any plugins?

**Comment by greenrobot-team** [comment]
Either explicitly add a no argument constructor, like:
```kotlin
data class ... {
    constructor() : this(0, "")
}
```

Or try to provide default values for all constructor arguments. This way Kotlin will create a no argument constructor behind the scenes (you can check using the 'Show Kotlin bytecode' action, then 'Decompile'). For example:
```kotlin
@Entity
data class Song (
        @Id var id: Long = 0,
        var name : String = ""
){
    lateinit var playlist: ToOne<Playlist>
}
```
-ut

**Comment by JohannesDev** [comment]
Thanks a lot! Worked amazingly well. I really appreciate your detailed answer.
