### ISSUE TITLE
Use predefines ObjectBox database.

### ISSUE THREAD

**Issue by ali-abbas-10p** [objectbox/objectbox-java#344]
Is there any way to load pre-created Object box database?
Like putting your database file in the assets folder and tell MyObjectBox to load a database from assets, instead of creating a new one.

**Comment by chiara-jm** [comment]
maybe you should check and "star" this: https://github.com/objectbox/objectbox-java/issues/310

**Comment by greenrobot-team** [comment]
@chiara-jm Thanks. Closing in favor of discussing/voting at #310. -ut

**Comment by yizeliang** [comment]
Whether the mdb file is cross-platform,For example, I am generating on x86, can I use armbi-v7a again?
