### ISSUE TITLE
In Android Studio 3.0 Build Fails with 1.4.0 version

### ISSUE THREAD

**Issue by hushengjun** [objectbox/objectbox-java#346]
How to solve it？

classpath 'io.objectbox:objectbox-gradle-plugin:1.4.0'
apply plugin: 'io.objectbox'
releaseImplementation 'io.objectbox:objectbox-android:1.4.0'
debugImplementation 'io.objectbox:objectbox-android-objectbrowser:1.4.0'

Error Message：
AGPBI: {"kind":"error","text":"Error converting bytecode to dex:\nCause: com.android.dex.DexException: Multiple dex files define Lio/objectbox/android/AndroidObjectBrowserReceiver;","sources":[{}],"original":"UNEXPECTED TOP-LEVEL EXCEPTION:\ncom.android.dex.DexException: Multiple dex files define Lio/objectbox/android/AndroidObjectBrowserReceiver;\n","tool":"Dex"}
AGPBI: {"kind":"error","text":"com.android.dex.DexException: Multiple dex files define Lio/objectbox/android/AndroidObjectBrowserReceiver;","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:198)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)","sources":[{}]}
AGPBI: {"kind":"error","text":"\tat java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)","sources":[{}]}

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lio/objectbox/android/AndroidObjectBrowserReceiver;

**Comment by greenrobot-team** [comment]
If you want to use the `objectbox-android-objectbrowser` artifact, make sure to move `apply plugin: 'io.objectbox'` after the `dependencies` block. Otherwise the plugin will also add `objectbox-android` to your dependencies which will lead to duplicate files. -ut

**Comment by hushengjun** [comment]
Thanks, It has been building a successful.

**Comment by slickorange** [comment]
I have put the `apply plugin: 'io.objectbox'` below the dependencies block but I still get the error.
I am using daocompat, not sure if that makes a difference.
