### ISSUE TITLE
How to see the data of ToMany 

### ISSUE THREAD

**Issue by Haskell2015** [objectbox/objectbox-java#350]
Hi, it's really amazing that we can now see the data by Data Browser.
The issue is that today I new two entities as below : 
 
TradeEntity.class

	@Entity
	public class TradeEntity {
	    @Id
	    public long id;

	    public String orderNum;

	    @Backlink
	    public ToMany<OrderEntity> orderItems;
	}  

and OrderEntity.class:

	@Entity
	public class OrderEntity {
	    ToOne<TradeEntity> tradeInfo;
	    @Id
	    public long id;

	    public String goodsPlu;
	
	    public String goodsName;
	
	    public String goodsUnitPrice;
	   
	    public String goodsWeightOrAmount;
	}

After I add some data,I open the Browser,I cannot see the data of OrderEntity.  

![](https://i.imgur.com/myaVRH3.jpg)

**Comment by greenrobot-team** [comment]
The Data Browser literally displays what is in the database.

If you look at your model file (by default in `objectbox-models/default.json`) you can see that only `OrderEntity` that has the `ToOne` has an ID reference (`tradeInfoId`) to `TradeEntity` with the `ToMany` back link.

So you can only see the ID of the related `TradeEntity` when viewing the `OrderEntity`s (select them in the `Type` drop-down). -ut

**Comment by Haskell2015** [comment]
Thanks : )
