### ISSUE TITLE
UninitializedPropertyAccessException for relation during local unit test.

### ISSUE THREAD

**Issue by AleksanderMielczarek** [objectbox/objectbox-java#354]
## Issue Basics
- ObjectBox version (are using the latest version?): 1.4.1
- Reproducibility: always

### Description
I'm getting `kotlin.UninitializedPropertyAccessException` during `JUnit` local tests on `Windows 10 x64`. Tested entity has `ToOne` which is the root of the problem. I can manually set `lateinit` relation before test (#240) but it does not resolve problem because I cannot set this field for object retrieved from box.

### Code
**Link to example project:** https://github.com/AleksanderMielczarek/ObjectBoxUnitTest

```Kotlin
class ObjectBoxRule : TestRule {

    lateinit var orderBox: Box<Order>

    override fun apply(base: Statement, description: Description): Statement {
        return object : Statement() {
            override fun evaluate() {
                val tempFile = File.createTempFile("object-store-test", "")
                tempFile.delete()
                val boxStore = MyObjectBox.builder().directory(tempFile).build()
                orderBox = boxStore.boxFor(Order::class.java)

                base.evaluate()

                boxStore.close()
                boxStore.deleteAllFiles()
            }
        }
    }
}


class ObjectBoxTest {

    @JvmField
    @Rule
    val objectBoxRule = ObjectBoxRule()

    @Test
    fun shouldSaveOrder() {
        val order = Order(name = "Order")
        val customer = Customer(name = "Customer")
        order.customer.target = customer

        objectBoxRule.orderBox.put(order)

        assertTrue(objectBoxRule.orderBox.all.any { it.name == "Order" })
        assertTrue(objectBoxRule.orderBox.all.any { it.customer.target.name == "Customer" })
    }
}
```

### Logs & stackstraces
> kotlin.UninitializedPropertyAccessException: lateinit property customer has not been initialized
> 	at com.github.aleksandermielczarek.objectboxunittest.Order.getCustomer(Order.kt:12)
> 	at com.github.aleksandermielczarek.objectboxunittest.ObjectBoxTest.shouldSaveOrder(ObjectBoxTest.kt:20)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at com.github.aleksandermielczarek.objectboxunittest.ObjectBoxRule$apply$1.evaluate(ObjectBoxRule.kt:24)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

## Entities
```
@Entity
data class Customer(@Id var id: Long = 0, var name: String = "")


@Entity
class Order(@Id var id: Long = 0, var name: String = "") {
    lateinit var customer: ToOne<Customer>
}
```

**Comment by AleksanderMielczarek** [comment]
I've just tested using instrumented test and it seems to work fine. Example project updated.

```
class InstrumentedObjectBoxRule : TestRule {

    lateinit var orderBox: Box<Order>

    override fun apply(base: Statement, description: Description): Statement {
        return object : Statement() {
            override fun evaluate() {
                val tempFile = File.createTempFile("object-store-test", "")
                tempFile.delete()
                val boxStore = MyObjectBox.builder()
                        .androidContext(InstrumentationRegistry.getTargetContext())
                        .build()
                orderBox = boxStore.boxFor(Order::class.java)

                base.evaluate()

                boxStore.close()
                boxStore.deleteAllFiles()
            }
        }
    }
}


@LargeTest
@RunWith(AndroidJUnit4::class)
class ObjectBoxInstrumentedTest {

    @JvmField
    @Rule
    val objectBoxRule = InstrumentedObjectBoxRule()

    @Test
    fun shouldSaveOrder() {
        val order = Order(name = "Order")
        val customer = Customer(name = "Customer")
        order.customer.target = customer

        objectBoxRule.orderBox.put(order)

        assertTrue(objectBoxRule.orderBox.all.any { it.name == "Order" })
        assertTrue(objectBoxRule.orderBox.all.any { it.customer.target.name == "Customer" })
    }
}
```

**Comment by greenrobot-team** [comment]
This is because the byte-code transformer which inserts initialization code for `ToOne` and `ToMany` properties only works for Android or plain-Java code. To get your local unit tests working you have to make sure to initialize your `ToOne` and `ToMany` fields before using them, for example:

`this.customer = ToOne(this, Order_.customer);`

-ut

**Comment by greenrobot-team** [comment]
There is now additional documentation available on [how to build Android local unit tests](http://objectbox.io/documentation/android-unit-tests/), an [example test](https://github.com/objectbox/objectbox-examples/tree/master/objectbox-example/src/test/java/io/objectbox/example) is also including in the example project. -ut

**Comment by greenrobot-team** [comment]
This was already reported in #240. Closing this as duplicate. -ut
