### ISSUE TITLE
ObjectBox in kotlin does not with a non-top level package

### ISSUE THREAD

**Issue by PaulMuriithi** [objectbox/objectbox-java#359]
## Issue Basics
- ObjectBox version: latest - `1.4.1`
- Reproducibility: always

## Reproducing the bug
When trying to use ObjectBox using kotlin and having models in a different package, then `MyObjectBox` is not found. 
The `default.json` has the models though

### Code
https://github.com/PaulMuriithi/ObjectBoxKotlinTest

### Logs & stackstraces
`Error:(20, 21) Unresolved reference: MyObjectBox
`
## Entities
```
@Entity
data class Note(
        @Id var id: Long = 0,
        var text: String? = null,
        var comment: String? = null,
        var date: Date? = null
)
```

## Workarounds
- Having the models in the top level package but this is not good.

**Comment by greenrobot-team** [comment]
Using your test project I did as [mentioned in the instructions](http://objectbox.io/documentation/introduction/): build the project, for example using 'Build > Make Project` in Android Studio. Then `MyObjectBox` will get generated (`import com.objectboxkotlintest.models.MyObjectBox`) and you can import it in `App`.
-ut

**Comment by PaulMuriithi** [comment]
I followed the kotlin example https://github.com/objectbox/objectbox-examples/tree/master/objectbox-kotlin-example
Did you make any changes for it to work and would you mind kindly sending them as a PR?

**Comment by greenrobot-team** [comment]
See https://github.com/PaulMuriithi/ObjectBoxKotlinTest/pull/1. -ut

**Comment by PaulMuriithi** [comment]
Thanks so much @greenrobot-team, that worked. I am closing this issue.
