### ISSUE TITLE
Why are we still using the beta-repo?

### ISSUE THREAD

**Issue by sumit-anantwar** [objectbox/objectbox-java#365]
1.4.1 has already been released.
Why are we still using the beta-repo?
`maven { url "http://objectbox.net/beta-repo/" }`

Actually, we are really enjoying Objectbox. But, every time I see the `beta-repo` thing, my heart skips a beat! Makes me rethink our decision, maybe we were too eager to move on to Objectbox, maybe we should have waited a tad bit longer?

**Comment by greenrobot-team** [comment]
See https://github.com/objectbox/objectbox-java/issues/329 -ut
