### ISSUE TITLE
ToMany problem with remove object from relation

### ISSUE THREAD

**Issue by Draptol** [objectbox/objectbox-java#373]
Hi,

I have a problem with removing object from relation.
I have a class User who has two ToMany relations to other users.
First relation is like this:
`public ToMany<User> observedUsersByMe;`
Second relation is like this:
`public ToMany<User> usersWhoObservedMe;`
(Both users are stored inside database)
In first step I am setting up relations:
`UserEntity firstUser = userBox.get(ApplicationDataManager.getUserId());`
`UserEntity secondUser = userBox.get(tmp.getId()); `
`firstUser.observedUsers.add(secondUser);`
`secondUser.usersWhoObservedMe.add(firstUser);`
`userBox.put(firstUser, secondUser);`

In next step (other method) I want to remove relations: 
`UserEntity firstUser = userBox.get(ApplicationDataManager.getUserId());`
`UserEntity secondUser = userBox.get(tmp.getId()); `
`boolean tmp2 = firstUser.observedUsers.remove(secondUser);`
`boolean tmp3 = secondUser.usersWhoObservedMe.remove(firstUser);`
`userBox.put(firstUser, secondUser);`
Both `tmp2` and `tmp3` are false but I checked (in debug mode) that object with the same Id are inside this lists. I don't implement my own equals and hashCode. I think this is M:N relation because first user can observe multiple users and can be observed by multiple users. 

Could you help me ? Maybe this is not a bug but I am doing something wrong in my code and relations.

**Comment by greenrobot-team** [comment]
You kind of already got the issue. The instance of `UserEntity` returned by `userBox.get(long)` is different from the second one. It may contain the same data, but the underlying Java object (class instance) is different.

So as `ToMany.remove(Object)` uses `Object.equals(Object)` to find the entity to remove it will not find it.

A few solutions:
- use the same instance to remove the entity (like caching it somewhere)
- implement `equals(Object)` on your `UserEntity` class so `ToMany.remove(Object)` works as expected
- use `ToMany.removeById(long)`
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
