### ISSUE TITLE
Multiple MyObjectBox class

### ISSUE THREAD

**Issue by Artur512** [objectbox/objectbox-java#379]
Hey, I have a problem with multiples MyObjectBox.class In my project. The project consist of few modules with entity classes. After rebuild project ObjectBox is generating  multiples MyObjectBox.class without all references to all data classes. Is any possible to solve this problem? Define single MyObjectBox.class with all entities?

**Comment by greenrobot-team** [comment]
If you want to have all your entities associated with one `MyObjectBox` they have to be in the same module. However it is possible to have a separate database for each module. Just make sure to [define a different name](http://objectbox.io/files/objectbox-java/current/io/objectbox/BoxStoreBuilder.html#name-java.lang.String-) when building using `MyObjectBox.builder()`. -ut
