### ISSUE TITLE
Consistency of the db

### ISSUE THREAD

**Issue by namanmehta1997** [objectbox/objectbox-java#394]
Hey!!! First of all thanks for this beautiful library.
I want to ask a question regarding the consistency of the database.
I am using this in an application where the there are two entity classes. There are parallel threads which creates box for these entities.
Suppose thread 1 and thread 2 create box objects.
Both read from the same db. Will there be any problem if there are two instance alive at the same time for the same box in different threads?

**Comment by Yazon2006** [comment]
@namanmehta1997 http://objectbox.io/faq/

**Comment by greenrobot-team** [comment]
While the FAQ answer this indirectly, the ObjectBox API can generally be considered thread-safe.

So no, there should not be any problem. -ut
