### ISSUE TITLE
Support backlinks for many to many relations

### ISSUE THREAD

**Issue by dgandhi17** [objectbox/objectbox-java#407]
## Issue Basics
- ObjectBox version (are using the latest version?): *1.4.4*

### Description

I have 2 entities lets say teacher and student, how to achieve many to many while design its entity
because from your example we have to add many in one entity only how am i going to find tomany from other entity?

## Entities
Ex : 

```kotlin
@Entity
class Teacher {
    @Id
    var id: Long = NEW_ID

    @Backlink
    lateinit var notes: ToMany<Student>
}

@Entity
class Student {
    @Id
    var id: Long = NEW_ID

    lateinit var teachers: ToMany<Teacher>
}
```

**Comment by greenrobot-team** [comment]
Judging from your (incorrect) example you should probably [read the docs about Relations](http://objectbox.io/documentation/relations/).

In regard to your question: the many-to-many relation currently has a direction, so this does not work. As of now, you would have to add another many-to-many relation and duplicate the relationships.

See #22 for details on this. Closing as duplicate.
-ut

**Comment by greenrobot-team** [comment]
Decided to track ToMany with backlink with this ticket. #22 is already assigned to a milestone for release of one-way to-many relations.
-ut

**Comment by greenrobot-team** [comment]
The next version will support using `@Backlink` pointing to a `ToMany`.

Note: **After updating users may receive a processor warning** like
`Set name of one to-one or to-many relation of 'notes'`
if a `@Backlink` points to an entity that also contains a `ToMany`. For example:

```java
// THIS DOES NO LONGER WORK
@Entity
public class Customer {
    @Backlink
    public ToMany<Order> orders;
}
 
@Entity
public class Order {
    public ToOne<Customer> buyer;
    public ToMany<Customer> others;
}
```

To resolve this tell the `@Backlink` explicitly which relation it should point to, like:

```java
// THIS DOES NO LONGER WORK
@Entity
public class Customer {
    @Backlink(to = "buyer")
    public ToMany<Order> orders;
}
```
