### ISSUE TITLE
Release version crashes

### ISSUE THREAD

**Issue by kevindmoore** [objectbox/objectbox-java#408]
## Issue Basics
- ObjectBox version (are using the latest version?): 1.4.4
- Reproducibility:  Always

### Description
ObjectBox works fine in debug mode but when I created a release version, it seems like it is able to save 1 object type but not another. I've included objectbox proguard statements in my proguard file.

### Code

```
    val podcastBox : Box<Podcast>

    init {
        podcastBox = boxStore.boxFor(Podcast::class.java)
    }

    suspend override fun addItem(item: Podcast) : Long {
        return podcastBox.put(item) // Crashes here
    }
```
### Logs & stackstraces

```
java.lang.IllegalArgumentException: Illegal key value: 0
    at io.objectbox.Cursor.nativeGetEntity(Native Method)
        at io.objectbox.Cursor.a(Unknown Source)
        at io.objectbox.a.a(Unknown Source)
        at com.mastertechsoftware.dailypodcast.data.repositories.LocalPodcastRepository.addItem(Unknown Source)
                                                                                        deleteAll
                                                                                        getItem
        at com.mastertechsoftware.dailypodcast.c.c$ab.a(Unknown Source)
        at b.d.a.b.a.a.a(Unknown Source)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.getSuccessfulResult(Unknown Source)
                                                                       run
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
```
## Entities

```
@Entity
data class Podcast(
        @Id
        var id : Long = 0,
        var title : String = "",
        var description : String = "",
        var url : String = "",
        var remoteImagePath: String? = null,
        var latestEpisode : String? = null,
        var imageChecked : Boolean = false,
        var episodes : ToMany<Episode>? = null
)
```
## Misc
*Is there anything special about your app? No
May transactions or multi-threading play a role? I do use Coroutines
Did you find any workarounds to prevent the issue?* No

**Comment by greenrobot-team** [comment]
Your stack trace looks weird. But it looks like the exception is actually originating from the `getItem` method.

I suspect you are doing something like `box.get(0)` which is invalid for ObjectBox. [`0` is a reserved id](http://objectbox.io/documentation/object-ids/) that is never assigned to entities. It is used to signal ObjectBox to assign the next available id to an entity to be put.

Hence the `Illegal key value: 0` message.
-ut

**Comment by kevindmoore** [comment]
Ok, I think it is fixed. Must have been a fixed proguard file
