### ISSUE TITLE
How to dynamically generate a table?

### ISSUE THREAD

**Issue by zhufengweihai** [objectbox/objectbox-java#420]

**Comment by greenrobot-team** [comment]
This is not possible. Maybe try to create a generic entity class instead.

ObjectBox is designed around you creating your boxes ("tables") at compile time by defining classes annotated with `@Entity`. Then it generates various helper classes that simplify storing and retrieving data.

Allowing to dynamically add or remove boxes ("tables") contradicts this somewhat.
-ut
