### ISSUE TITLE
ToMany<Verse> is not initialized when running app for the first time

### ISSUE THREAD

**Issue by karzelekp** [objectbox/objectbox-java#435]
I have a problem with such field (throws UninitializedPropertyAccessException):
```
    @Backlink
    lateinit var verses: ToMany<Verse>
```
But it occurs only when I launch application for the first time after installation.

tested on versions 1.4.3 and 1.5.0 RC

Here is sample project:
https://bitbucket.org/karzelekp/objectbox-bug

the most important code:
```
        val booksBox = boxStore().boxFor(Book::class.java)
        var books = booksBox.all
        if (books.isEmpty()) {
            books = Gson().fromJson(getJson(this), Array<Book>::class.java).toList()
            booksBox.put(books)
        }
        books.first().verses.toList()
        return books
```

**Comment by greenrobot-team** [comment]
For completeness: `ToMany` and `ToOne` currently do not work out of the box with Gson. See #104 for a discussion.

Here: the `ToMany` is initialized in the constructor of your object (the init code is injected by the ObjectBox transformer), which I suppose Gson does not call? You might try to initialized the `ToMany` yourself:
`var verses: ToMany<Verse> = ToMany<>(this, YourEntity_.verses);`

However: there were some improvements for Kotlin data classes in `1.5.0`, updating to it might also solve your issue.
-ut

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut
