### ISSUE TITLE
Get newly inserted data

### ISSUE THREAD

**Issue by f3ell0w** [objectbox/objectbox-java#438]
Hello. Here is what I do not fully understand:

Let's say, I have 10 records of a certain model in my database and a subscription with **.onlyChanges** called on it. I insert a new row and in the observer I get a list of **11 row**s, but not **1**. 

I don't know if it is an issue or if it is up to query to be properly constructed to get updates only, but the question is, how do i get the newly inserted data only instead of all of it?

Here is the query:
`@Override
    public Query<ChatMessage> messagesQuery(int userId) {
        return repository.query()
                .equal(ChatMessage_.userId, userId)
                .build();
    }`

**Comment by greenrobot-team** [comment]
For completeness: the `onlyChanges()` flag only modifies when the query is (re-)run. The query itself will always return all of its results. -ut
