### ISSUE TITLE
[ASK] ObjectBox Query and Writes on Thread

### ISSUE THREAD

**Issue by GulajavaMinistudio** [objectbox/objectbox-java#445]
## Issue Basics
- ObjectBox version (are using the latest version?): *1.5.0*
- Are objectbox queries and objectbox writes is asynchronous ? or synchronous ?
- Should we wrap it with AsyncTask or RxJava for async operation that not blocking main thread ?

**Comment by greenrobot-team** [comment]
The ObjectBox Box and Query API is synchronous.

In general: all database operations of any kind should run on a background thread. You might get away with a very small query or put, but you can never guarantee that for example on a low power device the query will not cause your app to hang.

- There is [built-in support for data observers](http://objectbox.io/documentation/data-observers-reactive-extensions/) which can help you run queries in a background thread.
- There is also a [library to simplify using RxJava2](https://github.com/greenrobot/ObjectBoxRxJava), though its [Single is currently broken](https://github.com/greenrobot/ObjectBoxRxJava/pull/9).
- Or [use LiveData](http://objectbox.io/documentation/livedata/).

Also see the Android [guidance on background processing](https://developer.android.com/guide/background/).

Closing. Please re-open if this did not answer your question.
-ut
