### ISSUE TITLE
Need more example in Transaction Insert and Query

### ISSUE THREAD

**Issue by GulajavaMinistudio** [objectbox/objectbox-java#476]
From this documentation, there are several transaction in ObjectBox
http://objectbox.io/documentation/transactions/

> The class BoxStore offers the following methods to perform explicit transactions:
> runInTx: Runs the given runnable inside a transaction.
> runInReadTx: Runs the given runnable inside a read(-only) transaction. Unlike write transactions, multiple read transactions can run at the same time.
> runInTxAsync: Runs the given Runnable as a transaction in a separate thread. Once the transaction completes the given callback is called (callback may be null).
> callInTx: Like runInTx(Runnable), but allows returning a value and throwing an exception.

But I found little confused for runInTxAsync implementation. Any good example about how to implementation those transaction ?

**Comment by greenrobot-team** [comment]
Closing in favor of https://github.com/objectbox/objectbox-examples/issues/44 -ut
