### ISSUE TITLE
objectbox-windows-x64.dll already loaded in another classloader

### ISSUE THREAD

**Issue by jmiecz** [objectbox/objectbox-java#482]
Hello,

I am trying to create some unit tests (following what you guys have in the example) but I am getting this error and not sure how to handle it.

`java.lang.UnsatisfiedLinkError: Native Library .\objectbox-windows-x64.dll already loaded in another classloader`

**Comment by greenrobot-team** [comment]
We have seen this only when running unit tests with some additional framework, like Robolectric. What does your setup look like? Can you share your test project? -ut

**Comment by iamupgirl** [comment]
Have you solved this problem?I  had the same problem.

**Comment by greenrobot-team** [comment]
If this is due to using Robolectric, a solution is at https://github.com/objectbox/objectbox-java/issues/847#issuecomment-616324208.
