### ISSUE TITLE
Getting only a single object with RxQuery

### ISSUE THREAD

**Issue by hendrep** [objectbox/objectbox-java#486]
I have a box that updates very frequently.
I have also subscribed to a query on this box.
I am only interested in the newest object in the box.  I am not interested in the whole list and I am worried that obtaining the whole list every time will cause performance issues down the line as the box size grows.
Is there a way to limit the amount of objects the observable query returns?

**Comment by greenrobot-team** [comment]
Setting an offset or a limit on a query is currently not supported when subscribing to a query. So it also won't work using RxQuery.

See #303 which tracks adding support for setting offset and limit before while building a query.
-ut
