### ISSUE TITLE
NameInDb for Entity classes

### ISSUE THREAD

**Issue by Faltenreich** [objectbox/objectbox-java#488]
@NameInDb is currently being used as annotation for fields and types, so that users of ObjectBox may rename their database properties. Is there any possibility to do the same for Entity classes and if not, could this possibly be introduced in a future update?

Proposal:
`@NameInDb("ExampleEntity")
class ExampleEntitiy // This class may be renamed but its stored name stays the same as the annotation value`

I am asking this due to a project I am currently working on, where we match entities by table name. The table name is stored as a String property and later matched against our entities. I am worrying about upcoming problems when the corresponding entity classes get refactored / renamed and the matching algorithm does not work anymore.

**Comment by greenrobot-team** [comment]
[We discourage using `@NameInDb`](https://docs.objectbox.io/entity-annotations#basic-annotations-for-entity-properties) and encourage to use `@Uid` annotations instead.

Actually ObjectBox [supports renaming entity classes if you use `@Uid` annotations](https://docs.objectbox.io/advanced/data-model-updates#how-to-and-example).

You could then supply your own annotation to annotate entity classes with a unique (string) name.
-ut

**Comment by greenrobot-team** [comment]
Closing. Please re-open if your question was not answered. -ut
