### ISSUE TITLE
DataSubscription observer()'s arg is wrong type 

### ISSUE THREAD

**Issue by ersin-ertan** [objectbox/objectbox-java#502]
## Issue Basics
- ObjectBox version (are using the latest version? yes): *2.0.0-beta2*
- Reproducibility: *[always]*

### Description
`observer(...)` is asking for `DataObserver<Class<MyEntity>>` or `((data: Class<MyEntity>)->Unit)`
The caller can't do anything with the `Class` wrapped return type, I think the `Class` should be excluded from the type. 

### Code
```
var myEntityBox: Box<MyEntity>
var myEntityObserver: DataObserver<MyEntity>
var mySub: DataSubscription
mySub = ObjectBox.boxStore.subscribe(MyEntity::class.java).observer(myEntityObserver)
```

## Misc
*Following the [online example](https://docs.objectbox.io/data-observers-and-rx#observing-general-changes), is the `Class` suppose to be a `Task`?*
```
DataObserver<Class> taskObserver = ...;
boxStore.subscribe(Task.class).observer(taskObserver);
```
And can `myEntityBox.store.subscribe(...)` be used instead of `ObjectBox.boxStore` in the above example for a store restricted observation?

**Comment by greenrobot-team** [comment]
I believe `BoxStore.subscribe()` is meant to only notify you that a change has happened. It only passes the `Class<Entity>` so the same `DataObserver<T>` interface as for query observation can be used. So yes, there is nothing you can do with the returned value.

`myEntityBox.store` will get you the same `BoxStore` that was used to get the box using `BoxStore.boxFor()`. So `subscribe()` will behave exactly the same.
-ut
