### ISSUE TITLE
static parameter in entity is not permitted

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#505]
``` java
@Entity
public class A{

    public static final int a= 3;

    public static final int b= 2;

    public static final int c= 1;

    public static final int d= 0;

    @Id
    long id;

    int i;

    Date date;

    public TakeDrugRecord() {
    }

}
```
Upper code can't compile correctly.

**Comment by greenrobot-team** [comment]
Using the above entity works fine in a simple example: [ObStaticFields-GitHub-505.zip](https://github.com/objectbox/objectbox-java/files/2219226/ObStaticFields-GitHub-505.zip)

Can you please share the error message or stack trace you get? If possible, even a small example project like mine that reproduces this issue.
-ut

**Comment by tvvbbb** [comment]
Sorry to bother. It is my fault operation. Thanks.

**Comment by greenrobot-team** [comment]
Closing then. -ut
