### ISSUE TITLE
QueryFilter is not working when use findIds() ,but use find() is working

### ISSUE THREAD

**Issue by andy37380** [objectbox/objectbox-java#507]
## Issue Basics
- ObjectBox version (are using the latest version?): *2.0.0-beta2*
- Reproducibility: *always*

### Description
*QueryFilter is not working when use findIds() ,but use find() is working*

### Code

```
@Entity
public class Note {
    @Id public long id;
    public String title; 
    public String context;
}

QueryBuilder<Note > queryBuilder = NoteBox.query();
queryBuilder = queryBuilder.filter(new QueryFilter<Note>() {
    @Override
    public boolean keep(Noteentity) {
        return entity.context.length() > 100;
    }
});

long[] ids = queryBuilder.build().findIds();
```

**Comment by andy37380** [comment]
Thanks for reply.

**Comment by greenrobot-team** [comment]
Alright, closing then. Please re-open if your question was not answered. -ut

**Comment by mecoFarid** [comment]
@greenrobot-team  Quick question. Is this documented somewhere? If not, adding documentation or maybe keeping the issue open would be more helpful. I have been looking at every side of the project for a couple of hours. I would suggest adding a bug tag instead of a feature

**Comment by greenrobot-team** [comment]
@mecoFarid What is documented? E.g. the `findIds()` method API documentation explicitly states that a query filter is not applied.
