### ISSUE TITLE
multi modules use objectbox ,how to init and manage MyObjectBox?

### ISSUE THREAD

**Issue by luffycheung** [objectbox/objectbox-java#515]
I have a project with a app and multi modules(A、B、C), if I use objectbox in module lib,I don't know what's the best way.

- Now my solution is create a Application in module-A, init objectbox in the module A application.
- app and other module implementation project(':module-A')
- Then in app's Application class extends the module-A's Application.
- Unified management the entites class in the module-A.Make sure only the module-A  generated the MyObjectBox.

in greendao it can  init and generated in one module place,how to use objectbox in multi module and 
use data browser easily without build error?

**Comment by greenrobot-team** [comment]
What you described is how it should work. (You can have one BoxStore per module and entities can not be shared among different modules.)

So what issue do you have with the data browser? What error do you get? Make sure to [follow the setup procedure](https://docs.objectbox.io/data-browser).
-ut

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut

**Comment by Zpecter** [comment]
I have a similar problem, I have a project with 4 different modules, and I would like to have the MyObjectBox object in the principal one, beside activies, in another module some repositories which use a Box<T>, and a third module with my business entities. Is this possible?

**Comment by DurgaArunkumarSmitiv** [comment]
Same issue for me too. I implemented dynamic module as per Android App Bundle documentation.But when I run I am facing issue with object box ,object box processor debug false.Help resolving it.

**Comment by Wanchen7** [comment]
It works for me ~ [https://stackoverflow.com/questions/53546614/how-to-use-objectbox-in-gradle-multi-module-project](url)
