### ISSUE TITLE
[kotlin] AndroidObjectBrowser.start return false 

### ISSUE THREAD

**Issue by iago-silva** [objectbox/objectbox-java#517]
```
ObjectBox.build(this)
val result= AndroidObjectBrowser(ObjectBox.boxStore).start(this)
Log.d("debug", result.toString())
```

```
debugImplementation("io.objectbox:objectbox-android-objectbrowser:$objectboxVersion")
releaseImplementation "io.objectbox:objectbox-android:$objectboxVersion"
implementation "io.objectbox:objectbox-kotlin:$objectboxVersion"
```

**Comment by greenrobot-team** [comment]
Is this using ObjectBox version `2.0.0`?

Your setup code and dependency configuration looks fine. Please [have a look at the setup page](https://docs.objectbox.io/data-browser) and make sure you did not miss a step (applied plugin after deps, permission).

If this won't help we can only help if you share a small example project where we can reproduce this issue (creating one might also help you figure out what's wrong).
-ut

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue. -ut

**Comment by danparn** [comment]
Same problem persists on ver. 2.9.1
Demo attached
[ObjectBox.zip](https://github.com/objectbox/objectbox-java/files/6708009/ObjectBox.zip)

**Comment by greenrobot-team** [comment]
@danparn Works fine with your given example project (I only updated Gradle to 6.8.3). Can you share any more details on how to reproduce this? E.g. what device do you use to test? Do you make sure to run the debug variant?

```
2021-06-28 15:09:55.822 5861-5861/com.iocoma.objectbox I/ObjectBrowser: ObjectBrowser started: http://127.0.0.1:8090/index.html
2021-06-28 15:09:55.822 5861-5861/com.iocoma.objectbox I/ObjectBrowser: Command to forward ObjectBrowser to connected host: adb forward tcp:8090 tcp:8090
2021-06-28 15:09:55.835 5861-5861/com.iocoma.objectbox I/ObjectBrowser: Started: true
2021-06-28 15:09:56.988 5861-5861/com.iocoma.objectbox I/ObjectBox: noteBox.all: [Note(id=1, text=This is a note, createdAt=Mon Jun 28 13:09:56 GMT 2021)]
```

**Comment by danparn** [comment]
@greenrobot-team Now it works for me too with gradle 6.7.1 (android gradle pluin 4.2.1). Thank you very much.
