### ISSUE TITLE
[ObjectBox] Field type "java.time.LocalDate" is not supported.

### ISSUE THREAD

**Issue by jega-ms** [objectbox/objectbox-java#521]
## Feature Support 
 - Add support for java.time.LocalDate 
 - Add support for java.time.LocalTime
 - Add support for  java.time.LocalDateTime 

## Error 
error: [ObjectBox] Field type "java.time.LocalDate" is not supported. Consider making the target an @Entity, or using @Convert or @Transient on the field (see docs). (com.jega.bookeiz.android.domain.model.StaffEntity.doj)

**Comment by greenrobot-team** [comment]
Use the `@Convert` annotation. See the [Custom Types documentation](https://docs.objectbox.io/advanced/custom-types) for details. -ut

**Comment by jega-ms** [comment]
Looking for build-in support for java.time api
