### ISSUE TITLE
How can I change id;

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#522]
From:
```java
@id
long id;
int cardId;
```
to
```java
@id
long cardId
```
How can I do this.

**Comment by greenrobot-team** [comment]
You can do this by annotating `id` with `@Uid`. Then build to get the uid and update the `@Uid` annotation. Then rename the `id` property to `cardId`. However, data of the `cardId` property will be lost.

See the [data model updates documentation](https://docs.objectbox.io/advanced/data-model-updates) for details.

Closing. Please re-open if your question was not answered.
-ut
