### ISSUE TITLE
How to Join 2 Classes 

### ISSUE THREAD

**Issue by AminMemariani** [objectbox/objectbox-java#524]
Assume I have following model classes. How can apply join functionality in   ##ObjectBox?

```
public class Animal {
    @Id(assignable = true)
    public long id;
    private String name;
    private boolean flying;
    private boolean swimming;
    private boolean walking;
    private ToOne<Zoo> zoo;
/*setters and getters*/
}
```
and:

```
@Entity
public class Zoo {
    @Id
    public long id;
    private String name;
    // a Zoo can have many Animals
    @Backlink
    ToMany<Animal> animals;
/*setters and getters*/
}
```

**Comment by greenrobot-team** [comment]
Since version `2.0.0` you can do something like:
```kotlin
val builder = box.query().equal(Zoo_.name, "The Big Zoo")
builder.link(Zoo_.animals).equal(Animal_.flying, true)
val flyingAnimals = builder.build().find()
```

This is called ["links" and there is documentation](https://docs.objectbox.io/queries#add-query-conditions-for-related-entities-links) on it with an additional example.

Closing. Please re-open if your question was not answered.
-ut

**Comment by zhanlv** [comment]
This approach doesn't work for me. Because in my application, there are several other applications (managed by other colleagues) that access the application's database through ContentProvider, maybe I should try GreenDao.
