### ISSUE TITLE
ToMany relations not automatically persisted when using put() on parent entity

### ISSUE THREAD

**Issue by herbeth1u** [objectbox/objectbox-java#525]
## Issue Basics
- ObjectBox version : 2.0.0
- Reproducibility: always

### Code
Let's suppose I have a parent entity called `Tag`, with 2 `ToMany` relations... : 
```kotlin
@Entity
class Tag() {
    @Id(assignable = true) var id: Long = 0
    lateinit var aliases: ToMany<TagAlias>
    lateinit var parents: ToMany<TagParent>

    constructor(...) : this() {
        id = ...

        boxStore.boxFor<Tag>().attach(this)
        aliases.add(TagAlias(2, "..."))
        aliases.add(TagAlias(3, "..."))
        parents.add(TagParent(4))
        parents.add(TagParent(5))
    }
}
```

...and 2 child entities : 
```kotlin
@Entity
data class TagAlias(
    @Id(assignable = true) var id: Long = 0,
    var alias: String = ""
)

@Entity
data class TagParent(
    @Id(assignable = true) var id: Long = 0
)
```

...and I want to save a list of tags with their aliases and their parents all at once : 
```kotlin
boxStore.boxFor<Tag>().put(listOf(Tag(...), Tag(...), ...))
```

### Description
The `Tag`s are properly saved, and I can retrieve them without problem.
However, the `TagAlias`s and `TagParent`s are not persisted automatically. Actually, both `TagAlias` and `TagParent` tables remain empty : `boxStore.boxFor<TagAlias>().all => []`.

The same problem seems to occur with `ToOne` relations too, as described by @eugenio1590 in https://github.com/objectbox/objectbox-java/issues/111#issuecomment-383974710 (I created a new issue for readability, as asked when the original issue was closed).

### Workaround
Adding a manual `put` for each `ToMany` relation fixes the problem... : 
```kotlin
@Entity
class Tag() {
     ...
    constructor(...) : this() {
        ...
        boxStore.boxFor<TagAlias>().put(aliases)
        boxStore.boxFor<TagParent>().put(parents)
    }
}
```

...but I'm not sure this is the intended behavior, if I believe [the documentation](https://docs.objectbox.io/relations#many-to-many-n-m)... : 
```java
Student student2 = new Student();
student2.teachers.add(teacher2);
​
// puts students and teachers
boxStore.boxFor(Student.class).put(student1, student2);
```
...`put` is not called for the teachers (child entity). Also, it is not very practical to call `put` recursively on every child entity, especially when child entities also have subchild entities.

Also, I have to wrap my parent's `put` into another transaction... : 
```kotlin
boxStore.runInTx {
    boxStore.boxFor<Tag>().put(listOf(Tag(...), Tag(...), ...))
}
```
...to keep my database consistent (if there is an error between two nested `put`) and also for performance's sake (so that there is only one parent transaction with one sync to the physical storage).

### Logs & stackstraces
No logs nor stacktraces for this issue. The code behaves like everything worked fine, though child entities are not actually persisted.

## Misc
In my example, the ids have to be assignable `@Id(assignable = true)` because all the objects come from the server. I don't know if this has anything to do with this issue though.

Thanks!

**Comment by greenrobot-team** [comment]
> In my example, the ids have to be assignable @Id(assignable = true) because all the objects come from the server. I don't know if this has anything to do with this issue though.

Yeap, that's it. See the [docs about self-assigned IDs](https://docs.objectbox.io/advanced/object-ids#self-assigned-object-ids). If you do, ObjectBox assumes you will take care of storing related entities. 

Only if the ID of a related entity is `0` ObjectBox will store a related entity and assign it an ID.
-ut

**Comment by arshcaptano** [comment]
I am facing the same exact issue while using the default object ID assignments.
