### ISSUE TITLE
About observer to get last object

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#530]
```java
    public Query<A> getChanged() {
        return ObjectBoxFactory
                .get(A.class)
                .query()
                .greater(A_.takeTime, System.currentTimeMillis())
                .order(A_.takeTime)
                .build();
    }
```
If I observer it,I can't get an object greater than now .Because time in greater is solid.
How can I get the last object whenever A changed.

**Comment by tvvbbb** [comment]
This is a good idea. I will try it. Thanks.

**Comment by tvvbbb** [comment]
Can I use  ```java query.publish() ``` to trigger observer？

**Comment by greenrobot-team** [comment]
@tvvbbb Yes, that should work.

Closing then. Please re-open if this will not work as expected.
-ut
