### ISSUE TITLE
how to add parentheses in a query?

### ISSUE THREAD

**Issue by jrcacd** [objectbox/objectbox-java#533]

**Comment by jrcacd** [comment]
Sorry to ask, but are you planning to implement this option? That's what we really miss.

**Comment by greenrobot-team** [comment]
@jrcacd A new query API is in preparation, but it's currently on hold. -ut

**Comment by RobbWatershed** [comment]
+1 here

**Comment by greenrobot-team** [comment]
@RobbWatershed 
Thanks for your enthusiasm. To voice your support (+1) thumbs up or heart the first comment instead.

Though feel free to leave a comment if you have something to share.

**Comment by greenrobot-team** [comment]
Oops, looks like this is much older.

Please thumbs up #201 instead.
-ut

**Comment by jrcacd** [comment]
> Please thumbs up #201 instead.
But that is about **_Creating queries with complex 'and' and 'or' combinations_**
Here we are asking for _**parentheses in a query**_

**Comment by greenrobot-team** [comment]
@jrcacd In what way is what the first comment in #201 suggests different? It also asks about adding support for nested conditions. -ut

**Comment by jrcacd** [comment]
Yes, you are right. I confused with another
