### ISSUE TITLE
How to make objectBox support ContentProvider?

### ISSUE THREAD

**Issue by zhanlv** [objectbox/objectbox-java#538]
How to make objectBox support ContentProvider? I want other applications to access the database.

**Comment by AminMemariani** [comment]
I think you don't need ContentProvider as long as your apps have the same Certificates.
Take a look at: [Certificates and keystores
](https://developer.android.com/studio/publish/app-signing#strategies)

**Comment by greenrobot-team** [comment]
@AminMemariani Thanks for the pointer.

And for `ContentProvider` in general: ObjectBox does not create `Cursor`, which is required for `ContentProvider`. It works with plain Java objects instead.

Closing. Please re-open if your question was not answered.
-ut

**Comment by zhanlv** [comment]
This approach doesn't work for me. Because in my application, there are several other applications (managed by other colleagues) that access the application's database through ContentProvider, maybe I should try GreenDao. @AminMemariani
