### ISSUE TITLE
Browser doesn't start

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [objectbox/objectbox-java#543]
I am using Kotlin and I am trying to start the browser.

With this `AndroidObjectBrowser(ObjectBox.boxStore).start(this)` nothing happens

With this: 
```
        ObjectBox.build(this)
        val boxStore = MyObjectBox.builder().androidContext(this).build()
        if (BuildConfig.DEBUG) {
            val started = AndroidObjectBrowser(boxStore).start(this)
            Log.i("ObjectBrowser", "Started: $started")
        }
```
I got this:  `Another BoxStore is still open for this directory: ...`

if I remove `ObjectBox.build(this)`, I haven't that error, but nothing happens

UPDATE:

```
        val objectBox = ObjectBox
        objectBox.build(this)
        if (BuildConfig.DEBUG) {
            val started = AndroidObjectBrowser(objectBox.boxStore).start(this)
            Log.i("ObjectBrowser", "Started: $started")
        }
```
This at least show `I/ObjectBrowser: Started: false`

**Comment by egll-tech** [comment]
Did you solved this issue? I am having the same problem
