### ISSUE TITLE
Data Browser no data to display

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#545]
I can query data with code. But Data Browser is no data to display. It makes me hard to debug.

**Comment by greenrobot-team** [comment]
Are you using the latest version `2.1.0`?

If yes, does the browser output any error message? Also see your browser's console (for example hit F12 in Chrome) for error output.
-ut

**Comment by tvvbbb** [comment]
No，I am using 2.0.0-beta. Now it can work.

**Comment by greenrobot-team** [comment]
Alright, closing then. Please re-open if this issue persists with version `2.1.0`. -ut

**Comment by tvvbbb** [comment]
Thanks.
