### ISSUE TITLE
This call is not supported on sub query builders (links) 

### ISSUE THREAD

**Issue by suda911** [objectbox/objectbox-java#549]
I wrote a test project that would use the LINK and create two models : Person and Address

```
@Entity
public class Person {
    @Id long id;
    String name;
    ToMany<Address> addresses;

    public Person() {}

    public Person(String name) {this.name = name;}

    public Person(long id, String name, ToMany<Address> addresses) {
        this.id = id;
        this.name = name;
        this.addresses = addresses;
    }
}
```

    

```
@Entity
public class Address {

    @Id long id;
    String street;

    public Address() {
    }

    public Address(String street) {this.street = street;}

    public Address(long id, String street) {
        this.id = id;
        this.street = street;
    }
}
```

Next, i wrote in my activity 

` Box<Person> personBox = MyApp.getBoxStore().boxFor(Person.class);`

Add data 

```
Address addressSesam = new Address("Sesam");
Address addressWessex = new Address("Wessex");

Person elmo = new Person("Elmo");
elmo.getAddresses().add(addressSesam);

Person elmoWessex = new Person("Elmo");
elmo.getAddresses().add(addressWessex);

personBox.put(elmo, elmoWessex);
```

And i want  get all Person objects named "Elmo"...which have an address on "Sesame Street"..

`List<Address> result= personBox.query().equal(Person_.name, "Elmo").
                link(Person_.addresses).equal(Address_.street, "Sesam").build().find();`

but crash occurs

java.lang.IllegalStateException: This call is not supported on sub query builders (links)

**Comment by greenrobot-team** [comment]
After calling `link()` you get a new `QueryBuilder` that is just for configuring the Link-Query. It can not actually return results, that is why calling `build()` on it will fail.

In short you should do this:
```java
QueryBuilder<Address> builder = personBox.query().equal(Person_.name, "Elmo");
builder.link(Person_.addresses).equal(Address_.street, "Sesam");
List<Address> result = builder.build().find();
```
-ut

**Comment by suda911** [comment]
Yes, it works! Thanks for the help!

**Comment by suda911** [comment]
Can I use the link for ToOne?

**Comment by suda911** [comment]
I wrote next models..

````
@Entity
public class Incident {

    @Id(assignable = true)
    long id;

    private long date;
    
    private ToOne<Acre> acre
}



@Entity
public class Acre {
    @Id(assignable = true)
    long id;
    private long date;

    public Acre() {
    }
````

And request ->

 ``` 
QueryBuilder<Incident> builder = incidentBox.query();
builder.link(Incident_.acre).equal(Acre_.date, 1L); // for example
List<Incident> result = builder.build().find();  
```
if I try to run, then crashes
`  java.lang.IllegalArgumentException: Relation not part of Entity Incident (2)`

**Comment by greenrobot-team** [comment]
@suda911 This is a separate issue that was uncovered as part of #537. This [will be fixed with the next update](https://github.com/objectbox/objectbox-java/issues/537#issuecomment-416600178).

Until the next update is available explicitly add the target ID property for the `ToOne`:
```
@Entity
public class Incident {
    ...
    long acreId;
    ToOne<Acre> acre
}
```
-ut

**Comment by suda911** [comment]
Thanks!

**Comment by Daimhim** [comment]
https://github.com/objectbox/objectbox-java/issues/549#issuecomment-418268003

QueryBuilder<Person> builder = personBox.query();
builder.link(Person_.addresses);
List<Person> result = builder.build().find();

ToMany<Address> addresses  

result addresses no data，Why？

**Comment by greenrobot-team** [comment]
@Daimhim Have a look at https://docs.objectbox.io/queries#add-query-conditions-for-related-entities-links to learn about link/backlink queries. If you believe to have found a bug, please create a new issue and supply the necessary details.
