### ISSUE TITLE
add new some entity  then run App  throw  io.objectbox.exception.DbException 

### ISSUE THREAD

**Issue by zlmkaka** [objectbox/objectbox-java#551]
i use  the ObjectBox version 1.4.0

when  add some  new entity  then  make project  is ok , but run app  throw  io.objectbox.exception.DbException  ;   only  uninstall  the   old  app   the can  run success ；
lose old data ;

what version can  fix  this  bug?

**Comment by greenrobot-team** [comment]
Can you please post the full exception message around `io.objectbox.exception.DbException`? Otherwise it's hard to tell what is going wrong.
-ut

**Comment by zlmkaka** [comment]
io.objectbox.exception.DbException: Incoming entity ID 1:3068397528464424630 does not match existing UID 8595104290307969439 
i  know  it  is   json file   VCS  error   ， but  lose  old  data  ,   i  want   keep the  old data

**Comment by greenrobot-team** [comment]
Did you delete your model file (typically `objectbox-models/default.json`) and it was regenerated afterwards? Check the history of your model file to restore its previous state.

To learn more about [UIDs and how to rename entities or properties](https://docs.objectbox.io/advanced/data-model-updates) check out the docs.
-ut

**Comment by zlmkaka** [comment]
yep i  delete the default.json,mybe i need learn more  , i will read the docs ;   thy  your team .

**Comment by greenrobot-team** [comment]
OK, closing this then. -ut

**Comment by Joslyn-Chen** [comment]
@greenrobot-team Hello, I have encountered the same problem, but my original file(default.json) could not be found. How can I solve it?

**Comment by greenrobot-team** [comment]
@Joslyn-Chen You can try to replace the UIDs in your `default.json` from the values given by the error messages. But this will only get you so far.

Make sure to check your `default.json` file into version control!
-ut
