### ISSUE TITLE
How to open Store？

### ISSUE THREAD

**Issue by njzy63lys** [objectbox/objectbox-java#556]
My app need clear table. but  i not fount method. so i used deleteAllFiles.
then  BoxStore  close = true. so  equal crash  java.lang.IllegalStateException: Store is closed.

How to open Store？

**Comment by greenrobot-team** [comment]
To clear a box (ObjectBox does not use "tables") do `box.removeAll()`.

And: After you use `BoxStore.deleteAllFiles()` you have to set up your `BoxStore` again using `MyObjectBox.builder()`.

Closing. Please re-open if your question was not answered.
-ut

**Comment by njzy63lys** [comment]
@greenrobot-team  
do  box.removeAll()  but id no begin 1
And: use application  public method     MyObjectBox.builder().  crash java.lang.IllegalStateException: Store is closed.   No kill app.But kill app  then  no crash.

**Comment by greenrobot-team** [comment]
There must be some error in your code logic then which closes the `BoxStore` right after it is built. We use this flow [in our tests regularly](https://github.com/objectbox/objectbox-examples/blob/master/objectbox-example/src/test/java/io/objectbox/example/AbstractObjectBoxTest.java).

It would help if you provide a small example and the full stack trace of that exception.
-ut

**Comment by njzy63lys** [comment]
@greenrobot-team 
this is my project  AppLication.java 

```
onCreate(){
 mBoxStore = MyObjectBox.builder().androidContext(this).directory(new File(AldeloConfig.RELEASEDB_DIR)).build();
}

//deleteTable method
  public void clearDB() {
        if (!mBoxStore.isClosed()){
            mBoxStore.close();
        }
        BoxStore.deleteAllFiles(new File(AldeloConfig.RELEASEDB_DIR));
        mBoxStore = MyObjectBox.builder().androidContext(this).directory(new File(AldeloConfig.RELEASEDB_DIR)).build();
    }

```
I have a  button click call clearDB()
