### ISSUE TITLE
There is no truncate method to reset id counter

### ISSUE THREAD

**Issue by avcial** [objectbox/objectbox-java#557]
Is there a way to reset id counter for tables, like truncate in tsql.
box.removeAll not work for this.

**Comment by greenrobot-team** [comment]
This was answered in #297. TL;DR: you can't reset the counter. Currently you can either 
- use [self-assigned IDs](https://docs.objectbox.io/advanced/object-ids#self-assigned-object-ids) or 
- delete the database file using `BoxStore.deleteAllFiles()` to start over.

-ut
