### ISSUE TITLE
A feedback about the Make Project

### ISSUE THREAD

**Issue by GreenhairTurtle** [objectbox/objectbox-java#567]
First forgive my bad English, I will try to describe my problem as much as possible.

When I use DataBinding And ObjectBox，then when using @Uid annotation to modify the variable name, both databinding and objectBox will report an error.

```Java
public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    ActivityMainBinding binding = DataBindingUtil.
        inflate(getLayoutInflater(),R.layout.activity_main,null,false);
  }
}

@Entity
public class Order {
  @Id
  private long id;
  @Uid
  private String uid;

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getUid() {
    return uid == null ? "" : uid;
  }

  public void setUid(String uid) {
    this.uid = uid;
  }
}
```

the error
```
ID model file changed: default.json, creating backup (.bak)
D:\AndroidStudioProjects\TestBug\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\borsam\testbug\databinding\ActivityMainBinding.java:3: 错误: 找不到符号
import android.databinding.DataBindingComponent;
                          ^
  符号:   类 DataBindingComponent
  位置: 程序包 android.databinding
D:\AndroidStudioProjects\TestBug\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\borsam\testbug\databinding\ActivityMainBinding.java:13: 错误: 找不到符号
  protected ActivityMainBinding(DataBindingComponent _bindingComponent, View _root,
                                ^
  符号:   类 DataBindingComponent
  位置: 类 ActivityMainBinding
D:\AndroidStudioProjects\TestBug\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\borsam\testbug\databinding\ActivityMainBinding.java:26: 错误: 找不到符号
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
                                                                ^
  符号:   类 DataBindingComponent
  位置: 类 ActivityMainBinding
D:\AndroidStudioProjects\TestBug\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\borsam\testbug\databinding\ActivityMainBinding.java:37: 错误: 找不到符号
      @Nullable DataBindingComponent component) {
                ^
  符号:   类 DataBindingComponent
  位置: 类 ActivityMainBinding
D:\AndroidStudioProjects\TestBug\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\borsam\testbug\databinding\ActivityMainBinding.java:46: 错误: 找不到符号
      @Nullable DataBindingComponent component) {
                ^
  符号:   类 DataBindingComponent
  位置: 类 ActivityMainBinding
注: [ObjectBox] Starting ObjectBox processor (debug: false)
错误: [ObjectBox] UID operations for property "Order.uid": [Rename] apply the current UID using @Uid(7505429871119459278L) - [Change/reset] apply a new UID using @Uid(4750760082689449888L)
6 个错误
```

When I changed the uid, it was normal.

In many cases, there are hundreds of Databinding errors before seeing the objectBox error, and android studio seems to only show the top 100, which caused me to be confused at the beginning.

So I want to ask, is this normal?

If this is normal, add the following code under project/build.gradle to see more errors and then we can change uid successfully

```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xmaxerrs" << "1000"
        }
    }
    repositories {
        google()
        jcenter()
    }
}
```

Finally, thank you!

**Comment by weixinzhi003** [comment]
i have the same problem

**Comment by GreenhairTurtle** [comment]
> i have the same problem

This should be a predictable issue, and it does not affect the use。
It’s just an annoyance when I first meet.

I think if the objectbox can put the error in the first one, it would be fine.

**Comment by weixinzhi003** [comment]
> > i have the same problem
> 
> This should be a predictable issue, and it does not affect the use。
> It’s just an annoyance when I first meet.
> 
> I think if the objectbox can put the error in the first one, it would be fine.

不影响使用吗？报的都是databinding的错误，那你是怎么获取到ObjectBox升级时的uid值呢

**Comment by GreenhairTurtle** [comment]
@weixinzhi003 
在Project的build.gradle下加入下面代码即可
```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xmaxerrs" << "1000"
        }
    }
    repositories {
        google()
        jcenter()
    }
}
````

这样可以输出1000条错误

emmmm，我主楼应该写了呀

**Comment by greenrobot-team** [comment]
Yes, the error is [expected when adding the `@Uid` annotation](https://docs.objectbox.io/advanced/data-model-updates#how-to-and-example).

Regarding the Databinding errors I'm not sure there is anything we can do so the ObjectBox error is shown first.

Workaround: Assuming you want to rename the property, you can look up the UID yourself in the `objectbox-models\default.json` file and immediately add `@Uid(<uid>)` instead of just `@Uid`. This will avoid the error message.

Closing as won't fix as I'm not sure what we could improve here.
-ut

**Comment by weixinzhi003** [comment]
> gradle.projectsEvaluated { tasks.withType(JavaCompile) { options.compilerArgs << "-Xmaxerrs" << "1000" } }

谢谢。一开始只看了前面，没有仔细看后面那部分
