### ISSUE TITLE
The query result is not 0 after all the data is deleted.

### ISSUE THREAD

**Issue by wb1992321** [objectbox/objectbox-java#575]
The query result is not 0 after all the data is deleted.
### remove
```
App.instance().getBox().boxFor(TagObj.class)
                                .removeByKeys(list);
```

### query

```
App.instance().getBox().boxFor(TagObj.class)
                    .query().build().count()
```

**Comment by greenrobot-team** [comment]
Are you sure `list` has all keys? Try `Box.removeAll()` instead.
-ut

**Comment by wb1992321** [comment]
@greenrobot-team Of course

**Comment by Yazon2006** [comment]
@wb1992321 Code example will clarify the case. Can you share simple project to reproduce the case?

**Comment by greenrobot-team** [comment]
No response, closing. Please re-open with more details or submit a new issue.
-ut
