### ISSUE TITLE
ObjectBoxLiveData and testing

### ISSUE THREAD

**Issue by casadogg** [objectbox/objectbox-java#581]
How would one go about testing ObjectBoxLiveData? I thought about creating a ObjectBoxTestLiveData or something like that, where internally the query is executed using `query.find()` instead of a `DataSubscription`.

**Comment by greenrobot-team** [comment]
What @abdurahmanadilovic said. A quick Google search delivers a lot of results on how to test `LiveData` and architecture components in general. You obviously have to set up the underlying database first, but that's the same as with a Room LiveData.

Maybe you can also find some inspiration in [the sample code Google provides for LiveData](https://developer.android.com/topic/libraries/architecture/livedata#additional-resources).

Closing as out of scope (programming question).
-ut
