### ISSUE TITLE
A method for Box to get its size in KBytes

### ISSUE THREAD

**Issue by minstrelsy** [objectbox/objectbox-java#585]
Hi,

Is it possible to have a new method for `Box` which could tell how much KBytes it is using now?

Since entities could not be removed after `DbFullException` been thrown, this new method could be a good way to predict that DB would soon be full in order to remove some entities before `DbFullException` happens.

**Comment by greenrobot-team** [comment]
Now tracked with #826

Note that `2.7.0` now has `BoxStore.sizeOnDisk()`.
