### ISSUE TITLE
How can I update some properties but not replace the entity object in the box?

### ISSUE THREAD

**Issue by JTforyuan** [objectbox/objectbox-java#590]
I want to update several properties. But if i put the entity object which had the same id into the box, it will replace all the properties .So i get the entity object first and then i put it into the box. Do I have to get the entity object first? Is there any way I can update only several properties and don't need to get the entity object  first?

**Comment by abdurahmanadilovic** [comment]
I don't think so, I think you need to query by Id then you perform updates on the model you got from the DB, then you can call save on that model, that will save to DB the changes you have and keep other properties unchanged. 

Do you have a use case where you need to update properties on a DB model without fetching it from the DB first?

P.S. When I use DB I mean ObjectBox.

**Comment by greenrobot-team** [comment]
What @abdurahmanadilovic said.

Closing. Feel free to re-open if you can find a use case where the current approach does not work for you.
-ut
