### ISSUE TITLE
ToMany can't update items to DB.

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#593]
objects1.get(0).getItems().get(0).getAge()  not equal 4 and Name is not equal "5"
```java
TestObjectItem item = new TestObjectItem();
        item.setAge(1);
        item.setName("a");

        TestObjectItem item1 = new TestObjectItem();
        item1.setAge(2);
        item1.setName("2");

        TestObjectItem item2 = new TestObjectItem();
        item2.setAge(3);
        item2.setName("3");

        List<TestObjectItem> items = new ArrayList<>();
        items.add(item);
        items.add(item1);
        items.add(item2);

        TestObject testObject = new TestObject();
        testObject.setItems(items);

        Box<TestObject> testObjectBox = ((BaseApplication) getApplication()).getBoxStore().boxFor(TestObject.class);
        testObjectBox.removeAll();
        testObjectBox.put(testObject);

        List<TestObject> objects = testObjectBox.getAll();

        for (TestObject object : objects) {
            object.getItems().get(0).setAge(4);
            object.getItems().get(0).setName("5");
        }

        objects.get(0).getItems().remove(1);
        testObjectBox.put(objects);

        List<TestObject> objects1 = testObjectBox.query().build().find();


        
```

```java
@Entity
public class TestObject {

    @Id
    long id;

    @Backlink(to = "testObject")
    ToMany<TestObjectItem> items;

    public List<TestObjectItem> getItems() {
        return items;
    }

    public void setItems(List<TestObjectItem> items) {
        this.items.addAll(items);
    }
}

```

```java
@Entity
public class TestObjectItem {

    @Id
    long id;

    String name;

    int age;

    ToOne<TestObject> testObject;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}

```

**Comment by greenrobot-team** [comment]
`ToMany` only tracks adds or removes, but not changes to the properties for existing related entities. So instead of
  
`testObjectBox.put(objects);` 

you should do 

`testObjectItemBox.put(object.getItems().get(0))`

for each changed `TestObjectItem`.

This is a little confusing, because `ToMany` actually will put a related entity **if it is new**. But it won't if the related entity already exists.
-ut

**Comment by tvvbbb** [comment]
I think this can improve. I don't know which items have changed. So I must use for/each to put each item. This is wasting time. You can imagine if I put List then I should  
 testObjectBox.put(objects);
 and 
 for(Object object : objects){
     testObjectItemBox.put(object.getItems().get(0))
}

**Comment by greenrobot-team** [comment]
`testObjectItemBox.put(object.getItems())` should also work and is probably a lot faster. You then only need to keep a list of the ones to remove, then call `testObjectItemBox.remove(itemsToRemove)`.
-ut

**Comment by tvvbbb** [comment]
I get a list from the server, so I can't keep a list of the ones to remove.

**Comment by greenrobot-team** [comment]
I don't follow. If you have the ID you can remove an entity. Not sure what we can do here.
-ut

**Comment by tvvbbb** [comment]
I am sorry for my poor English.
