### ISSUE TITLE
entity Inheritance from other module can not persist  super classes's properties 

### ISSUE THREAD

**Issue by liucy2007975** [objectbox/objectbox-java#611]
## Issue Basics
- ObjectBox version  V1.5.0
- Reproducibility:  always
### 
* App have maney modules ,  entity extends super classes which in other module , the super class have annotationed with @BaseEntity, rebulid the project ,then only persisted properties without super classes's properties , but in the same module ,they can persist all properties . 
please tell me how to fix that, thanks!

**Comment by greenrobot-team** [comment]
This is a known [restriction of entity inheritance](https://docs.objectbox.io/advanced/entity-inheritance#restrictions). Nothing to do here. -ut
