### ISSUE TITLE
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)

### ISSUE THREAD

**Issue by ivanooi** [objectbox/objectbox-java#639]
I'm having this message when I run the code. Any ideas? 

[WARN ] Skipped low-level close of cursor (write, TX #4 alive)

here are the simple loop : 

        ArrayList<user3in1_data> map = new ArrayList<user3in1_data>();

        for( int i = 0 ; i < 1000 ; i ++ ){

            user = new user_data();

            user.user_code = "abc" + i;
            user.area = "TX";

            map.add(user);
        }
        box.put(map);

**Comment by ivanooi** [comment]
> Task :Main.main()
[WARN ] Skipped low-level close of cursor (write, TX #3 alive)
[WARN ] Skipped low-level close of cursor (write, TX #3 alive)
[WARN ] Skipped low-level close of cursor (write, TX #3 alive)
[WARN ] Skipped low-level close of cursor (write, TX #3 alive)
[WARN ] Skipped low-level close of cursor (write, TX #3 alive)
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)
1000 notes in ObjectBox database:
[WARN ] Skipped low-level close of cursor (write, TX #4 alive)

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 executed
23:54:30: Task execution finished 'Main.main()'.

**Comment by greenrobot-team** [comment]
Thanks, we are already aware of this: #196
