### ISSUE TITLE
ZERO WIDTH SPACE in the docs

### ISSUE THREAD

**Issue by Grohden** [objectbox/objectbox-java#642]
Ok, i'm not following the issue template cuz this is kind of a doc issue. 

There's a weird char at the docs, specifically [this page here](https://docs.objectbox.io/advanced/custom-types), at the second example, on line break (line 18 - and probably others) there is this char "​" (believe, it's in the quotes), the code is 8203 and it's the zero width space. I lost some time to found out that the "Expecting member declaration" error was about that... hehe

Is that intentional ​​​​🤔​​​?

**Comment by greenrobot-team** [comment]
Thanks for reporting. This seems to be an issue with GitBook which places them on empty lines. Also passed this on to them.

Workaround 1: copy the code using the small copy button in the top right.
Workaround 2: replace empty lines with at least 1 space.

-ut

**Comment by greenrobot-team** [comment]
Added at least one space wherever I could find an empty line. But this is fragile (I doubt we or even I will always remember to add a space on an empty line...). Let's hope GitBook fixes this.
-ut

**Comment by greenrobot-team** [comment]
GitBook did deploy a fix on the 18th.

Removed spaces where it makes sense, some were actually missing from before (indentation).

Copying manually or via the copy button now includes no invisible characters.

@Grohden Thanks again for reporting!
-ut
