### ISSUE TITLE
ToOne.target and ToOne.getTarget in kotlin

### ISSUE THREAD

**Issue by worldsnas** [objectbox/objectbox-java#649]
## Issue Basics
- ObjectBox version 2.3.1
- Reproducibility: occasionally without visible pattern
- Platform: Android
- Language: Kotlin

### Description
We have a entity called A and another entity called B. there is a OneToMany Relation between them.
so it's like: A has only one B but every B has lots of As.
every thing is fine with the database when we insert and get. but in kotlin when we use A.b.target (as suggested by IDE it returns null. becuase mysteriously calles the variable inside ToOne class directly which is empty at first (lazily loaded). but when we change it to A.b.getTarget() (despite the IDE highlight) everything is working fine and good agian. at first I thought target variable is not private but when i check it seems it's private and I have no idea how it is actually using the variable.

### Code
```
@Entity
data class A(
        @Id(assignable = true)
        val id: Long
) {
    lateinit var b: ToOne<B>
}
@Entity
data class B(
        @Id(assignable = true)
        val id: Long
) {
    @Backlink(to = "b")
    lateinit var b: ToMany<A>
}
```

```
a.b.target == null
a.b.getTarget() == b
```

**Comment by greenrobot-team** [comment]
First, it should be `var id: Long = 0` or this won't compile.

Quickly tried this and working as expected. Does this happen for the same instance of `a`?

As the example is using `@Id(assignable = true)` there may be another cause where your related entities might not get put as expected if they are put with `id != 0`.
https://docs.objectbox.io/relations#updating-relations

-ut

**Comment by worldsnas** [comment]
that val is my mistake in the example and it was correct in the project (thank you for the heads up)
I don't actually think it's instance related.
all my Id's are assignable and at I make sure that I use attach or put before adding the entity.
when I use ObjectboxBrowser and check for the entities they are actually have been inserted even when bBox is used to retrieve all Bs I can confirm that they have been inserted. 
the only thing is when I use `target` instead of `getTarget()` in kotlin keeps returning null.

 if I could come up with the pattern it actually happens, I'll try to prepare a sample demonstrating this issue.

**Comment by greenrobot-team** [comment]
> I'll try to prepare a sample demonstrating this issue

That would be tremendously helpful, thanks.
-ut

**Comment by worldsnas** [comment]
Hey, all again.
sorry for the late reply. the issue is still there but since I could not reproduce it as a sample yet I'm going to close this Issue and reopen it when I have a sample at hand.
thank you all
