### ISSUE TITLE
Box store stops working with error "Could not put (1) (error code 1)"

### ISSUE THREAD

**Issue by datacode-taavi** [objectbox/objectbox-java#651]
## Issue Basics
- ObjectBox version : 2.2.0
- Reproducibility: occasionally without visible pattern

### Description
We have an application that gradually imports data from the backend server and inserts it to the database with about 3000 objects per transaction. The total object count is about 2 million objects. On most of the devices, this is not a problem and everything works correctly. However on about 10% of the devices, the insert transactions start to fail with db exception "Could not put (1) (error code 1)". Retrying the transaction does not help as it fails with the same reason. Making select queries after this condition has occurred also fail with error message "Could not get from cursor (1) (error code 1)". After application restart the box store starts to work again.

### Code
Unfortunately I have not been able to reproduce this problem separately (only happens with real world application use).

However here is the pseudo code of what we do:

    List<Entity> entities;
    while (true) {
        entities = fetchEntitiesFromBackend();
    
        if (entities.size() == 0) {
            break;
        }
    
        boxStore.callInTx(() -> {
            boxStore.boxFor(Entity.class).put(entities);
            return null;
        });
    }

### Logs & stackstraces

```
01-29 04:20:29.626 5613-6995 E/Box Storage error code 1
01-29 04:20:29.627 5613-6995 E/Box Illegal state: Tx destroyed/inactive, writeable cursor still available
01-29 04:20:29.627 5613-6995 W/Box Skipped low-level close of cursor (write, TX #628 alive)
01-29 04:20:29.628 5613-6995 E/DataImporter Failed to run database transaction
01-29 04:20:29.628 5613-6995 E/DataImporter io.objectbox.exception.DbException: Could not put (1) (error code 1)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at io.objectbox.Cursor.collect313311(Native Method)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.e.EntityCursor.put(EntityCursor.java:146)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.e.EntityCursor.put(EntityCursor.java:19)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at io.objectbox.Box.put(Box.java:407)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.f.DataImporter.handleDbTransactions(DataImporter.java:843)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.e.DataImporter.runObjectboxTransaction(DataImporter.java:170)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.e.DataImporter.lambda$execute$1(DataImporter.java:94)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at a.b.c.d.e.DataImporter.-$$Lambda$DbTransaction$A_-xrsDVVglsf1Wt7WHSkU69-pI.call(lambda)
01-29 04:20:29.628 5613-6995 E/DataImporter 	at io.objectbox.BoxStore.callInTx(BoxStore.java:744)
```

boxStore.diagnose() responds with following output (called after the initial exception inside the db exception handler):
```
01-30 13:38:05.196  5032  5103 E DatabaseManager:       pid     thread     txnid
01-30 13:38:05.196  5032  5103 E DatabaseManager:       5032 51ad7930 2538
01-30 13:38:05.196  5032  5103 E DatabaseManager:       5032 da28930 -
01-30 13:38:05.196  5032  5103 E DatabaseManager:       5032 d175930 -
01-30 13:38:05.196  5032  5103 E DatabaseManager: 
01-30 13:38:05.196  5032  5103 E DatabaseManager: entries=4315641
01-30 13:38:05.196  5032  5103 E DatabaseManager: depth=4
01-30 13:38:05.196  5032  5103 E DatabaseManager: branch-pages=1642
01-30 13:38:05.196  5032  5103 E DatabaseManager: leaf-pages=186047
01-30 13:38:05.196  5032  5103 E DatabaseManager: overflow-pages=0
01-30 13:38:05.196  5032  5103 E DatabaseManager: page-size=4096
01-30 13:38:05.196  5032  5103 E DatabaseManager: last-page-number=196162
01-30 13:38:05.196  5032  5103 E DatabaseManager: last-tx-id=2538
01-30 13:38:05.196  5032  5103 E DatabaseManager: size=2147483648
01-30 13:38:05.196  5032  5103 E DatabaseManager: max-readers=126
01-30 13:38:05.196  5032  5103 E DatabaseManager: readers=3
```

## Entities
    @Entity
    public class Entity {
        @Id(assignable = true)
        private Long entityId;
        
        @Index
        @Convert(converter = ByteStringConverter.class, dbType = String.class)
        private ByteString byteStringId;

        private Integer intField;
        // other fields follow
    }

## Misc
The application is multithreaded and all inserts are done in a background thread. All inserts are done in one thread, however this thread is recycled every now and then. There are read-only queries being made from other threads. There are 3 different box stores in use in the same application, the other stores are very small and are not used often.

Only workaround to get the database working again is to restart the application. After application restart, both get and put queries start to work again and no other problems seem to exist.

The logs mention "Storage error code 1", which I have no idea what it means. There is nothing wrong with the device storage as all other threads have no problems with writing to the storage. Box store size is sufficient (total space reserved is 2GB for the whole store, only about 1G is used when 2 million objects have been inserted).

We also get a lot of "Skipped low-level close of cursor" type of log events, but as I understand this is not something critical, as it always happens if the entity has indexes.

**Comment by greenrobot-team** [comment]
Thanks for the very detailed report!

I could not find any conclusive info on error code 1, but it might be `EPERM /* Operation not permitted */`.

Can you share any more details about the affected devices? Maybe a certain Android version, manufacturer or model? Or the amount of total or free memory?

Will look into reproducing this.
-ut

**Comment by datacode-taavi** [comment]
Hi,

The devices are running Android 6.0.1 on custom hardware (the devices are basically headless devices without UI). Free memory on the devices at the time of the crashes is usually around 1.6GB (total memory available 2GB).

**Comment by datacode-taavi** [comment]
Looks like we can close this task, sorry for the trouble.

This does not seem be an Objectbox issue, but an Android issue (or particularly the 6.0 version we are using) as we started to notice similar behavior in other parts of the application (SQLite queries failed with "Cursor window allocation of 2048 kb failed.", creating new threads failed with "pthread_create (1040KB stack) failed: Try again"). All of these errors seem to have one underlying error and that is error code EPERM (operation not permitted) being thrown in some very low level code.

I still have no idea what is causing it, but the issue seems to disappear after upgrading to Android 7.1.1.

Thanks for the help!
