### ISSUE TITLE
Max() returns a big value on empty entity's

### ISSUE THREAD

**Issue by jrcacd** [objectbox/objectbox-java#661]
ObjectBox 2.3.3
Kotlin

One entity does not have records
If we do 
`query().build().property(Record_.typeLongField).max() `
on a long Field
it returns 
-9223372036854775808

**Comment by greenrobot-team** [comment]
`-9223372036854775808` is `Long.MIN_VALUE`, so this works as expected (the maximum is the lowest possible number if there are no values).

What would you have expected to get returned here?
-ut

**Comment by jrcacd** [comment]
> What would you have expected to get returned here?

The maximum inserted value in that field.

**Comment by greenrobot-team** [comment]
> One entity does not have records

Sorry, I misunderstood. I assumed there is only one entity overall.

So the Box has at least one entity where `typeLongField != null` and one entity where `typeLongField == null`?
-ut

**Comment by jrcacd** [comment]
> So the Box has at least one entity where `typeLongField != null` and one entity where `typeLongField == null`?

I did not understand your question.


The database has an **entity** called **Record**

That entity does not have records. Is empty.

When we do 

`query().build().property(Record_.typeLongField).max()`

We thought it will return 0.

And if it had record with values in that field such as:1, 5, 9, we thought it will return the greatest one (9 in the above example).
