### ISSUE TITLE
App's size increased by 4MB

### ISSUE THREAD

**Issue by Kashish-Sharma** [objectbox/objectbox-java#667]
- ObjectBox version : 2.3.3
- Reproducibility:  always

## Description
I migrated my app's database from Room to ObjectBox completely ( by using the getting started guide and some other basic info ), and app's size increased from 8MB to 12MB.
*I'm using ObjectBox with Paging library.*

Another question,
As earlier I was using Room database in my production app, to change anything in Room, we've to write complete migration code, but now I've completely shifted my app's Db to ObjectBox and have removed Room ( dependency and all ).
After updating the app, app's size increased from like 6MB to 20MB?

**Comment by greenrobot-team** [comment]
OK, sorry, you are just throwing random numbers around. Are we talking about APK size? Then investigate your APK by opening it in Android Studio and comparing it to the previous one.

Are we talking about database size? It increases depending on the number of objects you put in your BoxStore.
-ut

**Comment by Kashish-Sharma** [comment]
Hey!
Thanks for the reply.
APK size is just as expected.
But I don't know when using Room, installed app size on a particular device is around 8MB and with ObjectBox app's size is around 20MB.
APK size is great!

**Comment by EsteveAguilera** [comment]
I've also faced a huge apk size increase after updating from version 2.1.0 to 2.3.3

With version 2.1.0 APK size was 28.8MB
With version 2.3.3 APK size was 44.2MB

**Comment by Kashish-Sharma** [comment]
@EsteveAguilera for the APK size you can compare it with previous APK versions.
That'll give a more clear idea of what is bloating the APK.
I'm facing issues with the InstantHelp app size on same device with Room Android then with ObjectBox.

**Comment by EsteveAguilera** [comment]
@Kashish-Sharma I've already compared with previous APK versions, and found... well, nothing.
But I changed the library version and found that APK size restores to normal values...

**Comment by greenrobot-team** [comment]
@EsteveAguilera In Android Studio, make sure to use `Rebuild Project` (or `Clean Project` followed by `Make Project`, or `gradlew clean assemble`, ...). Possibly the old .so files were still getting packaged into the APK.

@Kashish-Sharma It largely depends on what data you are storing and how many indexes there are. You also might want to look at https://github.com/objectbox/objectbox-java/issues/552

-ut

**Comment by Kashish-Sharma** [comment]
@greenrobot-team  thanks a lot.
As I've shifted my app's database from Room to ObjectBox, users who updated their apps ( Earlier having Room and now ObjectBox ) have the app size of around 20MB. ( Earlier app size was 8MB )
And the users who have installed the fresh app have the app size of 12MB (great!).

Anyways ObjectBox works perfect and have made developing apps a lot easier.
Thanks for this awesome database!

**Comment by donglua** [comment]
#665

**Comment by Kashish-Sharma** [comment]
@donglua Thanks !!

**Comment by greenrobot-team** [comment]
Updated the FAQ.
https://docs.objectbox.io/faq#how-much-does-objectbox-add-to-my-apk-size

-Uwe
