### ISSUE TITLE
Apk size increased too much when upgrade to 2.3.0 from 2.2.0

### ISSUE THREAD

**Issue by GreenhairTurtle** [objectbox/objectbox-java#673]
## Issue Basics
- ObjectBox version: 2.3.0-2.3.3
- Reproducibility: always

### Description
Apk size increased too much.
Create a new project with Android Studio, implementation 2.2.0 and 2.3.0 respectively and generate signed apk to reproduce。

2.2.0 apk size
![2 2 0](https://user-images.githubusercontent.com/22109299/54339587-420de880-4670-11e9-92b7-0e169575949d.png)

2.3.0 apk size
![2 3 0](https://user-images.githubusercontent.com/22109299/54339584-3f12f800-4670-11e9-9b6b-02f125e37ce3.png)

and also has issue same with #638 

## Code
No code required
Just add this library

**Comment by donglua** [comment]
#665

**Comment by GreenhairTurtle** [comment]
Thanks too much

**Comment by greenrobot-team** [comment]
Updated the FAQ.
https://docs.objectbox.io/faq#how-much-does-objectbox-add-to-my-apk-size

-Uwe
