### ISSUE TITLE
Too many types of .so library for Android

### ISSUE THREAD

**Issue by chejdj** [objectbox/objectbox-java#674]
Hello, ObjectBox provides x86,x86-64,arm64-v8a,arm64-v7a but in fact I only need the arm64-v8a,arm64-v7a and the .so files are a little big, so I want to ask how to delete others?

**Comment by wangnanuestc** [comment]
It seems that objectbox-java only support x86 x64 platform

**Comment by greenrobot-team** [comment]
@chejdj You can add an ABI filter to your `build.gradle` file.
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.NdkOptions.html

@wangnanuestc On desktop operating systems, yes. You might want to join the discussion in #657.

-Uwe

**Comment by chejdj** [comment]
Thanks
