### ISSUE TITLE
RxQuery violates observable contract

### ISSUE THREAD

**Issue by MrSlateZB** [objectbox/objectbox-java#687]
The observable contract doesn't allow for concurrent calls of onNext/onComplete/or onError. ObjectBox subscriptions can come in on multiple threads concurrently if the database is changing rapidly enough. This would cause onNext to be called concurrently from multiple threads. 

Thankfully, the emitter from RxJava has a .serialize() method that you can use to make the emitter safe for this use case. This should fix the issue.

**Comment by greenrobot-team** [comment]
Thanks!

Verified this, quote from docs:
> Note that the onNext(T), onError(java.lang.Throwable) and onComplete() methods provided to the function via the Emitter instance should be called synchronously, never concurrently. Calling them from multiple threads is not supported and leads to an undefined behavior.
http://reactivex.io/RxJava/javadoc/io/reactivex/Emitter.html

Side note: `ObjectBoxLiveData` is safe as it uses `LiveData#postValue` which posts a task to the main thread.

For "regular" observers this is solved by passing a scheduler, e.g.:
```
query.subscribe(subscriptions)
     .on(AndroidScheduler.mainThread())
     .observer(data -> updateUi(data));
```

Side note: should update the query observers docs to always explicitly specify a scheduler.
https://docs.objectbox.io/data-observers-and-rx#observing-queries

-Uwe

**Comment by MrSlateZB** [comment]
If the serialized emitter fix isn't going to be implemented, I would just make it very clear that any multi-threaded scheduler would still recreate this problem.

**Comment by MrSlateZB** [comment]
In https://github.com/objectbox/objectbox-java/issues/793 emissions seem to now be synchronized onto a single thread. Because of this, the observable contract shouldn't be violated anymore.
