### ISSUE TITLE
How to achieve deduplication effect (Original: 如何实现 去除重复数据效果)

### ISSUE THREAD

**Issue by xyb789** [objectbox/objectbox-java#689]
When the data is saved repeatedly, the data will be repeated. When it is saved, the data id is replaced or the effect of removing the duplicate data is achieved.

Original:
重复保存时 数据会重复  如何存的时候判断  把数据id替换
  或者达到去除重复数据的效果

**Comment by greenrobot-team** [comment]
@xyb789 If I understand this correctly: to update an object, make sure to get it (or at least its id) first. Then change properties, then put it again:

User user = new User();
user.setName("Tammy");
// user.id == 0, new user is created
box.put(user);
// user.id != 0, user is updated
user.setName("Tammy2");
box.put(user);

https://docs.objectbox.io/getting-started#object-ids

-Uwe

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
