### ISSUE TITLE
Class conflict with flatbuffers dependency

### ISSUE THREAD

**Issue by luoyexk** [objectbox/objectbox-java#690]
latest version
+--- project :module_mobile
|    +--- project :lib_common
|    |    +--- io.objectbox:objectbox-kotlin:2.3.4
|    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21
|    |    |    |    \--- org.jetbrains:annotations:13.0
|    |    |    \--- io.objectbox:objectbox-java:2.3.4
|    |    |         +--- io.objectbox:objectbox-java-api:2.3.4
|    |    |         +--- org.greenrobot:essentials:3.0.0-RC1
|    |    |         +--- **com.google.flatbuffers:flatbuffers-java:1.9.0**
|    |    |         \--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- io.objectbox:objectbox-android:2.3.4
|    |    |    \--- io.objectbox:objectbox-java:2.3.4 (*)

google arcore lib use flatbuffers, your package name are same, this make conflict

![google_sceneform](https://user-images.githubusercontent.com/20855787/55768259-c3f60380-5aae-11e9-9cc5-61ccb56514a3.png)

**Comment by luoyexk** [comment]
![conflict](https://user-images.githubusercontent.com/20855787/55940623-13852c80-5c73-11e9-9ad2-dbe9da10fde1.png)

how can I merge them?

`
package io.objectbox.model;
import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
@SuppressWarnings("unused")
/**
 * A model describes all entities and other meta data.
 * The current model of an app is synced against ObjectBox's persisted schema.
 * The model itself is not persisted, and thus may change as long as both ends are consistent (Java and native).
 * There could be multiple models/schemas (one dbi per schema) in the future.
 */
public final class Model extends Table{}
`

**Comment by greenrobot-team** [comment]
1. Apply the ObjectBox plugin after the dependencies block:
```
dependencies {
...
}
apply plugin: 'io.objectbox'
```

2. Manually include `objectbox-java` and exclude its flatbuffers dependency:
```
implementation("io.objectbox:objectbox-java:$objectboxVersion") {
    exclude group: 'com.google.flatbuffers', module: 'flatbuffers-java'
}
```
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies

-Uwe

**Comment by greenrobot-team** [comment]
Since `2.6.0` the `objectbox-java` library no longer leaks the FlatBuffers dependency, making the above workaround superfluous.
