### ISSUE TITLE
Objectbox migration feature

### ISSUE THREAD

**Issue by sonhvp** [objectbox/objectbox-java#691]
In the future, will ObjectBox have more features to control migration? Currently, ObjectBox manages its data model (schema) mostly automatically, it's great, really love it but sometimes, we need more control. Will some methods to destroy the database and init with new default.json when migrating will be available? Or when changing property types, will there anyways to implement convert logic from old data? Currently, it seems like data will loss when changing.
```kotlin
// old data:
String dateTime;  //ex: 2019-04-14T05:55:23Z

// new data (will there anyways to implement convert logic?)
Long millis;

**Comment by greenrobot-team** [comment]
In the example you suggested, e.g. changing the type of a property, you would have to write migration logic yourself anyhow. I don't see how this could be avoided.

ObjectBox supports renaming without data loss.
https://docs.objectbox.io/advanced/data-model-updates#renaming-entities-and-properties

As for nuking and starting with a fresh database: you could delete your `default.json`. Then before using the `MyObjectBox` builder do a one-time deletion of the database files using `BoxStore.deleteAllFiles(directory)`.
http://objectbox.io/files/objectbox-java/current/io/objectbox/BoxStore.html#deleteAllFiles-java.io.File-
-Uwe
