### ISSUE TITLE
In entity {XXX}, no property with UID {xxxxx} found

### ISSUE THREAD

**Issue by liyzay** [objectbox/objectbox-java#692]
*Before creating a new issue, make sure that you checked: (1) existing issues, (2) docs (3) FAQ.
TEMPLATE FOR ISSUES ONLY - for feature requests just delete the text and start fresh.
Please help us to fix issues asap: this template reduces checking with you back and forth.
Replace italic sections with your input.
For __support questions__, please use [stackoverflow with the [objectbox] tag](https://stackoverflow.com/questions/tagged/objectbox) - we get notified.*

## Issue Basics
- ObjectBox version (are using the latest version?): *Yes(2.3.4)*
- Reproducibility: *always*

### Description
I have __two properties__(Lets say `startTime` and `endTime`) I want to change type from String to long,So I followed the doc [https://docs.objectbox.io/advanced/data-model-updates](https://docs.objectbox.io/advanced/data-model-updates) by adding `@Uid` on those properties
The first time I build my project I got: 

> [ObjectBox] UID operations for property "Order.startTime": [Rename] apply the current UID using @Uid(3248566047441574246L) - [Change/reset] apply a new UID using @Uid(5206624569070640164L)

So I added `@Uid(5206624569070640164L)` on `startTime`.
The second time I build my project I got: 

> [ObjectBox] UID operations for property "Order.endTime": [Rename] apply the current UID using @Uid(5990312914043167764L) - [Change/reset] apply a new UID using @Uid(6233827831574489486L)

And I added `@Uid(6233827831574489486L)` on `endTime`.
The third time I build my project I got: 

> [ObjectBox] Could not sync parsed model with ID model file "D:\xxxxxx\objectbox-models\default.json": In entity Order, no property with UID 5206624569070640164 found

We can see the missing UID is the first time added UID.
I aslo check my `objectbox-models\default.json` and I found there only one item in `newUidPool`.
![20190417134050](https://user-images.githubusercontent.com/716739/56263724-aa8c3180-6116-11e9-9442-98a9c8c7722f.png)
Maybe there should be two item in `newUidPool`?

**Comment by liyzay** [comment]
I barely fixed this bug by adding a item with the missing UID in the `newUidPool` of my `objectbox-models\default.json`.
![20190417135108](https://user-images.githubusercontent.com/716739/56264288-92b5ad00-6118-11e9-83fc-5546f1079457.png)
And the new generated `objectbox-models\default.json` are like
![20190417135157](https://user-images.githubusercontent.com/716739/56264320-afea7b80-6118-11e9-9f43-1862c3d810cf.png)
From which we can see the old UID are retired. ^_^!

**Comment by liyzay** [comment]
Solution 2:**Add only one `@Uid` on a property at a time when you build your project**.
This means if you have 5 properties you want to change ,you will have to do this 5 times.

**Comment by greenrobot-team** [comment]
@liyzay Thanks for reporting. Yeah, we probably should make it more clear that you have to do it property by property.

Task for me:
- [ ] Look into code if assigning new UIDs could work for multiple properties at a time, if not update docs as suggested above.

-Uwe

**Comment by greenrobot-team** [comment]
Updated the docs about making changes one-by-one, or in case or renaming, to get the UIDs directly from model.json which might be faster.
https://docs.objectbox.io/advanced/data-model-updates
