### ISSUE TITLE
All the .so file was not found in nativeLibraryDir

### ISSUE THREAD

**Issue by liyzay** [objectbox/objectbox-java#705]
*Before creating a new issue, make sure that you checked: (1) existing issues, (2) docs (3) FAQ.
TEMPLATE FOR ISSUES ONLY - for feature requests just delete the text and start fresh.
Please help us to fix issues asap: this template reduces checking with you back and forth.
Replace italic sections with your input.
For __support questions__, please use [stackoverflow with the [objectbox] tag](https://stackoverflow.com/questions/tagged/objectbox) - we get notified.*

## Issue Basics
- ObjectBox version (yes): *2.3.4*
- Reproducibility: *[always]*

### Description
*All my .so file(not just objectbox .so) was not found in the nativeLibraryDir(Android 8.0) after update objectbox from 2.2.0 to 2.3.4,which **did not** cause my app to crash but the other lib does not work now.*
Here is the code to check files under nativeLibraryDir:
![20190512202615](https://user-images.githubusercontent.com/716739/57582249-f606e500-74f4-11e9-92ed-55df6e95ab54.png)
Here is the log for **objectbox 2.2.0**:
![20190512202821](https://user-images.githubusercontent.com/716739/57582265-26e71a00-74f5-11e9-9163-af73bc31e496.png)
Here is the log for **objectbox from 2.3.0 to 2.3.4**:
![20190512203046](https://user-images.githubusercontent.com/716739/57582309-96f5a000-74f5-11e9-8081-db786cfe2817.png)
Maybe some change from 2.20 to 2.3.0 cause the issue?

**Comment by liyzay** [comment]
I read the changelog and found this change from 2.2.0 to 2.3.0:

> Android: set extractNativeLibs to false to avoid issues with extracting the native library

Resoved this issue by adding:

> <application
    ...
    android:extractNativeLibs="true"
    tools:replace="android:extractNativeLibs"
    ...   
   </applicaton>
You can found it by [how-much-does-objectbox-add-to-my-apk-size](https://docs.objectbox.io/faq#how-much-does-objectbox-add-to-my-apk-size)

**Comment by greenrobot-team** [comment]
Note that this will increase the size of app updates. Google recommends to set this flag to false.
https://developer.android.com/topic/performance/reduce-apk-size#extract-false
-Uwe
