### ISSUE TITLE
Can the database be encrypted? What are the related functions?

### ISSUE THREAD

**Issue by qeadsw** [objectbox/objectbox-java#707]
Version 2.3.4

Can the database be encrypted? What are the related functions?

**Comment by greenrobot-team** [comment]
This is currently not supported by the database. See the existing discussions.
https://github.com/objectbox/objectbox-java/issues/8
https://github.com/objectbox/objectbox-java/issues?utf8=%E2%9C%93&q=is%3Aissue+encryption
-Uwe
