### ISSUE TITLE
alternative config for objectbox just like 'daoPackage' in greenDao

### ISSUE THREAD

**Issue by bravewilliam** [objectbox/objectbox-java#709]
I am migrating data from your greenDAO database to ObjectBox.The 'build.gradle' file is like that.
greendao {
      daoPackage 'com.uum.library.data.db'
}
with the config,the the package  of generated code will be 'com.uum.library.data.db'.
Is there a alternative config for objectbox just like this?

**Comment by greenrobot-team** [comment]
No, generated code is always placed in the same package as your entities.

But you can change which MyObjectBox is generated into: https://docs.objectbox.io/advanced/advanced-setup#change-the-myobjectbox-package

-Uwe

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
