### ISSUE TITLE
Use ObjectBox lib in sdk (library) and application

### ISSUE THREAD

**Issue by core2root** [objectbox/objectbox-java#713]
Hi, i built an android library with the help of object box library, this app is meant to be sent to multiple customers, each will implement it as they like.
Also i building my own app with the help of my library and i'm trying to use object box for the app too, the problem is that when i launch the app and it comes to the point where `boxStore.boxFor(Site.class)` it is crashing with the message: "....data.model.Site is not a known entity. Please add it and trigger generation again."
I do mark my Site class with `@Entity` annotation.

`@Entity
public class Site {
  @Id
  private long id;
  private String name;
  private String siteId;
  ....
`
When i look in the `MyObjectBox` class in app module i don't see my `Site` class there but i do see all classes from the library.
And if i take look into `default.json` file in app module i do see Site class there but not classes from my library.
Is this means that your library cannot be used for this scenario?

**Comment by core2root** [comment]
After some hours of explore i saw that the problem was in import, the IDE imported `MyObjectBox` class from the library instead of the app module.

**Comment by jicg** [comment]
how to solve this problem？

**Comment by core2root** [comment]
> how to solve this problem？

What problem do you have?

**Comment by jicg** [comment]
If there are Entity in multiple modules. Only one module of Entity is useful

**Comment by core2root** [comment]
> If there are Entity in multiple modules. Only one module of Entity is useful

Same problem happened to me, in the module where the Entity is not working currently delete the import of MyObjectBox, this line : `import com.***.****.model.MyObjectBox;`
Then comment the code : `BoxStore boxStore = MyObjectBox.builder()
              .androidContext(getApplicationContext())
              .name("your_db_name")
              .build();`
clean project and build again , then un-comment the code above, and when you import the `MyObjectBox `class make sure you import the current one from current module.

**Comment by jicg** [comment]
thanks。

**Comment by core2root** [comment]
> thanks。

Is that helped you?

**Comment by jicg** [comment]
I moved all the entities to a module.
