### ISSUE TITLE
Flatbuffering from device to device, with ObjectBox, like protobuffer, JSON etc.

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-java#726]
I read that _flatbuffers_ can be used as a serialization scheme e.g. JSON, protobuffers. Short of receiving an _mdb file_ on an app and creating a new ObjectBox instance to read the transmitted data, can ObjectBox directly accept _flatbuffer objects_ like JSON, assuming the schema by sending party is the same?

**Comment by Buggaboo** [comment]
I'll have to check out Sync then...

**Comment by greenrobot-team** [comment]
Not with the Java API, but this might be possible with the C API (in preview).
https://objectbox.io/dev-get-started/

But yes, for syncing device-to-device we are working on a syncing solution.
https://objectbox.io/sync/
https://twitter.com/mobile_n_games/status/1146375648946114560

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
