### ISSUE TITLE
Performance Change After first Query

### ISSUE THREAD

**Issue by andreishosta** [objectbox/objectbox-java#727]
Hi,
Is objectbox doing some caching on query results automatically?
Because when I perform a same query in a loop, there is a big different in time between first and all the next queries.
It always happens like first query for  example takes 5000ms but the next ones just take 190ms.

**Comment by greenrobot-team** [comment]
Not sure why this wasn't answered, yet. But yes, there are various optimizations.

If you continue to have reproducible performance issues, feel free to create a new issue.
