### ISSUE TITLE
An error will still occur after adding the corresponding cpu.S0 library. How to solve it, is it a compatibility issue or?

### ISSUE THREAD

**Issue by RainQuKong** [objectbox/objectbox-java#729]
![image](https://user-images.githubusercontent.com/49434528/60648562-c203cc80-9e72-11e9-8a8c-4d162412e514.png)

**Comment by greenrobot-team** [comment]
Sorry, I don't understand the issue. Your screenshot does not show anything related to ObjectBox.

Anyhow, if you have issues with loading the native library and are using Android App Bundle check out the docs.
https://docs.objectbox.io/android/app-bundle-and-split-apk

**Comment by greenrobot-team** [comment]
Closing because this issue is missing details. Feel free to re-open with additional details.
