### ISSUE TITLE
Could not download objectbox-windows.jar

### ISSUE THREAD

**Issue by wangpeng1** [objectbox/objectbox-java#730]
Unable to resolve dependency for ':objectboxdemo@debugUnitTest/compileClasspath': Could not download objectbox-windows.jar (io.objectbox:objectbox-windows:2.3.4)

Could not download objectbox-windows.jar (io.objectbox:objectbox-windows:2.3.4)
 > Could not get resource 'https://jcenter.bintray.com/io/objectbox/objectbox-windows/2.3.4/objectbox-windows-2.3.4.jar'.
    > Read timed out

**Comment by greenrobot-team** [comment]
I can download the file just fine. Maybe try a different network, turn off any proxy or VPN.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
