### ISSUE TITLE
如何修改某一列的数据

### ISSUE THREAD

**Issue by SuperBigJian** [objectbox/objectbox-java#731]
How to modify the value of a column？

**Comment by greenrobot-team** [comment]
Not sure what exactly you need. If you simply want to change a property value:
```
val note = noteBox.get(noteId)
note.text = "This is a new text"
noteBox.put(note)
```

To rename a property or change the type of a property see the docs.
https://docs.objectbox.io/advanced/data-model-updates

**Comment by SuperBigJian** [comment]
getAllPerson().forEach {
            it.state = 0
            putPerson(it)
 }

I want do something like this  "update person set state=0;" in SQLite 

Forgive me for my poor English.

**Comment by greenrobot-team** [comment]
ObjectBox works with plain Java objects.

Try something like this:
```
List<Person> personList = personBox.getAll();
for (Person person : personList) {
   updatePerson(person);
}
personBox.put(personList);
```
