### ISSUE TITLE
Huge value for maxSizeInKByte causes crash on Android

### ISSUE THREAD

**Issue by enuoCM** [objectbox/objectbox-java#735]
## Issue Basics
- ObjectBox version 
2.3.4
- Reproducibility: 
always

### Description
Crash happens when set 10T max size.

### Code
`BoxStore boxStore = MyObjectBox.builder()
                .maxSizeInKByte(1024 * 1024 * 1024 * 10L ) //10T
                .androidContext(context.getApplicationContext())
                .build()`

### Logs & stackstraces
07-10 11:05:42.734 28648 28648 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.XXX.XXX.XXApplication: io.objectbox.exception.DbException: Could not open env for DB (12) (error code 12)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5421)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6134)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: Caused by: io.objectbox.exception.DbException: Could not open env for DB (12) (error code 12)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at io.objectbox.BoxStore.nativeCreate(Native Method)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at io.objectbox.BoxStore.<init>(BoxStore.java:203)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)

07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5418)
07-10 11:05:42.734 28648 28648 E AndroidRuntime: 	... 8 more

## Misc
Non multi-process
It's OK on PC test with `maxSizeInKByte(1024 * 1024 * 1024 * 10L ) //10T`.
Change to `maxSizeInKByte(1024 * 1024 * 10L ) //10 G` is OK on Android

**Comment by greenrobot-team** [comment]
Error code 12 is the Linux kernel error code ENOMEM or "Out of memory". I suspect the Android device does not have enough memory to manage such a large database.

https://github.com/torvalds/linux/blob/6f52b16c5b29b89d92c0e7236f4655dc8491ad70/include/uapi/asm-generic/errno-base.h#L16

**Comment by enuoCM** [comment]
@greenrobot-team  Yes，no Android device has 10TB memory and My PC too. But it's just the max size setting, it does not consume all at beginning.

**Comment by greenrobot-team** [comment]
It still needs to be managed. And yes, that does not mean it is consumed, yet.

Anyhow, I would recommend setting a reasonable size and instead ensuring to not grow your database beyond a certain number of entities.
