### ISSUE TITLE
Cannot update model

### ISSUE THREAD

**Issue by Kashish-Sharma** [objectbox/objectbox-java#737]
## Issue Basics
- ObjectBox version (2.3.4)
- Reproducibility: always
- Android Studio: 3.4.1

I tried updating my entity variables ( From Int to String )
1. Added `@Uid` annotation 
2. Started building
3. Build failed
4. Couldn't find
```
error: [ObjectBox] UID operations for property "Movies.contentType": 
  [Rename] apply the current UID using @Uid(6707341922395832766L) -
  [Change/reset] apply a new UID using @Uid(9204131405652381067L)
```
any such error.

Please help!
Thanks

**Comment by greenrobot-team** [comment]
Briefly tested with our Kotlin example on Android Studio 3.5 Beta 5 with Android Gradle Plugin 3.4.1 and it works fine.

![image](https://user-images.githubusercontent.com/13865709/61270421-ea0ffb80-a7a1-11e9-9464-c29df6f22200.png)

I used Build > Make Project.

Can you share more details about your setup or a small example project?

**Comment by Kashish-Sharma** [comment]
Still getting the same errors.
![sample](https://user-images.githubusercontent.com/26424111/61271366-0ae84900-a7c2-11e9-91e9-985738349fc2.jpg)

I'm just wondering why that Kotlin compiler why that `kotlin compiler` error is not showing.
Thanks.

**Comment by greenrobot-team** [comment]
Based on your screenshot there is a compilation error. As the message says "See log for more details".

You can toggle the output to show the full log using the button below the hammer on the left.

**Comment by Kashish-Sharma** [comment]
I think this is what's causing a compilation error.

![sample1](https://user-images.githubusercontent.com/26424111/61276600-fb6efd00-a7cd-11e9-816a-b12b8612a6c9.jpg)

Before adding the `@Uid` annotation everything works fine.

**Comment by greenrobot-team** [comment]
Before adding the `@Uid` annotation do Build > Make Project. Then `MyObjectBox` should get generated.

The add the `@Uid` annotation and build again. But do not clean or rebuild the project.

**Comment by Kashish-Sharma** [comment]
Updated the Android Studio and it works fine now.
Thanks!
