### ISSUE TITLE
Declare data type error (Original: 声明数据类型报错)

### ISSUE THREAD

**Issue by Fanyunf** [objectbox/objectbox-java#738]
Drawable type How to report a rebuild error in an entity Cannot use the Drawable type

Original:
Drawable 类型 如何在实体中 声明  rebuild  时报错 不能使用Drawable类型

**Comment by greenrobot-team** [comment]
I'm not sure what you are trying to do. Could you share a code example?

Note that ObjectBox supports a fixed set of data types. If you want to use other types you have to provide a converter.
https://docs.objectbox.io/advanced/custom-types

Just using the `Drawable` class inside an `@Entity` class works fine based on a quick test.

**Comment by greenrobot-team** [comment]
Closing because this issue is missing details. Feel free to re-open with additional details.
