### ISSUE TITLE
Question: Does it OK to use minSdkVersion 14 for objectbox-android:2.3.4

### ISSUE THREAD

**Issue by enuoCM** [objectbox/objectbox-java#739]
My Android app has to support minSdkVersion 14.  Is it safe to use objectbox-android:2.3.4 which declared minSdkVersion 15. Thanks in advance for any confirmation.

**Comment by greenrobot-team** [comment]
It should be.

Though there shouldn't be any (sane) devices out there using SDK 14 (Android 4.0). So you are on your own if errors pop up.
