### ISSUE TITLE
about Tomany Question

### ISSUE THREAD

**Issue by guqh** [objectbox/objectbox-java#740]
![image](https://user-images.githubusercontent.com/17330238/61575036-78191880-aaf9-11e9-8a5d-d87b5adab7fd.png)

![image](https://user-images.githubusercontent.com/17330238/61575206-a39d0280-aafb-11e9-926a-c965f1052d9e.png)

![image](https://user-images.githubusercontent.com/17330238/61575219-b57ea580-aafb-11e9-9f94-ef1163cbce71.png)

Translation:
My two tables use orderCoder as the associated foreign key, and I want to store the implementation directly through the productBox. How can I ensure that the data directly put by the productBox is found in the query order?

Original:
我两张表 通过 orderCoder 作为关联外键，想要通过 productBox 直接 put 进行存储实现，怎么才能保证在 query order 的时候 查到 通过 productBox 直接 put 的数据？

**Comment by guqh** [comment]
orderResult2 中没有  product2

**Comment by guqh** [comment]
I hope that product 2 can be included in orderResult 2. How can it be implemented?

**Comment by guqh** [comment]
I hope that  “product2” can be included in ”orderResult2“. How can it be implemented?

**Comment by guqh** [comment]
help me

**Comment by guqh** [comment]
@

**Comment by greenrobot-team** [comment]
ObjectBox is not a relational database like SQLite, so there is no concept like foreign keys.

To add a relation, you need to add a product to a `ToMany` and then put the source entity. Like you did for `product1`.

https://docs.objectbox.io/relations#to-many-relations

**Comment by guqh** [comment]
Thanks!
oh my god ! I use a lot of relationship bindings and modifications here, which is too cumbersome to do.
