### ISSUE TITLE
DbException: Could not commit tx (-30797)

### ISSUE THREAD

**Issue by xr-hui** [objectbox/objectbox-java#745]
## Issue Basics
- ObjectBox version (are using the latest version?): *2.3.4*
- Reproducibility: *occasionally without visible pattern*

### Description
*My application is running on the android(Android 8.1) system. In most cases, the application runs very stably. However, it is found that sometimes this bug will appear after the machine restarts, causing the application to crash. Even my UncaughtExceptionHandler cannot capture it.*

### Code
*Provide the code triggering the bug.
![Crash when put is calling](https://user-images.githubusercontent.com/19950614/62703830-a0bb7080-ba1c-11e9-85ac-7d3076953c94.png)
![Related method](https://user-images.githubusercontent.com/19950614/62703907-cf394b80-ba1c-11e9-80b3-f30aac1768fc.png)

### Logs & stackstraces
![log](https://user-images.githubusercontent.com/19950614/62703964-ee37dd80-ba1c-11e9-9c23-3585453163ff.png)

## Entities
*Provide the code for entities related to the bug (shorten to relevant parts).*
![Entity field](https://user-images.githubusercontent.com/19950614/62704051-17f10480-ba1d-11e9-9fcb-5c9ebe1f6f92.png)

## Misc
*Is there anything special about your app?
May transactions or multi-threading play a role?
Did you find any workarounds to prevent the issue?*
My app is running on vending machine as a default launcher.

**Comment by greenrobot-team** [comment]
Thanks for reporting. Also see the discussion in https://github.com/objectbox/objectbox-java/issues/646. Do you know how to reliably bring the database into that state (e.g. does this happen on every restart, how is the machine restarted)?

**Comment by xr-hui** [comment]
@greenrobot-team Thanks for your reply.
1. does this happen on every restart, how is the machine restarted?

**Comment by xr-hui** [comment]
@greenrobot-team Thanks for your reply

1. Does this happen on every restart, how is the machine restarted?
When this problem occurs, it will be the same no matter how to restart it.

2. How is the machine restarted?
In fact, my application is running on a vending machine, and restart is usually to directly disconnect the main power supply, not the shutdown and restart option of the system.

I also consider that it may be caused by hardware or firmware, but according to the current log, there is no way to judge. Is it possible that the database connection was abnormally closed?

**Comment by greenrobot-team** [comment]
> directly disconnect the main power supply

Hm, possibly check which file system the machine is using and if it is built to handle power loss (e.g. has journaling and file transactions). However, most modern file system should handle that well, so not sure if this applies. 🤷‍♂

**Comment by xr-hui** [comment]
All right, I'll I try my best to check. Anyway, thank you very much.
