### ISSUE TITLE
C:\Users\__\.objectbox-build.properties (The requested operation cannot be performed on a file opened with the user mapping area.)

### ISSUE THREAD

**Issue by XBYoung** [objectbox/objectbox-java#749]
Original title: `C:\Users\__\.objectbox-build.properties (请求的操作无法在使用用户映射区域打开的文件上执行。)`

clean  and rebuild project,resolve this issue,but,so annoying.

**Comment by greenrobot-team** [comment]
Should this still be an issue with the latest release, feel free to re-open with more details or submit a new issue.
