### ISSUE TITLE
Not auto generage getter and setter

### ISSUE THREAD

**Issue by wangpeng1** [objectbox/objectbox-java#754]
objectbox version ：io.objectbox:objectbox-android:2.3.4
android studio version ：3.2
```
  classpath 'com.android.tools.build:gradle:3.1.0'
  classpath "io.objectbox:objectbox-gradle-plugin:2.3.4"
```
```
@Entity
public class FaceBlackEntity {
    @Id
    long oid;
    @Index
    String blackUrl;
    String blackPath;

    @Index
    String blackNum;
    String blackType;
```

when i make project，not auto generate get or set

**Comment by greenrobot-team** [comment]
The ObjectBox plugin does not generate getters or setters, add the ones you need.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
