### ISSUE TITLE
how to save a class with an inner class?

### ISSUE THREAD

**Issue by fashioncj** [objectbox/objectbox-java#756]
```
@Entity
public class A{
   @Id
    public long idx;
    B b;

    @Entity
    public class B{
       @Id
        public long idx;
        String c;
}
} 
```
--
in this case, class B_ will general with error

**Comment by greenrobot-team** [comment]
Try making `B` static. But it's probably best to have `@Entity` classes as separate top-level classes.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
