### ISSUE TITLE
About less() and greater()

### ISSUE THREAD

**Issue by guqh** [objectbox/objectbox-java#759]
![image](https://user-images.githubusercontent.com/17330238/64407748-b376a300-d0b7-11e9-9db5-c7c98687067f.png)
关于这两个函数是否有提供闭区间的方法？
translate：
Is there a closed interval method for these two functions?

**Comment by greenrobot-team** [comment]
Currently not. Thumbs up https://github.com/objectbox/objectbox-java/issues/697 to have this.
