### ISSUE TITLE
Google play 64 bit library compatibility

### ISSUE THREAD

**Issue by SheikhZayed** [objectbox/objectbox-java#762]
Hi as you know google has made it mandatory for all the apps to have 64 bit compatibility.

I have analyzed my APK to see that object box has some native code.

Google is expecting third party libraries which use native code to provide update as a fix to this problem.

Please let me know how do I overcome this issue 

I'm using object box : 2.3.4

**Comment by greenrobot-team** [comment]
ObjectBox provides 64-bit versions for both ARM and x86 (so armeabi-v7a, arm64-v8a, x86 and x86_64).
https://docs.objectbox.io/faq#on-which-platforms-does-objectbox-run

Do you maybe have an ABI filter configured in your `build.gradle` file?

**Comment by SheikhZayed** [comment]
Yes,

I have this : `ndk.abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'`

**Comment by greenrobot-team** [comment]
Then you should be fine. You can inspect the built APK by opening it in Android Studio to check if it actually contains the native library files.

![image](https://user-images.githubusercontent.com/13865709/64591722-c1277380-d3aa-11e9-8715-7fc66df94320.png)

**Comment by SheikhZayed** [comment]
Yes,it does contain.

but according to this blog[https://developer.android.com/distribute/best-practices/develop/64-bit#test_your_app_on_64-bit_hardware](url)

AFAIK,if the app contains .so files (native code),google will not accept it for store listing 

Please correct me if im wrong

**Comment by greenrobot-team** [comment]
Your app is fine and ready for 64-bit support. The relevant part is here: https://developer.android.com/distribute/best-practices/develop/64-bit#test_your_app_on_64-bit_hardware

**Comment by SheikhZayed** [comment]
so you mean to say that even though it contain .so files, it is safe to go ?

I might have understood it wrong...Thanks anyway #

**Comment by greenrobot-team** [comment]
Yes, safe. Google Play should accept your APK.

Closing this then.

**Comment by SheikhZayed** [comment]
Thanks 👍
