### ISSUE TITLE
Result of QueryBuilder.build().count() dosen't match QueryBuilder.build().count().size()

### ISSUE THREAD

**Issue by fakerqu** [objectbox/objectbox-java#771]
#764  Issue Basics
- ObjectBox version (are using the latest version?): 2.3.4
- Reproducibility: *[always]*

### Description
Result of QueryBuilder.build().count() dosen't match QueryBuilder.build().count().size()

### Code
```java
List<MtLogEntity> entities = ObjectBoxManager.getInstance().getMtLogEntityBox().query()
                    .filter(entity -> logFile.getName().contains(entity.getFirstLogName()))
                    .build().find();
            long count = ObjectBoxManager.getInstance().getMtLogEntityBox().query()
                    .filter(entity -> logFile.getName().contains(entity.getFirstLogName()))
                    .build().count();
```

### Logs & stackstraces
While I was debugging the result of build().count()==1 ,but the size of entities is 0!
![bug](https://user-images.githubusercontent.com/29764984/65752026-82c9dc80-e13e-11e9-946b-c491d5fc7e61.png)
My database is quite simple and only contains one entity
![捕获](https://user-images.githubusercontent.com/29764984/65752284-126f8b00-e13f-11e9-9aee-c74983448ba2.PNG)

**Comment by greenrobot-team** [comment]
Thanks for reporting. `query.count()` does not use a given filter. So the result size will be different.

Filters only work with `find()` as stated in the documentation.
https://github.com/objectbox/objectbox-java/blob/c9ede740daf045aaf394657c435fa40ba042afd7/objectbox-java/src/main/java/io/objectbox/query/QueryBuilder.java#L385-L399

So this is a documentation oversight, but we might as well throw an error as the other `Query` methods do.

**Comment by greenrobot-team** [comment]
Starting with `2.4.0-RC` calling `count()` or `remove()` while using a filter throws.
