### ISSUE TITLE
[Android] objectbox-models path concatenation broken w/kotlin 1.3.41, 1.3.50

### ISSUE THREAD

**Issue by tellypresence** [objectbox/objectbox-java#772]
Configuration: Win 64 Android Studio 3.5 stable, gradle plugin 3.5.0, gradle 5.4.1, AndroidX

Have a project that has been stable and working for months with older version of kotlin (1.3.21)

Innocently updated kotlin to 1.3.41 (and later 1.3.50) but suddenly had catastrophic build failures due to inability to find objectbox model file; the error message indicates that the way the relative path is being interpreted has changed in newer kotlin versions (instead of looking relative to project root now tries to navigate from kotlin daemon folder)

ObjectBox code is in simple android library module located under "Libs" folder at same level as the main android studio project; again this setup has been working fine for months but is brittle in the face of kotlin version upgrade

Project root level build.gradle
```
buildscript {
    ext.kotlin_version = '1.3.21'
    ext.objectboxVersion = '2.3.1'
...
ext {
    // NOTE: path rel to _app_ folder, not library module
    objectBoxModelPath = '../Libs/DBObjectBox/objectbox-models/default.json'
```

If kotlin version updated to 1.3.41 or 1.3.50 build fails with error e.g.
```
e: error: [ObjectBox] The model folder does not exist at
     'C:\Users\<username>\AppData\Local\kotlin\daemon\..\Libs\DBObjectBox\objectbox-models'
     (based on the option objectbox.modelPath='../Libs/DBObjectBox/objectbox-models/default.json').
```
Obviously the intended path concatenation should not involve the kotlin daemon (!) folder, so something's seriously wrong

P.S.  Same problem w/objectBox 2.3.4

**Comment by greenrobot-team** [comment]
Using a relative path to set `objectBoxModelPath` is dangerous as it depends on Gradle and the build setup how it is resolved to an absolute path. This is also why the docs suggest using an absolute path.
https://docs.objectbox.io/advanced/advanced-setup#change-the-model-file-path

**Comment by nabraas60000** [comment]
Good

**Comment by nabraas60000** [comment]
hi

**Comment by greenrobot-team** [comment]
Closing. Please re-open if your question was not answered.
