### ISSUE TITLE
2.4.0-RC errir (objectbox-examples-master)

### ISSUE THREAD

**Issue by 1341290135** [objectbox/objectbox-java#774]
ERROR: Failed to resolve: io.objectbox:objectbox-windows:2.4.0-RC

**Comment by greenrobot-team** [comment]
Thanks for reporting. Due to an error we could not publish the `objectbox-windows` artifact. It is published now, including some fixes to the example projects.

**Comment by 1341290135** [comment]
Thank you very much. It's all right now.

**Comment by greenrobot-team** [comment]
Closing this then.
