### ISSUE TITLE
Is Multi process supported yet?

### ISSUE THREAD

**Issue by DennisMuchiri** [objectbox/objectbox-java#791]
In reference to the issue 
https://github.com/objectbox/objectbox-java/issues/403

Please confirm if multi process is supported. Am getting the same error 

java.lang.IllegalArgumentException: ID is higher or equal to internal ID sequence: 51 (vs. 51). Use ID 0 (zero) to insert new entities.

@greenrobot @greenrobot-team  please confirm

**Comment by greenrobot-team** [comment]
No. See and thumbs up #193.
