### ISSUE TITLE
How to Update someone property value？

### ISSUE THREAD

**Issue by s349856186** [objectbox/objectbox-java#792]
I want do something like this "update myFrom set counts = counts+1 where name = "Alfa" in SQLite, in objectBox how to do? Thanks

![20191205201934](https://user-images.githubusercontent.com/2498958/70235047-01757280-179d-11ea-8276-350af34c847b.jpg)

**Comment by greenrobot-team** [comment]
There is no such thing like the update method used in SQL-based databases.

Just get the entity, change any property and put it again.
