### ISSUE TITLE
On app build deprecated API error

### ISSUE THREAD

**Issue by andzejsw** [objectbox/objectbox-java#794]
On app create i am seeing this error:
```
Note: [ObjectBox] Starting ObjectBox processor (debug: false)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by greenrobot-team** [comment]
I do not see this for our example applications. Could you do as the message suggested and recompile with the `-Xlint:deprecation` flag set and share the output?

**Comment by andzejsw** [comment]
I was going through my deprecated code and fixed some of it and message disappeared. Looks like it was related to deprecated ProgressDialog usage on my side.
