### ISSUE TITLE
problem with ToOne relation on converting object to JSON

### ISSUE THREAD

**Issue by faridfedora** [objectbox/objectbox-java#809]
## Issue Basics
- ObjectBox version : 2.5.0
- Reproducibility: *[always]*

### Description
when I want to convert my object to JSON with gson it returns null for ToOne<PomoSubject> relation.
you can see the result in output: "pomoSubject":{} but actually it's not null.
expected output must be exactly such as PomoSubject Model Map.

### Code
```
        List<Pomodoro> pomodoroList = ObjectBox.get().boxFor(Pomodoro.class)
                                                           .query().equal(Pomodoro_.mongoId, "")
                                                           .eager(Pomodoro_.pomoSubject).build().find();
            Gson gson = new GsonBuilder().excludeFieldsWithoutExposeAnnotation().create();
            gson.toJson(pomodoroList); //>> output
```

## Entities
 
```
@Entity
public class Pomodoro  {
    @Id
    public long id;
    @SerializedName("_id")
    private String mongoId="";  
    @Expose
    private int pomoDurationMinute;

    @Expose
    private ToOne<PomoSubject> pomoSubject;
}

@Entity
public class PomoSubject   {
    @Id
    public long id;
    @Expose
    private String _id; //mongodb id;
    @Expose
    @Unique
    private String title;
    private int count;
    private long totalTimeMinute;

}
```

##output
`[{"finishTime":1578685347767,"gregDate":"Jan 10, 2020 11:12:27 PM","pomoDurationMinute":2,"pomoSubject":{}},{"finishTime":1578685379891,"gregDate":"Jan 10, 2020 11:12:59 PM","pomoDurationMinute":2,"pomoSubject":{}},{"finishTime":1578685508589,"gregDate":"Jan 10, 2020 11:15:08 PM","pomoDurationMinute":2,"pomoSubject":{}},{"finishTime":1578685543225,"gregDate":"Jan 10, 2020 11:15:43 PM","pomoDurationMinute":2,"pomoSubject":{}}]`

## Misc
gson:2.8.6
gradle:3.5.3
minSdkVersion 16
targetSdkVersion 28

**Comment by greenrobot-team** [comment]
You probably have to write an adapter that uses `ToOne.getTarget()` to get the object of the ToOne to parse into JSON. The `ToOne` itself is just the wrapper object for state tracking and other things.

**Comment by faridfedora** [comment]
Considering app's performance is it good solution to write adapter ?
And do u have any reference or sample code for best approach of writing adapter?

**Comment by greenrobot-team** [comment]
Sorry, these are questions to ask the Gson team. As for writing an adapter, see https://github.com/google/gson/blob/master/UserGuide.md#TOC-Custom-Serialization-and-Deserialization.

**Comment by faridfedora** [comment]
Oh so much trouble...I think it's better to use greendao again.
thanks for your help anyway

**Comment by greenrobot-team** [comment]
Closing this then.
