### ISSUE TITLE
Would not recommend over GreenDao actually

### ISSUE THREAD

**Issue by breakline87** [objectbox/objectbox-java#812]
Why do you guys recommend this over GreenDao? I feel like it's a step-back. You should explicitly list the numerous problems:

1. I cannot use ToOne and ToMany and such without extensive refactoring in an existing project. My POJO's are tied to databinding too, ergo I need to refactor at multiple points, besides issues with json parsing and internal references

2. Using ToOne and ToMany in my model layer means the model layer is strong-coupled to my database layer...A big no-no and breaks basic encapsulation principles (unlike annotations which are not exposed)

3. As others said huge problems with json parsing: even if you use custom setters, Objectbox WILL need the getters to be the proper type (that is, you need to use ToOne or ToMany again)

4. the lib should not break basic usage over assignable ID's... Again a very common use case where you get all your ID's from a remote server. Relations should be saved wheter you use your own ID's or not.

Annotating 20 POJO's and writing a service layer is work, but its not comparable to refactor every layer which uses the models.

**Comment by Dugin123** [comment]
Agree. 

"TooMany" is too many problem.
"TooOne" is too wrong.

**Comment by greenrobot-team** [comment]
Thanks for your feedback. Improving the mapping of relations from something like JSON is covered by #104.

As for assignable IDs this can be solved by using separate ID properties for the model and ObjectBox.
https://docs.objectbox.io/entity-annotations#object-ids-id

Anyhow, yes, it's always a challenge to share the same model between server and database.

Closing this as no new features suggestions or actual bugs.
