### ISSUE TITLE
loading schema failed:Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sangx123** [objectbox/objectbox-java#815]
i used objectbox-kotilin in androidx in debug model  
 when  i open the browser to see local database 
 i get a toast  in my app browser
 it tips  loading schema failed:Cannot read property 'name' of undefined

**Comment by sangx123** [comment]
I solved this problem happy haha.

**Comment by greenrobot-team** [comment]
@sangx123 So this issue can be closed? Do you mind sharing, what the problem was?
