### ISSUE TITLE
Problems when building with Kotlin

### ISSUE THREAD

**Issue by MGlolenstine** [objectbox/objectbox-java#821]
## Issue Basics
- ObjectBox version (are using the latest version?): 2.5.0
- Reproducibility: always

### Description
*Describe the situation in English in which you encounter the bug.*
Created new project with *Maven*, imported needed dependencies and added the maven plugin
As soon as I port the entity to Java, it works flawlessly.
### Code
@Entity
data class RandomText1(
        @Id var id: Long = 0,
        var text: String = ""
)
### Logs & stackstraces
Finding the `Notes.kt` file in the path, but it doesn't export it
## Entities
*Provide the code for entities related to the bug (shorten to relevant parts).*
```
@Entity
data class RandomText1(
        @Id var id: Long = 0,
        var text: String = ""
)
```
## Misc
*Is there anything special about your app?
May transactions or multi-threading play a role?
Did you find any workarounds to prevent the issue?*
I'm using the Maven with the Maven plugin with the following configuration
```
<plugin>
<groupId>io.objectbox</groupId>
<artifactId>objectbox-maven-plugin</artifactId>
<version>1.1.0</version>
<executions>
    <execution>
        <goals>
            <goal>transform</goal>
        </goals>
    </execution>
</executions>
<configuration>
    <debug>true</debug>
</configuration>
</plugin>
```
I know that the Maven plugin is in ~~early access~~ kinda unsupported, but I'm still reporting it, as it's apparently working, but not as well as it should.

**Comment by greenrobot-team** [comment]
Sorry, Kotlin is currently only fully supported on Android. Desktop app support is limited to Java right now.
https://docs.objectbox.io/java-desktop-apps

**Comment by MGlolenstine** [comment]
I knew as much but wanted to let you know that it does work with Kotlin, just entities need to be in Java!

Thanks for your reply!
