### ISSUE TITLE
Changing the datatype of a property

### ISSUE THREAD

**Issue by ksdc-anandhid** [objectbox/objectbox-java#825]
Hi,
I noticed that when I change the datatype of property the existing data is lost as Objectbox does not support migrating data to the new datatype. One solution that was recommended in the Object box website is to add a new property with a different name so that custom logic can be added to migrate the data from the old property to the new one. But in doing so the property name along with the datatype is getting changed. Is there any other way to change the datatype and still have the old data in the new type. Please advise.

**Comment by greenrobot-team** [comment]
ObjectBox behavior has not changed since then. You described the existing solution: create and use a new property, fetch data from the old property as needed. I'm not sure how else one could do this.
https://docs.objectbox.io/advanced/data-model-updates

**Comment by ksdc-anandhid** [comment]
Thanks for the reply.
