### ISSUE TITLE
BoxStore.removeAllObjects is not working

### ISSUE THREAD

**Issue by liyzay** [objectbox/objectbox-java#828]
## Issue Basics
- ObjectBox version (are using the latest version?): *No(2.5.0)*
- Reproducibility: *[always]*

### Description
I want to delete all my data but leave the data table,so I use **BoxStore.removeAllObjects**.
After call **BoxStore.removeAllObjects**,I can still see my data.
Isn`t **BoxStore.removeAllObjects** suppose to delete all data?

**Comment by greenrobot-team** [comment]
`BoxStore.removeAllObjects()` removes all data, yes. We have internal tests verifying it works as expected. Can you share a small example project that reproduces this?

**Comment by yesimbig** [comment]
I have the same problem too. When I use removeAllObjects in my android app, the spaced used in app data isn't removed. Although the data cannot be queried, it still takes lots of space inside disk data.

**Comment by greenrobot-team** [comment]
@yesimbig Note that `BoxStore.removeAllObjects()` does **not** reclaim disk space for performance reasons.

See https://docs.objectbox.io/faq#how-to-reclaim-disk-space-used-by-objectbox on how to reclaim disk space, if that's what is important.
