### ISSUE TITLE
ERROR: Unable to resolve dependency 2.5.1

### ISSUE THREAD

**Issue by pratikbutani** [objectbox/objectbox-java#830]
- ObjectBox version - 2.5.1 

### Description
I have updated Android Studio 3.6.1 and also updated Gradle Plugin and Gradle Version. I got suggestion to update ObjectBox version from 2.5.0 to 2.5.1.

I have tried to update 2.5.1 but getting errors as follow:

`
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download objectbox-windows.jar (io.objectbox:objectbox-windows:2.5.1)
`

What can I do? Any solution?

**Comment by greenrobot-team** [comment]
The `objectbox-windows` artifact has been downloaded almost 1k times from Bintray. So I guess check your network setup and connection. This is unlikely an issue that we can resolve.

Worst case you can get it manually from our Bintray repo: https://bintray.com/beta/#/objectbox/objectbox/io.objectbox:objectbox-windows/2.5.1?tab=files

**Comment by pratikbutani** [comment]
Thank you. My Internet connection was restricted. Its solved.
