### ISSUE TITLE
DbException: Cannot change the following flags for Property id (1, Long) (Crash) from 5 to 1 (problematic flags: 4)

### ISSUE THREAD

**Issue by SunmerCho** [objectbox/objectbox-java#833]
I used verison 2.3.4 and it works well, now i want to upgrade to the latest version 2.5.1 but it can not open the app and the log as the title. I notice that the default.json auto generate the "name',"type","flat" tags under "properties", What should i do to fix that?

**Comment by greenrobot-team** [comment]
A recent version removed the `NOT_NULL` flag on ID properties. Check that all dependencies for ObjectBox use version `2.5.1`. E.g. maybe there is an explicit dependency on `objectbox-android` somewhere?

Using the Gradle `:app:dependencies` task can also help when checking dependency versions.

**Comment by greenrobot-team** [comment]
Update: it's also possible that your generated code is out of date. Make sure to clean + make (or Rebuild in Android Studio) your project. Also ensure any dependencies are updated to 2.5.1.

**Comment by AntWhale** [comment]
I have same problem. what should I do??
