### ISSUE TITLE
Support "not" contains/startsWith/endsWith

### ISSUE THREAD

**Issue by clunyes** [objectbox/objectbox-java#835]
```
 List<BjWordBean> listAll = wordBox.query().contains(BjWordBean_.word, lastWord).orderDesc(BjWordBean_.hitNum).build().find();
List<BjWordBean> listEnd = wordBox.query().endsWith(BjWordBean_.word, lastWord).orderDesc(BjWordBean_.hitNum).build().find();
```

i need contain lastword ,but how can i add condition like not endwith lastWord,but i only find endwith.so now i make them subtract.(english is not good)

thanks :)

**Comment by greenrobot-team** [comment]
Sorry, there is currently neither `notEndsWith(property, value)` or a not/negation condition.

As a workaround maybe use `Query.filter(filter)`.
https://docs.objectbox.io/queries#query-filters

Or use `Query.subscribe()` with a transformer.
https://docs.objectbox.io/data-observers-and-rx#transforming-data

**Comment by greenrobot-team** [comment]
Merging this with #650, it has many votes already.
