### ISSUE TITLE
objectbox-rxjava support for RxJava3

### ISSUE THREAD

**Issue by zhupengxiang** [objectbox/objectbox-java#839]
Do you have any plan to update objectbox-rxjava for RxJava3?

**Comment by greenrobot-team** [comment]
Some notes:
- There is an interop library to bridge RxJava 2 and 3. So you can use RxJava 3 without waiting for us to support it. https://github.com/akarnokd/RxJavaBridge#rxjavabridge
- 2.x will be supported until February 28, 2021.
- The artifact location has changed to `io.reactivex.rxjava3:rxjava:3.0.0`.
- All code lives in a new package `io.reactivex.rxjava3`.

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0

**Comment by greenrobot-team** [comment]
I guess creating a separate artifact makes the most sense (e.g. `objectbox-rxjava3`) as this allows us to still ship fixes for RxJava 2 support.

**Comment by zhupengxiang** [comment]
so much the better

**Comment by greenrobot-team** [comment]
A new library to support RxJava 3 is available with `3.0.0-alpha2`.
https://docs.objectbox.io/#v-3-0-0-alpha2-2020-03-24

As noted before, to continue using the old RxJava 2 extension library with RxJava 3, you can use RxJavaBridge. https://github.com/akarnokd/RxJavaBridge#rxjavabridge

**Comment by greenrobot-team** [comment]
The RxJava 3 support library is now also available with `2.6.0-RC`.
https://docs.objectbox.io/#v-2-6-0-rc-2020-04-28

**Comment by greenrobot-team** [comment]
Available as part of the `2.6.0` release.
https://docs.objectbox.io/#v-2-6-0-2020-06-09
