### ISSUE TITLE
How to go about unit testing calls that use SubscriptionBuilder.on(scheduler)?

### ISSUE THREAD

**Issue by whoyawn** [objectbox/objectbox-java#843]
If my code is something like this
```
get()
  .subscribe()
  .on(AndroidSchedulers.mainThread())
```
but in my unit tests, I don't care about observing on the main thread (I just want to run a synchronous blocking call so I can run assertions), how do "undo" putting the observable on the main thread?

**Comment by greenrobot-team** [comment]
It is not possible to "undo" changing the scheduler. Some suggestions:
- omit the `on(scheduler)` call for test code,
- supply a different `Scheduler` when running tests.

**Comment by greenrobot-team** [comment]
Closing. Please re-open if your question was not answered.
