### ISSUE TITLE
Multi modules not support in Android project

### ISSUE THREAD

**Issue by AnswerZhao** [objectbox/objectbox-java#844]
In the lastest ObjectBox 2.5.1 or old version, If Entities were put in different modules(libs),  the generated entity classes are not all, it just includes one module's entities. 

I know this can be resolved by adding different MyObjectBox, but it works limited.  How can I use one MyObjectBox with entities of multi modules?

**Comment by greenrobot-team** [comment]
Hello, this is currently not supported. Please see and comment on #588.
