### ISSUE TITLE
Need help with relations

### ISSUE THREAD

**Issue by Kashish-Sharma** [objectbox/objectbox-java#852]
## Issue Basics
- ObjectBox version : **3.0.0-alpha2**

### Description
I have 3 entities:
A, B, C

* `A` has **toMany** `B`
* `B` has **toMany** `C`, `B` has **toOne** `A`
* `C` has **toOne** `B`

If I take a new `A`, and add multiple `B`'s in it each containing multiple `C`'s and then put `A`, will it put the whole chain ?

Also, If I add same `B`(already persisted in db, so it's having an auto-gen ID) multiple times in `A`
What's the behaviour in this case, crash? or `A` with a single `B`?

**Comment by greenrobot-team** [comment]
This is what unit test are for, just saying.

https://github.com/objectbox/objectbox-java/blob/1c7416c8371987c44ab2e5844a786b99e3ef76ab/objectbox-java/src/main/java/io/objectbox/relation/ToMany.java#L796-L798
Yes to the first question, if the `B`'s and `C`'s are new as well.

As for adding the same instance multiple times to a `ToMany`, if their `hashCode()` matches they will only get added once. If your code does not override `hashCode()` then that's the case.

**Comment by Kashish-Sharma** [comment]
Thanks for the quick help!
