### ISSUE TITLE
How to use multiple entity ids in a entity?

### ISSUE THREAD

**Issue by Divya21** [objectbox/objectbox-java#853]
I have 4 entities(4 tables) and I want to use multiple entities ids in another entity. How to inherit it. Please help!

```kotlin
@Entity 
data class A ( 
@Id var idA: Long = 0,
var nameA: String? = null
) 

@Entity 
data class B ( 
@Id var idB: Long = 0,
var nameB: String? = null
) 

@Entity 
data class C ( 
@Id var idC: Long = 0,
var nameC: String? = null
) 

@Entity
data class MemberTable(
    @Id
    var memberId: Long =0,

//I want to to do something like this...How to achieve this?
var idsA: List<A.idA>? = null,
var idsB: List<B.idB>? = null,
var idsC: List<C.idC>? = null,

)
```

**Comment by greenrobot-team** [comment]
If you only want to store IDs you have to do it yourself. With ObjectBox, there are relations. In this case adding ToMany<A>, ToMany<B>, etc. to MemberTable would work.
https://docs.objectbox.io/relations

**Comment by Divya21** [comment]
> If you only want to store IDs you have to do it yourself. With ObjectBox, there are relations. In this case adding ToMany, ToMany, etc. to MemberTable would work.
> https://docs.objectbox.io/relations

I have to use List<Int> for this, I have seen its been added to features in 2016. So is there any way?

**Comment by greenrobot-team** [comment]
You would have to write a custom converter for this.
https://docs.objectbox.io/advanced/custom-types

Alternatively, use `ToMany` anyhow. But get the list of related entities using `Box.getRelationIds(MemberTable_.toManyOfA, memberTable.memberId)`.
https://github.com/objectbox/objectbox-java/blob/220fc35ef296b9957a29207596abf8c1313dfcb5/objectbox-java/src/main/java/io/objectbox/Box.java#L657

**Comment by Divya21** [comment]
> You would have to write a custom converter for this.
> https://docs.objectbox.io/advanced/custom-types
> 
> Alternatively, use `ToMany<A>` anyhow. But get the list of IDs of the related entities using `Box.getRelationIds(MemberTable_.toManyOfA, memberTable.memberId)`.
> https://github.com/objectbox/objectbox-java/blob/220fc35ef296b9957a29207596abf8c1313dfcb5/objectbox-java/src/main/java/io/objectbox/Box.java#L657

Thanks a lot!
