### ISSUE TITLE
Transform data before insert into database

### ISSUE THREAD

**Issue by jack9394** [objectbox/objectbox-java#866]
Hello, is there any way to transform data before it enters the database? I want to add some default values just before data is saved and I don't want to do it manually or create an extension for it in Kotlin.

Thank you

**Comment by greenrobot-team** [comment]
I guess a wrapping layer would have to be written for this. Built-in are converters that work only on property level.
https://docs.objectbox.io/advanced/custom-types#convert-annotation-and-property-converter

**Comment by jack9394** [comment]
Thank you for your response. What I'm doing is that all my objects extend a base object that contains `updated_at` and `lang` fields. So when I want to save any object to the object I am setting these fields so that I can build queries later based on them.
I created these two extensions to make it easier: 

`inline fun <reified T : BaseObject?> Box<T>.put(any: T?) {
    any?.localDBTimeStamp = System.currentTimeMillis()
    any?.lang =
        LocaleManager.getinstance().getLanguage() ?: LocaleManager.LocalObject.EN.language
    put(any)
}

inline fun <reified T : BaseObject> Box<T>.put(
    any: Collection<T?>?
) {
    ObjectBox.boxStore.runInTx {
        val list = any?.filterNotNull()
        list?.forEach {
            it.localDBTimeStamp = System.currentTimeMillis()
            it.lang =
                LocaleManager.getinstance().getLanguage() ?: LocaleManager.LocalObject.EN.language
        }
        put(list)
    }

}`

It would be very helpful if we can intercept and convert data before it's being saved.

**Comment by greenrobot-team** [comment]
> It would be very helpful if we can intercept and convert data before it's being saved.

I would argue this is up to the application, not the database. There are likely many different use cases. There is nothing preventing pre-processing of entity objects before putting them (e.g. add a `prepareForPut()` function, special constructor, who knows what).

Closing this then.
