### ISSUE TITLE
Getting row count from an entity

### ISSUE THREAD

**Issue by saravanatm** [objectbox/objectbox-java#878]
How to retrieve the row count based on a condition using objectbox query.

Sample sql query :-
select  sum(case when status='1' then 1 else 0 end) as A ,sum(case when status='2' then 1 else 0 end) as B ,sum(case when status='3' then 1 else 0 end) as C from Orders

**Comment by greenrobot-team** [comment]
In general: instead of running `find()` call `count()` on a `Query`. Or when looking at single properties, try property queries.
https://docs.objectbox.io/queries#propertyquery
