### ISSUE TITLE
Ndk compile the libobjectBox .so .The error is:uses VFP register arguments, output does not .why?

### ISSUE THREAD

**Issue by Laganer** [objectbox/objectbox-java#885]
*Before creating a new issue, make sure that you checked: (1) existing issues, (2) docs (3) FAQ.
TEMPLATE FOR ISSUES ONLY - for feature requests just delete the text and start fresh.
Please help us to fix issues asap: this template reduces checking with you back and forth.
Replace italic sections with your input.
For __support questions__, please use [stackoverflow with the [objectbox] tag](https://stackoverflow.com/questions/tagged/objectbox) - we get notified.*

## Issue Basics
- ObjectBox version (are using the latest version?): *?*
- Reproducibility: *[occurred once only | occasionally without visible pattern | always]*

### Description
*Describe the situation in English in which you encounter the bug.*

### Code
*Provide the code triggering the bug.
Ideally, try to keep it short by removing as much code as possible while preserving the issue.
You get __extra karma points__ for sharing a runnable project on GitHub that reproduces the bug.*

### Logs & stackstraces
*Check if you have relevant logs and/or a stacktrace.
For __build issues__, use `--stacktrace` for the Gradle build (`./gradlew build --stacktrace`).
For __runtime errors__, check Android's Logcat (check also for relevant logs preceeding the issue itself).*

## Entities
*Provide the code for entities related to the bug (shorten to relevant parts).*

## Misc
*Is there anything special about your app?
May transactions or multi-threading play a role?
Did you find any workarounds to prevent the issue?*

**Comment by greenrobot-team** [comment]
@Laganer Sorry, but we need more information than that. E.g. see the issue template above you posted.

**Comment by Laganer** [comment]
Thank you very much for your reply. Here is my files.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "objectbox/objectbox-java"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月27日(星期一) 下午4:16
收件人:&nbsp;"objectbox/objectbox-java"<objectbox-java@noreply.github.com&gt;;
抄送:&nbsp;"春天里"<1021496404@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [objectbox/objectbox-java] Ndk compile the libobjectBox .so .The error is:uses VFP register arguments, output does not .why? (#885)





 
@Laganer Sorry, but we need more information than that. E.g. see the issue template above you posted.

**Comment by greenrobot-team** [comment]
@Laganer Sorry, but GitHub does not auto-add file attachments. Please share what is it that you are trying to do. And how your setup looks like.

**Comment by Laganer** [comment]
I  want to use the database in JNI

# Sets the minimum version of CMake required to build the native library.

cmake_minimum_required(VERSION 3.4.1)
set(CMAKE_VERBOSE_MAKEFILE on)
set(libs "${CMAKE_SOURCE_DIR}/jniLibs")


include_directories(${CMAKE_SOURCE_DIR}/include)
include_directories(${CMAKE_SOURCE_DIR}/include/flatcc)
include_directories(${CMAKE_SOURCE_DIR}/include/opencv)
include_directories(${CMAKE_SOURCE_DIR}/include/opencv2)


# Creates and names a library, sets it as either STATIC
# or SHARED, and provides the relative paths to its source code.
# You can define multiple libraries, and CMake builds them for you.
# Gradle automatically packages shared libraries with your APK.



add_library(libobjectbox SHARED IMPORTED )
set_target_properties(libobjectbox PROPERTIES
        IMPORTED_LOCATION "${libs}/${ANDROID_ABI}/libobjectbox.so")

add_library( # Sets the name of the library.
        blurLap

        # Sets the library as a shared library.
        SHARED

        # Provides a relative path to your source file(s).
        native-lib.cpp
        lapls.cpp
        include/flatcc-src/builder.c
        include/flatcc-src/emitter.c
        include/flatcc-src/refmap.c
 
        )

# Searches for a specified prebuilt library and stores the path as a
# variable. Because CMake includes system libraries in the search path by
# default, you only need to specify the name of the public NDK library
# you want to add. CMake verifies that the library exists before
# completing its build.
find_library( # Sets the name of the path variable.
        jnigraphics-lib

        # Specifies the name of the NDK library that
        # you want CMake to locate.
        jnigraphics)


find_library( # Sets the name of the path variable.
        log-lib

        # Specifies the name of the NDK library that
        # you want CMake to locate.
        log)

# Specifies libraries CMake should link to your target library. You
# can link multiple libraries, such as libraries you define in this
# build script, prebuilt third-party libraries, or system libraries.

target_link_libraries( # Specifies the target library.
        blurLap
        libobjectbox
        # Links the target library to the log library
        # included in the NDK.
        ${log-lib})

**Comment by greenrobot-team** [comment]
Assuming you want to also use the library from Java/Kotlin, you can create it there and then pass a pointer to the BoxStore to our C API.
https://github.com/objectbox/objectbox-c

`long pointer = boxStore.getNativeStore()`
https://objectbox.io/docfiles/java/current/io/objectbox/BoxStore.html#getNativeStore()
> If you want to use the same ObjectBox store using the C API, e.g. via JNI, this gives the required pointer, which you have to pass on to obx_store_wrap(). The procedure is like this:
> 1) you create a BoxStore on the Java side
> 2) you call this method to get the native store pointer
> 3) you pass the native store pointer to your native code (e.g. via JNI)
> 4) your native code calls obx_store_wrap() with the native store pointer to get a OBX_store pointer
> 5) Using the OBX_store pointer, you can use the C API. Note: Once you close() this BoxStore, do not use it from the C API.

**Comment by greenrobot-team** [comment]
Closing as this appears to be resolved. ✅ Feel free to re-open with more information or create a new issue.
