### ISSUE TITLE
Memory Leak with IntentService

### ISSUE THREAD

**Issue by iLazarus** [objectbox/objectbox-java#895]
When I click insert button for insert new data into DB, than I hava a service for check this DB and update them, i found some memory leak in my IntentService . my code look like this!

in Activity

    public class MainActivity extends AppCompatActivity {

    private static final String TAG = "YX_MainActivity";
    private byte[] data = new byte[1024 * 1024 * 10]; // 10MB
    Intent mLeakServiceIntent = null;
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        for (int i = 0; i < data.length; i++) {
            data[i] = 0x31;
        }
        initView();
        mLeakServiceIntent = new Intent(this, LeakService.class);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(mLeakServiceIntent);
        }
    }

    @Override
    protected void onDestroy() {

        stopService(mLeakServiceIntent);
        super.onDestroy();
    }

    private void initView() {
        findViewById(R.id.insert).setOnClickListener((v) -> {

            Record record = new Record();
            record.name = "" + System.currentTimeMillis();
            record.data = data;
            record.touchByIntentService = false;
            ObjectBox.mRecordBox.put(record);
            Log.d(TAG, "object put data");
        });

        findViewById(R.id.stop_service).setOnClickListener((v) -> stopService(mLeakServiceIntent));
    }
}

in IntentService

    public class LeakService extends IntentService {

    private static final String TAG = "YX_LeakService";

    public LeakService() {
        super("LeakService");
    }

    private NotificationManager notificationManager;
    private String notificationId = "channelId";
    private String notificationName = "channelName";

    private boolean isBreak = false;

    private Notification getNotification() {
        Notification.Builder builder = new Notification.Builder(this)
                .setSmallIcon(R.drawable.ic_launcher_foreground)
                .setContentTitle("Memory Leak")
                .setContentText("Open your Android Studio Profiler, than touch button 'insert', you will be found Memory [Others] leak");
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            builder.setChannelId(notificationId);
        }
        Notification notification = builder.build();
        return notification;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        isBreak = false;
        Log.d(TAG, "onCreate: ");
        notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
            NotificationChannel channel = new NotificationChannel(notificationId, notificationName, NotificationManager.IMPORTANCE_HIGH);
            notificationManager.createNotificationChannel(channel);
        }
        startForeground(1,getNotification());
    }

    @Override
    protected void onHandleIntent(@Nullable Intent intent) {
        Log.d(TAG, "LeakService onHandleIntent");

        Query<Record> recordQuery = ObjectBox.mRecordBox.query().equal(Record_.touchByIntentService, false).build();

        while(true) {
            if (isBreak) {
                Log.d(TAG, "onHandleIntent: stop");
                break;
            }
            SystemClock.sleep(1000);
            Record record = recordQuery.findFirst();
            if (record == null) continue;
            record.touchByIntentService = true;
            Log.d(TAG, "onHandleIntent: Be careful of  your Profiler -> Memory -> Others");

             // Memory Leak happen
            ObjectBox.mRecordBox.put(record); // Memory Leak happen

            SystemClock.sleep(1000);
        }
    }

    @Override
    public void onDestroy() {
        isBreak = true;
        Log.d(TAG, "onDestroy: ");
        super.onDestroy();
    }
}

**Comment by greenrobot-team** [comment]
I don't follow, what exactly is leaking here? Anyhow, I would argue this code mis-uses `IntentService` designed to process requests on a background thread as a long-running foreground service.
https://developer.android.com/reference/android/app/IntentService#onHandleIntent(android.content.Intent)

That might lead to undefined behavior and that memory leak.
