### ISSUE TITLE
Error @Index is not supported for double does not tell Entity and Field.

### ISSUE THREAD

**Issue by ridcully99** [objectbox/objectbox-java#902]
**Describe the bug**
When annotating a field of type Double with @Index, the ObjectBox processor shows the following error:

> Note: [ObjectBox] Starting ObjectBox processor (debug: false, incremental: true)
> error: [ObjectBox] 'viewOrder' @Index is not supported for Double, remove @Index.
> [ObjectBox] 'viewOrder' @Index is not supported for Double, remove @Index.
> 
> 1 error

From that error message one cannot tell what Entity and Field it refers too. Of course I can just search through all of my entities, but it would be much easier, if the error message would contain the Entity and Field directly.

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): 2.7.0
 - Reproducibility: 100%

**To Reproduce**

Create an Entity with a field of type Double and annotate the field with @Index.
Try to build the project.

**Expected behavior**
Error should contain Entitiy and Field name.

**Comment by greenrobot-team** [comment]
Thanks. Is it not possible to click on the error message? It should jump to the field that caused the error.

What IDE are you using?

**Comment by greenrobot-team** [comment]
OK, both with Java and Kapt and using Android Studio 4.1 RC1 the message is not clickable. Will look into this. Thanks!

**Comment by greenrobot-team** [comment]
Thanks again, this will be fixed in the next release.

**Comment by ridcully99** [comment]
Sorry I didn't react to your question earlier, but seems you checked for yourself already. Your quick reactions are much appriciated.
