### ISSUE TITLE
Ability to configure sound for ObjectBox DB browser notification

### ISSUE THREAD

**Issue by atulgpt** [objectbox/objectbox-java#903]
Whenever flashing new build it creates ObjectBox DB browser creates a notification sound which is quite unpleasant. 
There should be an option in AndroidObjectBrowser to configure this behavior.

Right now I used to make the channel of ObjectBoxBrowser to silent notification but in case of a reinstall of application those settings gets cleared

**Comment by greenrobot-team** [comment]
Thanks! The next update will change this to a silent notification.
