### ISSUE TITLE
Changelog for 2.7.1 ?

### ISSUE THREAD

**Issue by RobbWatershed** [objectbox/objectbox-java#904]
It looks like v2.7.1 is out, but the changelog is nowhere to be found (neither [here](https://github.com/objectbox/objectbox-java/releases) nor [there](https://docs.objectbox.io/#objectbox-changelog))

Could you please make it available ? Thanks~

**Comment by greenrobot-team** [comment]
Here you go: https://docs.objectbox.io/#v-2-7-1-2020-08-19

**Comment by RobbWatershed** [comment]
Thanks
