### ISSUE TITLE
How to cancel an executing query ？

### ISSUE THREAD

**Issue by 1341290135** [objectbox/objectbox-java#905]
Because of the large amount of data, query takes time (1-4s). When multiple threads execute query at the same time, the speed is slower (2-6s). However, users can quickly select different queries on the UI interface. If we can safely terminate the unused queries. If we call query.close directly will cause the program to crash, can only wait for the end of the query itself。

**Comment by greenrobot-team** [comment]
This sounds more like an application issue. Could this be solved with rate-limiting/debouncing? E.g. do not run more than 1 query at a time; a new query request replaces any waiting request?

**Comment by 1341290135** [comment]
Thank you for your reply.
 
 It is OK to run only 1 query. Can we  safely terminate the previous runing query use query.close() ?

**Comment by greenrobot-team** [comment]
Sorry for the late response. IIRC `query.close()` should only be called once e.g. `find()` has finished, to reclaim resources. E.g. a request queue pattern is what you want here (and then e.g. replace waiting requests, or whatever fits your needs).
