### ISSUE TITLE
DB browser not able to show a derived entity

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#914]
**Describe the bug**
I have an entity, say Word, that extends from another entity, say Text, like:
```
@Entity
public class Text {
    @Id
    public long id;

    public String discId;
}

@Entity
public class Word extends Text {

    public String word;
}
```
Except perhaps the first time after I created an entry in the DB of Word, everytime I use the browser to check on DB Word, it shows an error: "Query response has unknown format.  See console for details.: undefined", at which point I can only press on "DISMISS" to get rid of the error, but the DB is shown as empty.  

BTW, I wonder where to see the console?

The DB appears OK from within my app, though.

ObjectBox 2.7
Device: Lenovo
Android 6

**Comment by greenrobot-team** [comment]
Thanks for reporting. The message talks about the console of the web browser development tools (e.g. press F12).

**Comment by greenrobot-team** [comment]
I can not reproduce this. E.g. the inheriting entity shows data just fine:
![image](https://user-images.githubusercontent.com/13865709/93848271-67d66d80-fca9-11ea-8fcd-0f955e7d03f5.png)

Does this work on an emulator for you? E.g. is it only broken on your device?

Can you check if [our example](https://github.com/objectbox/objectbox-examples/tree/main/android-app-kotlin) works?

**Comment by LeoK987** [comment]
I can't reproduce this anymore.  Not sure what happened before.

**Comment by greenrobot-team** [comment]
Thanks. Closing this then. Feel free to comment if you have more details on how to reproduce.

**Comment by RobbWatershed** [comment]
For the record, if anyone comes across this issue by googling as I did, my problem was a numeric field having the value "NaN" after an unfortunate division by zero that has been stored in the DB.

The ObjectBox Browser UI didn't know what to display for that value and gave me that infamous "Query response has unknown format. See console for details.: undefined"

**Comment by greenrobot-team** [comment]
@RobbWatershed Thanks, I created a new issue as it appears unrelated (above entity does not have a numeric property). 👉  #984
