### ISSUE TITLE
Generated code unsupported in Kotlin v1.4.x

### ISSUE THREAD

**Issue by shivanshs9** [objectbox/objectbox-java#917]
**Describe the bug**
Kotlin v1.4.x had some major updates in type inference algorithm breaking existing builds. I updated all my relevant code which couldn't compile but Objectbox generated code also breaks when compiled using latest Kotlin.

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): [e.g. 2.7.0] 2.7.1
 - Reproducibility: [e.g. occurred once only | occasionally without visible pattern | always] always
 - Device: [e.g. Galaxy S20] *
 - OS: [e.g. Android 10] *

**To Reproduce**
1. Put `ext.kotlin_version` as `1.4.10`.
2. Build
3. See error

**Expected behavior**
Build should pass, as it has been, since I didn't even touch any entitiy or ObjectBox code.

**Code**
If applicable, add code to help explain your problem.
 - Include affected entity classes.
 - Please remove any unnecessary or confidential parts.
 - At best, link to or attach a project with a failing test.

**Logs, stack traces**
<details>
<summary>Build logs</summary>

```
> Task :app:compileCoreDebugJavaWithJavac
/home/shivanshs9/projects/Checkin-Android/app/build/generated/source/kapt/coreDebug/com/checkin/app/checkin/menu/models/MenuItemModel_.java:47: error: cannot infer type arguments for Property<>
        new io.objectbox.Property<>(__INSTANCE, 2, 10, String.class, "typeNames", false, "typeNames", ListConverter.class, List.class);
        ^
/home/shivanshs9/projects/Checkin-Android/app/build/generated/source/kapt/coreDebug/com/checkin/app/checkin/menu/models/MenuItemModel_.java:50: error: cannot infer type arguments for Property<>
        new io.objectbox.Property<>(__INSTANCE, 3, 11, String.class, "typeCosts", false, "typeCosts", ListConverter.class, List.class);
        ^
/home/shivanshs9/projects/Checkin-Android/app/build/generated/source/kapt/coreDebug/com/checkin/app/checkin/menu/models/MenuItemModel_.java:56: error: cannot infer type arguments for Property<>
        new io.objectbox.Property<>(__INSTANCE, 5, 6, String.class, "tags", false, "tags", ListConverter.class, List.class);
        ^
/home/shivanshs9/projects/Checkin-Android/app/build/generated/source/kapt/coreDebug/com/checkin/app/checkin/menu/models/MenuItemModel_.java:59: error: cannot infer type arguments for Property<>
        new io.objectbox.Property<>(__INSTANCE, 6, 7, String.class, "availableMeals", false, "availableMeals", ListConverter.class, List.class);
        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

> Task :app:compileCoreDebugJavaWithJavac FAILED
```
</details>

**Additional Context**
Objectbox `v2.5.1` works.

**Comment by greenrobot-team** [comment]
@shivanshs9 Thanks. Did you make sure to do a clean build (or Rebuild in Android Studio)?
