### ISSUE TITLE
Related entities not saved after settind `Id = 0`

### ISSUE THREAD

**Issue by mecoFarid** [objectbox/objectbox-java#922]
**Bug dexcription**
This part of [Documention](https://docs.objectbox.io/relations#updating-relations) is quite misleading. To be more specific

> For convenience, ToOne and ToMany will put related entities if they do not yet exist (ID == 0).

No, it doesn't work as it is described

**Basic info:**
 - ObjectBox version [2.6.0]
 - Reproducibility: [always]
 - Device: [N/A]
 - OS: [Android]

**To Reproduce**
1. Create a `Parent` with `Child` entities
2. Create relation as follows: `Parent` relates to `Child` as `ToMany<Child>`
3. Create a parent add children and save (put)
4. Get the same `Parent` with `Children` from 'BoxStore' and keep in heap
5. Delete all entities
6. Set `Id = 0` in all children of retreived parent
7. Save retreived `Parent` object with changes applied
8.`ObjectBox` will save only `Parent` not the related `Child` object but in documentation it clearly states that related entities with `Id = 0` will be saved

**Comment by greenrobot-team** [comment]
Thanks! I updated the documentation.
https://docs.objectbox.io/relations#updating-relations

ToMany will only put added Objects that are new. So to work around this it's probably enough to remove the Objects from the ToMany, then add them again.

**Comment by greenrobot-team** [comment]
Closing this as the documentation issue was resolved. Let me know if it's still unclear.
