### ISSUE TITLE
Unresolved reference: ObjectBoxDataSource [android-objectbrowser]

### ISSUE THREAD

**Issue by devjn** [objectbox/objectbox-java#932]
Using `io.objectbox:objectbox-android-objectbrowser:2.8.1` I get "_Unresolved reference: ObjectBoxDataSource_".
Changing to `io.objectbox:objectbox-android` fixes the issue

**Basic info:**
 - ObjectBox version 2.8.1 (latest)
 - Reproducibility: always

**To Reproduce**
```
dependencies {
    implementation("io.objectbox:objectbox-android-objectbrowser:2.8.1")
}

// Apply plugin at the end
apply(plugin = "io.objectbox")
```

I am using it in Kotlin based project if it is relevant.

**Comment by greenrobot-team** [comment]
I tried to reproduce this using our [Kotlin example app](https://github.com/objectbox/objectbox-examples/tree/main/android-app-kotlin) to no success. Maybe sync or rebuild your project?

Also note our recommended setup for using Data browser: https://docs.objectbox.io/data-browser#setup

If this is still an issue, please provide us with an example project that reproduces this issue.

**Comment by devjn** [comment]
Here is a very simplified example project https://github.com/devjn/ObjectBoxRepro

**Comment by greenrobot-team** [comment]
You are trying to use the ObjectBox code in a module different from the one where the ObjectBox library is added as a dependency.

You have two options:
- change the dependency configuration from `implementation` to `api` so the `common` module exposes it to modules using it, or
- add `objectbox-android` as a dependency to your `app` module.

**Comment by greenrobot-team** [comment]
Closing this as this is not an ObjectBox issue, but a Gradle usage question.
