### ISSUE TITLE
Corrupt DB, min key size violated

### ISSUE THREAD

**Issue by ffyliu** [objectbox/objectbox-java#934]
:rotating_light: First, please check:
 - existing issues,
 - Docs https://docs.objectbox.io/
 - Troubleshooting page https://docs.objectbox.io/troubleshooting
 - FAQ page https://docs.objectbox.io/faq

**Describe the bug**
A crash happened occasionally, which showed that the database was damaged, the app could not be started, and the database could not be recovered at present. I want to know under what circumstances this exception will occur.Thank you.

**Basic info (please complete the following information):**
 - ObjectBox version: 2.5.0
 - Reproducibility: occurred once only
 - Device: red mi
 - OS: Android 10

**Logs, stack traces**

12-28 11:14:28.861 28095 28137 E com.cc.a.b: normalException thread name is RxCachedThreadScheduler-1,willCollectException is true, ex is io.objectbox.exception.DbException: Corrupt DB, min key size violated: 0
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at io.objectbox.BoxStore.nativeCreate(Native Method)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at io.objectbox.BoxStore.<init>(BoxStore.java:205)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at com.sogou.xiaop_android.business.model.dao.StoreManager.createBoxStore(StoreManager.java:68)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at com.sogou.xiaop_android.business.model.dao.StoreManager.getBoxStore(StoreManager.java:49)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at com.sogou.xiaop_android.business.model.dao.entity.Emoji.getAllEmoji(Emoji.java:21)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at com.sogou.xiaop_android.business.message.EmojiUtils.lambda$checkEmojiIntegrity$2(EmojiUtils.java:60)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at com.sogou.xiaop_android.business.message.-$$Lambda$EmojiUtils$y89A_gAtwwE-D6aiAEVRnexe3ck.subscribe(Unknown Source:0)
12-28 11:14:28.861 28095 28137 E com.cc.a.b: at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)

**Comment by greenrobot-team** [comment]
As said in #800, please update to the latest version of ObjectBox (right now 2.8.1).
https://docs.objectbox.io/
