### ISSUE TITLE
Observers won't work if the return value of observer is not kept

### ISSUE THREAD

**Issue by neroux** [objectbox/objectbox-java#936]
This probably is rather a documentation "bug" than a code one, but the thing itself is very AngularJS-like with its random idea of implementing dependency injection via parameter names and I believe I should document that here for future use.

It just cost me about an hour of debugging to find out why my call to `observer` was only called once. Please try to spot the difference between these three calls

    DataSubscription localVariable = boxStore.boxFor(Myclass.class).query().build().subscribe().observer(data -> {});
    globalVariable = boxStore.boxFor(Myclass.class).query().build().subscribe().observer(data -> {});
    boxStore.boxFor(Myclass.class).query().build().subscribe().observer(data -> {});

Anyone with more than a week of Java experience would say they execute the same code and - in this case - configure an observer which is subsequently called on changes.

Well, that's even partially true. All three cases will configure an observer and that observer will actually work as long one does not leave the current variable scope. The moment one does that only the second call will actually work, because the reference returned by `observer` is apparently crucial and once `finalize` is called on it, the whole observer will stop working.

I am not saying one shouldn't clean up and calling `cancel` on the data subscription is certainly a good idea (for which one will need to keep a reference) but it should still not just stop working without any further notice if one does not keep that reference (either explicitly or via `DataSubscriptionList`). I only figured that out when I came across the following sentence from https://github.com/objectbox/objectbox-java/issues/862#issuecomment-640541945

> You need to hold onto the Disposable. Otherwise it gets garabage collected and the subscription is cancelled.

Neither the documentation nor the JavaDoc really point that out. https://docs.objectbox.io/data-observers-and-rx does not mention that at all and the JavaDoc at https://objectbox.io/docfiles/java/current/io/objectbox/reactive/SubscriptionBuilder.html#observer(io.objectbox.reactive.DataObserver) has a vague reference about it

> Note: you must keep the returned DataSubscription to cancel it.

but only mentions it in the context of cancellation, it does not state it is absolutely necessary for it to work at all. Only https://objectbox.io/docfiles/java/current/io/objectbox/reactive/SubscriptionBuilder.html refers to `weak` being called implicitly.

This really should be made obvious in the documentation itself. Again, this issue is mostly for future reference.

**Comment by neroux** [comment]
https://objectbox.io/docfiles/java/current/io/objectbox/query/Query.html#subscribe() seems to go into detail here

>  Stale observers: you must hold on to the Query or DataSubscription objects to keep your DataObservers active. If this Query is not referenced anymore (along with its DataSubscriptions, which hold a reference to the Query internally), it may be GCed and observers may become stale (won't receive anymore data).

but that should really be made obvious at https://docs.objectbox.io/data-observers-and-rx, even some of the examples do not keep the return value.

**Comment by greenrobot-team** [comment]
Not to step on any toes, but it kind of is a core Java feature that once a class instance/object is no longer referenced it will stop existing after the next garbage collector run. So e.g. if you want an instance to keep existing outside of a local scope (e.g. method body), keep a reference in a more global scope (e.g. activity/fragment in Android) to it. This is nothing ObjectBox specific, no?

I guess we can improve our docs to point out this common pitfall.

**Comment by greenrobot-team** [comment]
Ah, thanks. Can you elaborate? Would you expect e.g. `Query` to hold onto the reference?

Side note: improved our observer docs a bit. https://docs.objectbox.io/data-observers-and-rx

**Comment by neroux** [comment]
Probably not query, but I would have expected the subscriper to be kept somewhere on a database level. After all that is what will be happening to a certain extent I assume and the query is only an additional layer which the database uses to filter the live data.

IMHO the subscription is not all that well placed on the query level in the first place, but that's certainly a subjective :)

I noticed you added a few "keep a reference" sentences 👍🏻. May I suggest to emphasise this maybe bold, red, blinking (okay, maybe not blinking but you get my point I guess :)) Thanks.

**Comment by greenrobot-team** [comment]
Duplicate of #215.
