### ISSUE TITLE
I have a database, how to know through the code inside the field and the contents of the database

### ISSUE THREAD

**Issue by zhanglixing15133991761** [objectbox/objectbox-java#942]
:rotating_light: First, please check:
 - existing issues,
 - Docs https://docs.objectbox.io/
 - Troubleshooting page https://docs.objectbox.io/troubleshooting
 - FAQ page https://docs.objectbox.io/faq

Start with a clear and concise description of what problem you are trying to solve.
Often there is already a solution! 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context (e.g. platform or language) about the feature request here.

**Comment by greenrobot-team** [comment]
I'm not sure what you want. Please fill out the issue template and add more details.
