### ISSUE TITLE
baseDirectory(File baseDirectory)  Provide the way of Uri to pass in parameters

### ISSUE THREAD

**Issue by GXSZone** [objectbox/objectbox-java#947]
Due to the storage change of Android 10, you can't create a file directly in the public directory or other directories by using new file(). Can you pass in parameters by providing Uri

From translation

**Comment by greenrobot-team** [comment]
Isn't the whole point of scoped storage to prevent apps from doing this? And https://developer.android.com/training/data-storage/app-specific#external still works, no?

**Comment by GXSZone** [comment]
thanks
