### ISSUE TITLE
FileCorruptException with "Corrupt DB, min key size violated: 0" message

### ISSUE THREAD

**Issue by mecoFarid** [objectbox/objectbox-java#950]
**Bug**
When `removeAll()` is called `FileCorruptException` is thrown. Steps that lead to the problem.
1. Mobile device shuts down unexpectedly
2. User restarts the device (device restarted automatically)
3. Tries to log in to our app. On login, we delete all data from "X" entity with `removeAll()`. At this specific point, it throws the exception

**Basic info**
 - ObjectBox version: 2.7.0
 - Reproducibility: occurred once only
 - Device: Redmi Note 8
 - OS: Android 10

**Code**
Only related code snippet attached below:
`boxStrore.boxFor(X.class).removeAll();`

**Logs, stack traces**
> Caused by io.objectbox.exception.FileCorruptException
> Corrupt DB, min key size violated: 0
> io.objectbox.Cursor.nativeDeleteAll (Cursor.java)
> io.objectbox.Cursor.deleteAll (Cursor.java:2)
> io.objectbox.Box.removeAll (Box.java:4)

**Comment by greenrobot-team** [comment]
> Mobile device shuts down unexpectedly

This sounds like the unexpected shutdown caused the database file to get corrupted?

It may be possible to salvage the database file using new APIs introduced with 2.7.0:
https://github.com/objectbox/objectbox-examples/blob/1651d96212985af46d01346dfcc6201cfb01230f/android-app/src/main/java/io/objectbox/example/ObjectBox.java#L17-L28
