### ISSUE TITLE
description of method "find" is inaccurate on Android Studio

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#951]
io.objectbox.query.Query<T>
@Nonnull
public java.util.List<T> find(long offset,
                                       long limit)
Find all Objects matching the query between the given offset and limit. This helps with pagination.
  Gradle: io.objectbox:objectbox-java:2.8.1

The above about "limit" sounds different from what's in the documentation:

"At most limit results of this query are returned."

**Comment by greenrobot-team** [comment]
Thanks, but I'm not sure what you mean. Can you provide links, maybe?

**Comment by LeoK987** [comment]
In Android Studio, open a Java file where there are statements calling method "find(long offset, long limit)", move mouse pointer onto the method name, then in the popup the inaccurate description is shown.

**Comment by greenrobot-team** [comment]
Now I get it. You are talking about the different description of https://docs.objectbox.io/queries#limit-offset-and-pagination vs. the Javadoc
https://github.com/objectbox/objectbox-java/blob/a8d62b4ae99c8f775138b44eb4add55bdb4628d1/objectbox-java/src/main/java/io/objectbox/query/Query.java#L222-L224

Actually this can be improved, yes. It sounds like it will always return `limit` results, where it is up to `limit` results. Thanks!
