### ISSUE TITLE
need a way to un-reference ToMany relations

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#957]
I understand that when ObjectBox loads an entity with ToMany relations, the relations are loaded as lazy, so it doesn't cost too much resource.  But when any of the relations is accessed, the real data of the relation get loaded in, and this is OK.  What becomes an issue is when I try to use or update a bulk of entities during which time the relations are accessed (only for the purpose of retrieving info), and the real data of the relations stay in memory from then on, which can be very expensive for large data sets.

So I hope to have a way to un-reference the relations at some point so GC can clear them out and the relations become again "lazy".  Is this possible at the moment?

**Comment by greenrobot-team** [comment]
Not sure, but is `ToMany.reset()` what you are looking for?

**Comment by LeoK987** [comment]
What I am looking for is a way to unload the cached ToMany relations to return them to the original uncached lazy status, or ultimately, to reclaim memory taken by these ToMany relations that are not needed when their holding entity is still of use.

**Comment by greenrobot-team** [comment]
So why does `ToMany.reset()` not work then?

**Comment by LeoK987** [comment]
I didn't know about it.  Sounds like it would work.  Will try it.

**Comment by LeoK987** [comment]
Indeed, ToMany.reset() as desired.
