### ISSUE TITLE
result of findLazy is erased

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#961]
ObjectBox 2.9.0

In Android Studio, when pointer is on findLazy() in statement `List<TextEntry> tList = box.query().build().findLazy();`
there is a popup warning:

`Unchecked assignment: 'io.objectbox.query.LazyList' to 'java.util.List<info.puzz.dao.models.TextEntry>'. Reason: 'box.build()' has raw type, so result of findLazy is erased `

What does that mean?  Is it not advisable to assign results of findLazy() to a List variable?

**Comment by greenrobot-team** [comment]
Sounds like a debugger bug? Not sure what the issue is here in regard to ObjectBox. If you still think it is, please provide e.g. a failing test.
