### ISSUE TITLE
How to solve the problem of probabilistic failure to find SO library?

### ISSUE THREAD

**Issue by qeadsw** [objectbox/objectbox-java#966]
Adroid: 7.0+
AndroidStudeio: 4.x
Objectbox: 2.9.1

log:
dlopen failed: library "/data/app/com.test.myapplication-2/base.apk!/lib/armeabi-v7a/libobjectbox-jni.so" not found

**Comment by greenrobot-team** [comment]
Can you please share more details on which devices this is happening? And how frequent or on what percentage?

Are you using App Bundle?

Does your AndroidManifest.xml change `android:extractNativeLibs` away from the recommended `false`?

**Comment by qeadsw** [comment]
@greenrobot-team s

I have tried this approach, but the problem still occurs at boot time. I saw a problem with the "libs" and "jniLibs" directories on the Internet.

**Comment by greenrobot-team** [comment]
Not responding to actual questions, probably a bot. Closing.
