### ISSUE TITLE
 How can I update and create a part of the batch data?

### ISSUE THREAD

**Issue by zhieci** [objectbox/objectbox-java#982]
Before the transactional write one would want to distinguish if a record already exist in DB. If it doesn't, a new record is put. If it does exist, then one would update the existing one with the new info. So how can I update and create a part of the batch data?

**Comment by greenrobot-team** [comment]
Typically existing objects have an `ID > 0` assigned. Not sure what your exact use case is. Maybe see https://docs.objectbox.io/advanced/object-ids

Maybe also #509?
