### ISSUE TITLE
Is there a roadmap for "update by multiple unique fields" feature?

### ISSUE THREAD

**Issue by mecoFarid** [objectbox/objectbox-java#985]
What I am looking for is to update a "row" with multiple unique fields.

**A bit insight:** I'm aware that there is no update functionality in ObjectBox unless the entity to be persisted has "boxId" assigned to it. The closest feature/issue I found is #509 which, ideally, would update entity based on the unique identifier if implemented but as of now, it throws an intended exception.

Now let's say I want something a bit "deadlier"; updating fields based on multiple unique fields. Say we have a `Client` entity
**Client class:**
```
public class Client{
    private long clientId;
    private long division;
    private long firm;

    private long clientName;
    // trimmed fields
}
```

A client may have different combinations of `division` and `firm`. Ideally, we should be having two entities `Client` and `DivisionFirmToClientMap` but unfortunately, we don't, and changing all that logic would require quite a work.

**The problem:** 
As I mentioned above a client can have different combinations of `division` and `firm`. Unique identifiers for any `Client` are `division`, `firm`, and `clientId`. We have 10000 `Client`s in local DB and on the next fetch we get 11000 `Client`s from a remote server. Is there any way in `ObjectBox` to update entities without manually traversing through and defining which needs to be removed and persisted?

**Comment by greenrobot-team** [comment]
How is this different from the replace on conflict strategy suggested in #509?

You may want to try the new `@Unique(onConflict = ConflictStrategy.REPLACE)` of the 2.9.2-RC preview release.
