### ISSUE TITLE
Could i visit other program's data.mdb file?

### ISSUE THREAD

**Issue by puguomai** [objectbox/objectbox-java#992]
I have a data.mdb file,but i don't know about it.I need visit this file,how should i do?

**Comment by greenrobot-team** [comment]
Note that the `.mdb` files created by ObjectBox are still ObjectBox specific. To open them write an application using any of the supported languages: https://objectbox.io/dev-get-started/

Or for Android you can also use the data browser: https://docs.objectbox.io/data-browser
