### ISSUE TITLE
ToOne object is null inside com.jega.entity.UserEntity

### ISSUE THREAD

**Issue by jegalirisoft** [objectbox/objectbox-java#994]
I've entity class with ToOne relation. when we query the parent class we are seeing the exception java.lang.IllegalStateException: ToOne object is null inside com.jega.entity.UserEntity

**Entity class** 
```
@Entity
data class UserEntity(
    @Id
    var id: Long = 0,
    var name: String
) {
    var address: ToOne<AddressEntity>? = null
}


@Entity
data class AddressEntity(
    @Id
    var id: Long=0,
    var streetLine: String,
    var streetLine2: String,
    var locality: String,
    var city: String,
    var state: String,
    var zipcode: String,
    var landmark: String? = null
)

```
**Exception** 

```

java.lang.IllegalStateException: ToOne object is null inside com.jega.entity.UserEntity
at io.objectbox.Cursor.nativeFirstEntity(Native Method)
at io.objectbox.Cursor.first(Cursor.java:197)
at io.objectbox.Box.getAll(Box.java:310)

```

**Comment by greenrobot-team** [comment]
Can you please share more about your setup? E.g. is this Android? Is this on device? Is this a local/instrumented test?

This may be related to the byte code transformer not running, which adds initializers for ToOne. See https://docs.objectbox.io/relations#initialization-magic

**Comment by jegalirisoft** [comment]
it is android project and running on android device Samsung s9 (Android 11).

**Comment by jegalirisoft** [comment]
@greenrobot-team  any updates ?

**Comment by greenrobot-team** [comment]
Try to change your property to `lateinit var address: ToOne<AddressEntity>` like the docs suggest.

If that won't help, as I said, see https://docs.objectbox.io/relations#initialization-magic on how to add the initializer yourself.

**Comment by greenrobot-team** [comment]
@fllaryora Is this an Android project? Did you try to manually initialize the to-one property as suggested in https://docs.objectbox.io/relations#initialization-magic?

**Comment by fllaryora** [comment]
@greenrobot-team Yes, it is an android project.
Yes, I have read that document and tried with it and without it.

**Comment by greenrobot-team** [comment]
@fllaryora Can you please share a minimal example project so we can reproduce this?

Just to make sure, the following does *not* work:
```kotlin
@Entity
data class PillTaken (
    @Id
    var id: Long = 0L
)  {
    var pill = ToOne<Pill>(this, PillTaken_.pill)
    @JvmField
    @Transient
    @Suppress("PropertyName")
    var __boxStore: BoxStore? = null
}
```
Is that correct?

**Comment by fllaryora** [comment]
Hello @greenrobot-team 
First,  let me thank you for your time.
 
And Yes, Despite using your suggestion in  my entity

```
import com.intecanar.ondiet.data.database.TimeConverterForObjectBox
import io.objectbox.BoxStore
import io.objectbox.annotation.Convert
import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.relation.ToOne
import java.time.OffsetDateTime

@Entity
data class PillTaken (
    @Id
    var id: Long = 0L,
    @Convert(converter = TimeConverterForObjectBox::class, dbType = String::class)
    val date: OffsetDateTime,
    val isTaken: Boolean = true
) : Graphable, Timelineable {
    var pill = ToOne<Pill>(this, PillTaken_.pill)
    @JvmField
    @Transient
    @Suppress("PropertyName")
    var __boxStore: BoxStore? = null
    override fun getX() = date
    override fun getY() = if(isTaken) 1.0f else 0.0f
    override fun getTime() = date
    override fun getLabel() = pill.target.name
    //override fun getLabel() = pill.target.name
    override fun ischecked() = isTaken
}
```

I am getting the exception
E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.intecanar.ondiet, PID: 15846
    java.lang.IllegalStateException: ToOne object is null inside com.intecanar.ondiet.data.database.entities.PillTaken
        at io.objectbox.query.Query.**nativeFind**(Native Method)
        at io.objectbox.query.Query$3.call(Query.java:209)
        at io.objectbox.query.Query$3.call(Query.java:206)
        at io.objectbox.BoxStore.callInReadTx(BoxStore.java:759)
        at io.objectbox.BoxStore.callInReadTxWithRetry(BoxStore.java:704)
        at io.objectbox.query.Query.callInReadTx(Query.java:293)
        at io.objectbox.query.Query.find(Query.java:206)
        at com.intecanar.ondiet.data.database.dao.PillTakenDAO.deleteByPill(PillTakenDAO.kt:43)
        at com.intecanar.ondiet.domain.pill.FetchPillsUseCaseSync.deletePill(FetchPillsUseCaseSync.kt:23)
        at com.intecanar.ondiet.domain.pill.DeletePillUseCase$deletePill$1.run(DeletePillUseCase.kt:20)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 15846 SIG: 9

**nativeFind** method always fail I mean I tried different alternatives such as the use of backlinks.

Thanks in advance.
Francisco.

**Comment by fllaryora** [comment]
@greenrobot-team 
Maybe you are wandering about how I store the new entity:

```
val pillTaken : PillTaken= PillTaken(0L, someDayAtTheMorning)
pillTaken.pill.target = it //it is a pill
val mPillTakenBox = ObjectBox.mBoxStore.boxFor(PillTaken::class.java)
mPillTakenBox.put(pillTaken)
```

Or /And Maybe you are wandering about how I find :
```
mPillTakenBox.query()
            .equal(PillTaken_.pillId, pill.id)
            .order(PillTaken_.date, QueryBuilder.CASE_SENSITIVE ).build()
```
Thanks.

**Comment by greenrobot-team** [comment]
> ext.objectboxVersion = '2.5.1'

@fllaryora I just saw that you are using ObjectBox 2.5.1? Does this also happen with the latest version `2.9.1` or the latest preview release `2.9.2-RC4`?

**Comment by fllaryora** [comment]
@greenrobot-team
  If I update the dependency from 2.5.1 to 2.9.1.
I am getting the exception
```
E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.intecanar.ondiet, PID: 27126
    java.lang.IllegalStateException: ToOne object is null inside com.intecanar.ondiet.data.database.entities.PillTaken
        at io.objectbox.query.Query.**nativeFind**(Native Method)
        at io.objectbox.query.Query.lambda$find$2$Query(Query.java:204)
        at io.objectbox.query.-$$Lambda$Query$ovRjxPApUS12yGDt7cTU1SPw8Ec.call(Unknown Source:2)
        at io.objectbox.BoxStore.callInReadTx(BoxStore.java:897)
        at io.objectbox.BoxStore.callInReadTxWithRetry(BoxStore.java:843)
        at io.objectbox.query.Query.callInReadTx(Query.java:292)
        at io.objectbox.query.Query.find(Query.java:203)
        at com.intecanar.ondiet.data.database.dao.PillTakenDAO.deleteByPill(PillTakenDAO.kt:43)
        at com.intecanar.ondiet.domain.pill.FetchPillsUseCaseSync.deletePill(FetchPillsUseCaseSync.kt:23)
        at com.intecanar.ondiet.domain.pill.DeletePillUseCase$deletePill$1.run(DeletePillUseCase.kt:20)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```
Native find is still failing.
Backing on my steps regarding how I store the new entity, I could see that I have never use the __boxStore property.

Thanks in advance.

**Comment by greenrobot-team** [comment]
@fllaryora 

> I could see that I have never use the __boxStore property

That is fine, this is only [used by ObjectBox itself](https://github.com/objectbox/objectbox-java/blob/54298e13617ce771dda13eb2e96c5d53bd4eda2b/objectbox-java/src/main/java/io/objectbox/relation/ToOne.java#L111-L134) via reflection.

The underlying issue is that there must be a default or all argument constructor for that data class that does not initialize the ToOne. I see that `PillTaken` does not provide a default value for `date`, so no default constructor will be available.

So maybe try something like:
```
@Entity
data class PillTaken (
    @Id
    var id: Long = 0L,
    @Convert(converter = TimeConverterForObjectBox::class, dbType = String::class)
    val date: OffsetDateTime? = null, // provide default values for all parameters to ensure a default constructor exists
    val isTaken: Boolean = true
)
```

**Comment by fllaryora** [comment]
@greenrobot-team 
I think you solve the issue. The following code let me insert, find as well as delete entities those are enough to me:

```
import com.intecanar.ondiet.data.database.TimeConverterForObjectBox
import io.objectbox.BoxStore
import io.objectbox.annotation.Convert
import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.relation.ToOne
import java.time.OffsetDateTime

@Entity
data class PillTaken (
    @Id
    var id: Long = 0L,///must be called id and must be a Long :(
    @Convert(converter = TimeConverterForObjectBox::class, dbType = String::class)
    // provide default values for all parameters to ensure a default constructor exists
    val date: OffsetDateTime = OffsetDateTime.now(),
    val isTaken: Boolean = true //always true otherwise the row would not exist
) : TodoLineable {
    var pill = ToOne<Pill>(this, PillTaken_.pill)
    @JvmField
    @Transient
    @Suppress("PropertyName")
    var __boxStore: BoxStore? = null
    override fun getTime() = date
    override fun getRatingT() = if(isTaken) 10 else 0
    override fun getShowRating() = false
}
```
Thank you greenrobot!

**Comment by greenrobot-team** [comment]
Closing this then as the original poster has also not replied.
