### ISSUE TITLE
Use Universal function to remove and Put Boxes data

### ISSUE THREAD

**Issue by TechNov** [objectbox/objectbox-java#997]
Hello, 
i want to implement an function who permit me to remove and save data from all Boxes like this:

`public static void RevomeAllAndSaveAll(Box<?> objectbox, List<?> ListData)
    {
        objectbox.removeAll();
        objectbox.put(ListData);
    }`
thank's.

**Comment by greenrobot-team** [comment]
There is `BoxStore.removeAllObjects()`. As for the put part I'm not sure if that would work with Java generics and `BoxStore.boxFor​(java.lang.Class<T> entityClass)`. But you are welcome to make a suggestion!
